// packages/plugin-annotation/src/vue/components/renderers/callout-free-text-renderer.vue
<template>
  <CalloutFreeTextVue
    :documentId="documentId"
    :isSelected="isSelected"
    :isEditing="isEditing"
    :annotation="{ ...annotation, object: currentObject }"
    :pageIndex="pageIndex"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfFreeTextAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import CalloutFreeTextVue from '../annotations/callout-free-text.vue';

const {
  annotation,
  currentObject,
  isSelected,
  isEditing,
  scale,
  pageIndex,
  documentId,
  onClick,
  appearanceActive,
} = defineProps<AnnotationRendererProps<PdfFreeTextAnnoObject>>();
</script>

// packages/plugin-annotation/src/svelte/components/renderers/CalloutFreeTextRenderer.svelte
<script lang="ts">
  import type { PdfFreeTextAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import CalloutFreeText from '../annotations/CalloutFreeText.svelte';

  let {
    annotation,
    currentObject,
    isSelected,
    isEditing,
    scale,
    pageIndex,
    documentId,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfFreeTextAnnoObject> = $props();
</script>

<CalloutFreeText
  {documentId}
  {isSelected}
  {isEditing}
  annotation={{ ...annotation, object: currentObject }}
  {pageIndex}
  {scale}
  {onClick}
  {appearanceActive}
/>
