// packages/plugin-annotation/src/vue/components/renderers/caret-renderer.vue
<template>
  <CaretVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfCaretAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import CaretVue from '../annotations/caret.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfCaretAnnoObject>>();
</script>

// packages/plugin-annotation/src/svelte/components/renderers/CaretRenderer.svelte
<script lang="ts">
  import type { PdfCaretAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Caret from '../annotations/Caret.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfCaretAnnoObject> = $props();
</script>

<Caret {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />
