// packages/plugin-annotation/src/vue/components/renderers/polygon-renderer.vue
<template>
  <PolygonVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfPolygonAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import PolygonVue from '../annotations/polygon.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfPolygonAnnoObject>>();
</script>

// packages/plugin-annotation/src/svelte/components/renderers/PolygonRenderer.svelte
<script lang="ts">
  import type { PdfPolygonAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Polygon from '../annotations/Polygon.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfPolygonAnnoObject> = $props();
</script>

<Polygon {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />
