// packages/plugin-annotation/src/vue/components/renderers/polyline-renderer.vue
<template>
  <PolylineVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfPolylineAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import PolylineVue from '../annotations/polyline.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfPolylineAnnoObject>>();
</script>

// packages/plugin-annotation/src/svelte/components/renderers/PolylineRenderer.svelte
<script lang="ts">
  import type { PdfPolylineAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Polyline from '../annotations/Polyline.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfPolylineAnnoObject> = $props();
</script>

<Polyline {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />
