// packages/plugin-loader/src/svelte/components/file-picker.svelte
<script lang="ts">
  import { useLoaderCapability } from '../hooks';

  const { provides: loaderProvides } = useLoaderCapability();

  let inputRef: HTMLInputElement | null = null;

  // Subscribe/unsubscribe whenever the capability changes
  $effect(() => {
    const cap = loaderProvides;
    if (!cap) return;

    // Listen for "open file" requests
    const unsubscribe = cap.onOpenFileRequest((req) => {
      if (req === 'open' && inputRef) {
        inputRef.click();
      }
    });

    // Cleanup function
    return () => {
      unsubscribe();
    };
  });

  // Handle actual file selection
  async function onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    const cap = loaderProvides;

    if (file && cap) {
      const arrayBuffer = await file.arrayBuffer();
      await cap.loadDocument({
        type: 'buffer',
        pdfFile: {
          id: Math.random().toString(36).substring(2, 15),
          name: file.name,
          content: arrayBuffer,
        },
      });
    }
  }
</script>

<!-- Hidden file picker -->
<input
  bind:this={inputRef}
  type="file"
  accept="application/pdf"
  style="display: none"
  onchange={onChange}
/>

// packages/plugin-loader/src/vue/components/file-picker.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { useLoaderCapability } from '../hooks';

const { provides: loaderProvides } = useLoaderCapability();
const inputRef = ref<HTMLInputElement | null>(null);

let unsubscribe: (() => void) | null = null;

onMounted(() => {
  const cap = loaderProvides.value;
  if (!cap) return;

  // Listen for "open file" requests
  unsubscribe = cap.onOpenFileRequest((req) => {
    if (req === 'open' && inputRef.value) {
      inputRef.value.click();
    }
  });
});

onUnmounted(() => {
  if (unsubscribe) {
    unsubscribe();
  }
});

// Handle actual file selection
const onChange = async (event: Event) => {
  const target = event.target as HTMLInputElement;
  const file = target.files?.[0];
  const cap = loaderProvides.value;

  if (file && cap) {
    const arrayBuffer = await file.arrayBuffer();
    await cap.loadDocument({
      type: 'buffer',
      pdfFile: {
        id: Math.random().toString(36).substring(2, 15),
        content: arrayBuffer,
      },
    });
  }
};
</script>

<template>
  <!-- Hidden file picker -->
  <input
    ref="inputRef"
    type="file"
    accept="application/pdf"
    style="display: none"
    @change="onChange"
  />
</template>
