// packages/plugin-form/src/vue/components/fields/push-button-field.vue
<script setup lang="ts">
import { computed } from 'vue';
import { PDF_FORM_FIELD_FLAG } from '@embedpdf/models';
import type { PushButtonFieldProps } from '../../../shared/components/types';
import { buttonStyle } from './style';

const props = defineProps<PushButtonFieldProps>();

const field = computed(() => props.annotation.field);
const flag = computed(() => field.value.flag);
const name = computed(() => field.value.alternateName || field.value.name);
const isDisabled = computed(
  () => !props.isEditable || !!(flag.value & PDF_FORM_FIELD_FLAG.READONLY),
);
</script>

<template>
  <button :disabled="isDisabled" :aria-label="name" :style="buttonStyle">
    {{ name }}
  </button>
</template>

// packages/plugin-form/src/svelte/components/fields/PushButtonField.svelte
<script lang="ts">
  import { PDF_FORM_FIELD_FLAG } from '@embedpdf/models';
  import type { PushButtonFieldProps } from '../../../shared/components/types';

  let { annotation, isEditable }: PushButtonFieldProps = $props();

  const field = $derived(annotation.field);
  const flag = $derived(field.flag);
  const name = $derived(field.alternateName || field.name);
  const isDisabled = $derived(!isEditable || !!(flag & PDF_FORM_FIELD_FLAG.READONLY));
</script>

<button
  disabled={isDisabled}
  aria-label={name}
  style:position="absolute"
  style:top="0"
  style:left="0"
  style:width="100%"
  style:height="100%"
  style:padding="0"
  style:margin="0"
>
  {name}
</button>
