// packages/plugin-form/src/vue/components/fields/radio-button-field.vue
<script setup lang="ts">
import { computed } from 'vue';
import { PDF_FORM_FIELD_FLAG, isWidgetChecked, type PdfWidgetAnnoOption } from '@embedpdf/models';
import type { RadioButtonFieldProps } from '../../../shared/components/types';
import { buttonStyle } from './style';

const props = defineProps<RadioButtonFieldProps>();

const field = computed(() => props.annotation.field);
const flag = computed(() => field.value.flag);
const name = computed(() => field.value.alternateName || field.value.name);
const checked = computed(() => isWidgetChecked(props.annotation));
const defaultValue = computed(() => {
  const option = field.value.options.find((o: PdfWidgetAnnoOption) => o.isSelected);
  return option?.label || field.value.value;
});
const isDisabled = computed(
  () => !props.isEditable || !!(flag.value & PDF_FORM_FIELD_FLAG.READONLY),
);
const isRequired = computed(() => !!(flag.value & PDF_FORM_FIELD_FLAG.REQUIRED));

function handleChange(evt: Event) {
  const wantChecked = (evt.target as HTMLInputElement).checked;
  if (wantChecked && props.annotation.exportValue) {
    props.onChangeField?.({ ...field.value, value: props.annotation.exportValue });
  }
}
</script>

<template>
  <input
    type="radio"
    :required="isRequired"
    :disabled="isDisabled"
    :name="name"
    :aria-label="name"
    :value="defaultValue"
    :checked="checked"
    @change="handleChange"
    :style="buttonStyle"
  />
</template>

// packages/plugin-form/src/svelte/components/fields/RadioButtonField.svelte
<script lang="ts">
  import { PDF_FORM_FIELD_FLAG, isWidgetChecked } from '@embedpdf/models';
  import type { PdfWidgetAnnoOption } from '@embedpdf/models';
  import type { RadioButtonFieldProps } from '../../../shared/components/types';

  let { annotation, isEditable, onChangeField }: RadioButtonFieldProps = $props();

  const field = $derived(annotation.field);
  const flag = $derived(field.flag);
  const name = $derived(field.alternateName || field.name);
  const checked = $derived(isWidgetChecked(annotation));
  const defaultValue = $derived.by(() => {
    const option = field.options.find((o: PdfWidgetAnnoOption) => o.isSelected);
    return option?.label || field.value;
  });
  const isDisabled = $derived(!isEditable || !!(flag & PDF_FORM_FIELD_FLAG.READONLY));
  const isRequired = $derived(!!(flag & PDF_FORM_FIELD_FLAG.REQUIRED));

  function handleChange(evt: Event) {
    const wantChecked = (evt.target as HTMLInputElement).checked;
    if (wantChecked && annotation.exportValue) {
      onChangeField?.({ ...field, value: annotation.exportValue });
    }
  }
</script>

<input
  type="radio"
  required={isRequired}
  disabled={isDisabled}
  {name}
  aria-label={name}
  value={defaultValue}
  {checked}
  onchange={handleChange}
  style:position="absolute"
  style:top="0"
  style:left="0"
  style:width="100%"
  style:height="100%"
  style:padding="0"
  style:margin="0"
/>
