// examples/vue-tailwind/src/examples/pan-example.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import {
  GlobalPointerProvider,
  InteractionManagerPluginPackage,
} from '@embedpdf/plugin-interaction-manager/vue';
import { usePan, PanPluginPackage } from '@embedpdf/plugin-pan/vue';

const { engine, isLoading } = usePdfiumEngine();

const plugins = [
  createPluginRegistration(LoaderPluginPackage, {
    loadingOptions: {
      type: 'url',
      pdfFile: { id: 'example-pdf', url: 'https://snippet.embedpdf.com/ebook.pdf' },
    },
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(InteractionManagerPluginPackage),
  createPluginRegistration(PanPluginPackage, { defaultMode: 'mobile' }),
];

const { provides: pan, isPanning } = usePan();
</script>

<template>
  <div style="height: 500px" class="select-none">
    <div v-if="isLoading || !engine">Loading PDF Engine...</div>
    <EmbedPDF v-else :engine="engine" :plugins="plugins">
      <div class="flex h-full flex-col">
        <div
          v-if="pan"
          class="mb-4 mt-4 flex items-center gap-3 rounded-lg border border-gray-200 bg-white p-3 shadow-sm"
        >
          <button
            @click="pan.togglePan"
            :class="[
              'flex h-8 w-8 items-center justify-center rounded-md border transition-colors duration-150',
              isPanning
                ? 'border-blue-500 bg-blue-100 text-blue-700'
                : 'border-gray-300 bg-white text-gray-700 hover:border-gray-400 hover:bg-gray-50',
            ]"
            title="Toggle Pan Tool"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M8 13v-7.5a1.5 1.5 0 0 1 3 0v6.5" />
              <path d="M11 5.5v-2a1.5 1.5 0 1 1 3 0v8.5" />
              <path d="M14 5.5a1.5 1.5 0 0 1 3 0v6.5" />
              <path
                d="M17 7.5a1.5 1.5 0 0 1 3 0v8.5a6 6 0 0 1 -6 6h-2h.208a6 6 0 0 1 -5.012 -2.7a69.74 69.74 0 0 1 -.196 -.3c-.312 -.479 -1.407 -2.388 -3.286 -5.728a1.5 1.5 0 0 1 .536 -2.022a1.867 1.867 0 0 1 2.28 .28l1.47 1.47"
              />
            </svg>
          </button>
        </div>
        <div class="relative flex w-full flex-1 overflow-hidden">
          <GlobalPointerProvider>
            <Viewport class="flex-grow bg-gray-100">
              <Scroller>
                <template #default="{ page }">
                  <div
                    :style="{
                      width: page.width + 'px',
                      height: page.height + 'px',
                      position: 'relative',
                    }"
                  >
                    <RenderLayer
                      :page-index="page.pageIndex"
                      :scale="page.scale"
                      class="pointer-events-none"
                    />
                  </div>
                </template>
              </Scroller>
            </Viewport>
          </GlobalPointerProvider>
        </div>
      </div>
    </EmbedPDF>
  </div>
</template>

// website/src/content/docs/snippet/code-examples/pan-example.tsx
'use client'
import { PDFViewer, PDFViewerRef, PanPlugin } from '@embedpdf/react-pdf-viewer'
import { useEffect, useRef, useState } from 'react'
import { Hand, MousePointer2 } from 'lucide-react'

interface PanExampleProps {
  themePreference?: 'light' | 'dark'
}

export default function PanExample({
  themePreference = 'light',
}: PanExampleProps) {
  const viewerRef = useRef<PDFViewerRef>(null)
  const [isPanMode, setIsPanMode] = useState(false)

  useEffect(() => {
    viewerRef.current?.container?.setTheme({ preference: themePreference })
  }, [themePreference])

  useEffect(() => {
    const viewer = viewerRef.current
    if (!viewer) return

    let cleanup: (() => void) | undefined

    const setupListener = async () => {
      const registry = await viewer.registry
      const panPlugin = registry?.getPlugin<PanPlugin>('pan')?.provides()
      const docPan = panPlugin?.forDocument('pan-doc')

      if (docPan) {
        setIsPanMode(docPan.isPanMode())
        cleanup = docPan.onPanModeChange((isActive) => {
          setIsPanMode(isActive)
        })
      }
    }

    setupListener()

    return () => cleanup?.()
  }, [])

  const togglePanMode = async () => {
    const registry = await viewerRef.current?.registry
    const panPlugin = registry?.getPlugin<PanPlugin>('pan')?.provides()
    panPlugin?.forDocument('pan-doc').togglePan()
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 p-2 dark:border-gray-700 dark:bg-gray-800">
        <span className="px-2 text-sm font-medium text-gray-600 dark:text-gray-300">
          Interaction Mode:
        </span>
        <button
          onClick={togglePanMode}
          className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors ${
            !isPanMode
              ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
              : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'
          }`}
        >
          <MousePointer2 size={16} />
          Select Text
        </button>
        <button
          onClick={togglePanMode}
          className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors ${
            isPanMode
              ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
              : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'
          }`}
        >
          <Hand size={16} />
          Pan (Hand Tool)
        </button>
      </div>

      <div className="h-[500px] w-full overflow-hidden rounded-xl border border-gray-300 shadow-lg dark:border-gray-600">
        <PDFViewer
          ref={viewerRef}
          config={{
            theme: { preference: themePreference },
            pan: {
              defaultMode: 'mobile',
            },
            documentManager: {
              initialDocuments: [
                {
                  url: 'https://snippet.embedpdf.com/ebook.pdf',
                  documentId: 'pan-doc',
                },
              ],
            },
          }}
          style={{ width: '100%', height: '100%' }}
        />
      </div>
    </div>
  )
}
