// packages/plugin-rotate/src/svelte/components/Rotate.svelte
<script lang="ts">
  import type { Size } from '@embedpdf/models';
  import type { Snippet } from 'svelte';
  import { useRotatePlugin } from '../hooks';

  interface RotateProps {
    pageSize: Size;
    children?: Snippet;
  }

  let { pageSize, children }: RotateProps = $props();

  const { plugin: rotate } = useRotatePlugin();

  const transformMatrix = $derived(
    rotate
      ? rotate.getMatrixAsString({
          w: pageSize.width,
          h: pageSize.height,
        })
      : 'matrix(1, 0, 0, 1, 0, 0)',
  );
</script>

<div style:position="absolute" style:transform-origin="0 0" style:transform={transformMatrix}>
  {@render children?.()}
</div>

// packages/plugin-rotate/src/react/components/rotate.tsx
import { ReactNode } from 'react';
import { Size } from '@embedpdf/models';

import { useRotateCapability } from '../hooks';

type RotateProps = React.HTMLAttributes<HTMLDivElement> & {
  children: ReactNode;
  pageSize: Size;
};

export function Rotate({ children, pageSize, ...props }: RotateProps) {
  const { provides: rotate } = useRotateCapability();
  const matrix =
    (rotate?.getMatrix({
      w: pageSize.width,
      h: pageSize.height,
    }) as string) || 'matrix(1, 0, 0, 1, 0, 0)';

  return (
    <div
      {...props}
      style={{
        position: 'absolute',
        transformOrigin: '0 0',
        transform: matrix,
      }}
    >
      {children}
    </div>
  );
}
