// packages/plugin-search/src/svelte/components/SearchLayer.svelte
<script lang="ts">
  import type { SearchResultState } from '@embedpdf/plugin-search';
  import { useSearchCapability } from '../hooks';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends HTMLAttributes<HTMLDivElement> {
    pageIndex: number;
    scale: number;
    highlightColor?: string;
    activeHighlightColor?: string;
  }

  const {
    pageIndex,
    scale,
    highlightColor = '#FFFF00',
    activeHighlightColor = '#FFBF00',
    ...divProps
  }: Props = $props();

  const { provides: searchProvides } = useSearchCapability();
  let searchResultState = $state<SearchResultState | null>(null);

  $effect(() => {
    if (!searchProvides) return;
    return searchProvides.onSearchResultStateChange((state) => {
      searchResultState = state;
    });
  });

  const pageResults = $derived(
    searchResultState
      ? searchResultState.results
          .map((result, originalIndex) => ({ result, originalIndex }))
          .filter(({ result }) => result.pageIndex === pageIndex)
      : [],
  );
</script>

{#if searchResultState}
  <div {...divProps}>
    {#each pageResults as { result, originalIndex }}
      {#each result.rects as rect}
        <div
          style:position="absolute"
          style:top="{rect.origin.y * scale}px"
          style:left="{rect.origin.x * scale}px"
          style:width="{rect.size.width * scale}px"
          style:height="{rect.size.height * scale}px"
          style:background-color={originalIndex === searchResultState.activeResultIndex
            ? activeHighlightColor
            : highlightColor}
          style:mix-blend-mode="multiply"
          style:transform="scale(1.02)"
          style:transform-origin="center"
          style:transition="opacity .3s ease-in-out"
          style:opacity="1"
        ></div>
      {/each}
    {/each}
  </div>
{/if}

// packages/plugin-search/src/react/components/search-layer.tsx
import { useEffect, useState } from 'react';
import { SearchResultState } from '@embedpdf/plugin-search';

import { useSearchCapability } from '../hooks';

type SearchLayoutProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'style'> & {
  pageIndex: number;
  scale: number;
  highlightColor?: string;
  activeHighlightColor?: string;
  style?: React.CSSProperties;
};

export function SearchLayer({
  pageIndex,
  scale,
  style,
  highlightColor = '#FFFF00',
  activeHighlightColor = '#FFBF00',
  ...props
}: SearchLayoutProps) {
  const { provides: searchProvides } = useSearchCapability();
  const [searchResultState, setSearchResultState] = useState<SearchResultState | null>(null);

  useEffect(() => {
    return searchProvides?.onSearchResultStateChange((state) => {
      setSearchResultState(state);
    });
  }, [searchProvides]);

  if (!searchResultState) {
    return null;
  }

  // Filter results for current page while preserving original indices
  const pageResults = searchResultState.results
    .map((result, originalIndex) => ({ result, originalIndex }))
    .filter(({ result }) => result.pageIndex === pageIndex);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      {pageResults.map(({ result, originalIndex }) =>
        result.rects.map((rect) => (
          <div
            style={{
              position: 'absolute',
              top: rect.origin.y * scale,
              left: rect.origin.x * scale,
              width: rect.size.width * scale,
              height: rect.size.height * scale,
              backgroundColor:
                originalIndex === searchResultState.activeResultIndex
                  ? activeHighlightColor
                  : highlightColor,
              mixBlendMode: 'multiply',
              transform: 'scale(1.02)',
              transformOrigin: 'center',
              transition: 'opacity .3s ease-in-out',
              opacity: 1,
            }}
          ></div>
        )),
      )}
    </div>
  );
}
