// examples/svelte-tailwind/src/lib/ui/CommandButtonItem.svelte
<script lang="ts">
  import { type SelectionMenuItem, getUIItemProps } from '@embedpdf/plugin-ui/svelte';
  import { useCommand } from '@embedpdf/plugin-commands/svelte';
  import CommandButton from '../components/CommandButton.svelte';

  interface Props {
    item: SelectionMenuItem & { type: 'command-button' };
    documentId: string;
  }

  let { item, documentId }: Props = $props();

  const command = useCommand(
    () => item.commandId,
    () => documentId,
  );
</script>

{#if command.current?.visible}
  <div {...getUIItemProps(item)}>
    <CommandButton commandId={item.commandId} {documentId} variant={item.variant} />
  </div>
{/if}

// examples/vue-tailwind/src/ui/CommandButtonItem.vue
<template>
  <div v-if="command?.visible" v-bind="getUIItemProps(item)">
    <CommandButton :commandId="item.commandId" :documentId="documentId" :variant="item.variant" />
  </div>
</template>

<script setup lang="ts">
import type { SelectionMenuItem } from '@embedpdf/plugin-ui/vue';
import { getUIItemProps } from '@embedpdf/plugin-ui/vue';
import { useCommand } from '@embedpdf/plugin-commands/vue';
import CommandButton from '../components/CommandButton.vue';

const props = defineProps<{
  item: SelectionMenuItem & { type: 'command-button' };
  documentId: string;
}>();

const command = useCommand(
  () => props.item.commandId,
  () => props.documentId,
);
</script>
