// examples/react-tailwind/src/application.tsx
import { useRef } from 'react';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/react';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/react';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/react';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan/react';
import { ViewportPluginPackage, Viewport } from '@embedpdf/plugin-viewport/react';
import { ScrollPluginPackage, ScrollStrategy, Scroller } from '@embedpdf/plugin-scroll/react';
import { TilingPluginPackage, TilingLayer } from '@embedpdf/plugin-tiling/react';
import { RotatePluginPackage, Rotate } from '@embedpdf/plugin-rotate/react';
import { RenderPluginPackage, RenderLayer } from '@embedpdf/plugin-render/react';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/react';
import { SelectionPluginPackage, SelectionLayer } from '@embedpdf/plugin-selection/react';

export default function DocumentViewer() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { engine, isLoading, error } = usePdfiumEngine();

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  if (isLoading || !engine) {
    return <div>Loading...</div>;
  }

  return (
    <div className="flex h-screen flex-1 flex-col overflow-hidden" ref={containerRef}>
      <div className="flex flex-1 overflow-hidden">
        <EmbedPDF
          engine={engine}
          plugins={[
            createPluginRegistration(LoaderPluginPackage, {
              loadingOptions: {
                type: 'url',
                pdfFile: {
                  id: '1',
                  url: 'https://snippet.embedpdf.com/ebook.pdf',
                },
                options: {
                  mode: 'full-fetch',
                },
              },
            }),
            createPluginRegistration(ViewportPluginPackage, {
              viewportGap: 10,
            }),
            createPluginRegistration(ScrollPluginPackage, {
              strategy: ScrollStrategy.Vertical,
            }),
            createPluginRegistration(RenderPluginPackage),
            createPluginRegistration(TilingPluginPackage, {
              tileSize: 768,
              overlapPx: 2.5,
              extraRings: 0,
            }),
            createPluginRegistration(ZoomPluginPackage, {
              defaultZoomLevel: ZoomMode.FitPage,
            }),
            createPluginRegistration(RotatePluginPackage),
            createPluginRegistration(SpreadPluginPackage),
            createPluginRegistration(FullscreenPluginPackage),
            createPluginRegistration(ExportPluginPackage),
            createPluginRegistration(InteractionManagerPluginPackage),
            createPluginRegistration(SelectionPluginPackage),
            createPluginRegistration(PanPluginPackage),
            createPluginRegistration(ThumbnailPluginPackage),
          ]}
        >
          {({ pluginsReady }) => (
            <GlobalPointerProvider>
              <Viewport className="h-full w-full flex-1 select-none overflow-auto bg-gray-100">
                {pluginsReady ? (
                  <Scroller
                    renderPage={({
                      pageIndex,
                      scale,
                      width,
                      height,
                      document,
                      rotation,
                      rotatedWidth,
                      rotatedHeight,
                    }) => (
                      <Rotate key={document?.id} pageSize={{ width, height }}>
                        <PagePointerProvider
                          rotation={rotation}
                          scale={scale}
                          pageWidth={rotatedWidth}
                          pageHeight={rotatedHeight}
                          pageIndex={pageIndex}
                          style={{
                            width,
                            height,
                          }}
                        >
                          <RenderLayer pageIndex={pageIndex} className="pointer-events-none" />
                          <TilingLayer
                            pageIndex={pageIndex}
                            scale={scale}
                            className="pointer-events-none"
                          />
                          <SelectionLayer pageIndex={pageIndex} scale={scale} />
                        </PagePointerProvider>
                      </Rotate>
                    )}
                  />
                ) : (
                  <div>Loading plugins...</div>
                )}
              </Viewport>
            </GlobalPointerProvider>
          )}
        </EmbedPDF>
      </div>
    </div>
  );
}

// examples/vue-tailwind/src/application.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/vue';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/vue';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/vue';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate/vue';
import { Rotate } from '@embedpdf/plugin-rotate/vue';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/vue';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/vue';

const { engine, isLoading: engineLoading, error: engineError } = usePdfiumEngine();
</script>

<template>
  <div class="flex h-screen flex-1 flex-col overflow-hidden">
    <div v-if="engineLoading" class="flex h-full items-center justify-center text-gray-500">
      Loading PDF engine...
    </div>
    <div v-else-if="engineError" class="flex h-full items-center justify-center text-red-600">
      Error: {{ engineError.message }}
    </div>
    <div v-else-if="engine" class="flex flex-1 overflow-hidden">
      <EmbedPDF
        :engine="engine"
        :plugins="[
          createPluginRegistration(LoaderPluginPackage, {
            loadingOptions: {
              type: 'url',
              pdfFile: {
                id: 'sample-pdf',
                name: 'embedpdf-ebook.pdf',
                url: 'https://snippet.embedpdf.com/ebook.pdf',
              },
            },
          }),
          createPluginRegistration(ViewportPluginPackage, {
            viewportGap: 10,
          }),
          createPluginRegistration(ScrollPluginPackage, {
            strategy: ScrollStrategy.Vertical,
            pageGap: 10,
          }),
          createPluginRegistration(RenderPluginPackage),
          createPluginRegistration(TilingPluginPackage, {
            tileSize: 768,
            overlapPx: 2.5,
            extraRings: 0,
          }),
          createPluginRegistration(InteractionManagerPluginPackage),
          createPluginRegistration(SelectionPluginPackage),
          createPluginRegistration(RotatePluginPackage),
          createPluginRegistration(FullscreenPluginPackage),
          createPluginRegistration(ZoomPluginPackage, {
            defaultZoomLevel: ZoomMode.FitPage,
          }),
        ]"
      >
        <template #default="{ pluginsReady }">
          <GlobalPointerProvider>
            <Viewport class="h-full w-full select-none overflow-auto">
              <Scroller v-if="pluginsReady">
                <template #default="{ page }">
                  <Rotate :page-size="{ width: page.width, height: page.height }">
                    <PagePointerProvider
                      :page-index="page.pageIndex"
                      :page-width="page.width"
                      :page-height="page.height"
                      :rotation="page.rotation"
                      :scale="page.scale"
                      class="absolute"
                      :style="{
                        width: page.width + 'px',
                        height: page.height + 'px',
                      }"
                    >
                      <RenderLayer :page-index="page.pageIndex" class="pointer-events-none" />
                      <TilingLayer
                        :page-index="page.pageIndex"
                        :scale="page.scale"
                        class="pointer-events-none"
                      />
                      <SelectionLayer :page-index="page.pageIndex" :scale="page.scale" />
                    </PagePointerProvider>
                  </Rotate>
                </template>
              </Scroller>
              <div v-else class="flex h-full items-center justify-center">Loading plugins...</div>
            </Viewport>
          </GlobalPointerProvider>
        </template>
      </EmbedPDF>
    </div>
    <div v-else class="flex h-full items-center justify-center text-gray-500">Engine not ready</div>
  </div>
</template>
