// website/src/content/docs/snippet/code-examples/spread-example.tsx
'use client'
import {
  PDFViewer,
  PDFViewerRef,
  SpreadPlugin,
  SpreadMode,
} from '@embedpdf/react-pdf-viewer'
import { useEffect, useRef, useState } from 'react'
import { Book, BookOpen, File } from 'lucide-react'

interface SpreadExampleProps {
  themePreference?: 'light' | 'dark'
}

export default function SpreadExample({
  themePreference = 'light',
}: SpreadExampleProps) {
  const viewerRef = useRef<PDFViewerRef>(null)
  const [currentMode, setCurrentMode] = useState<SpreadMode>(SpreadMode.None)

  useEffect(() => {
    viewerRef.current?.container?.setTheme({ preference: themePreference })
  }, [themePreference])

  const setSpreadMode = async (mode: SpreadMode) => {
    const registry = await viewerRef.current?.registry
    const spreadPlugin = registry?.getPlugin<SpreadPlugin>('spread')?.provides()
    const docSpread = spreadPlugin?.forDocument('spread-doc')
    docSpread?.setSpreadMode(mode)
    setCurrentMode(mode)
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-2 rounded-lg border border-gray-200 bg-gray-50 p-2 dark:border-gray-700 dark:bg-gray-800">
        <span className="px-2 text-sm font-medium text-gray-600 dark:text-gray-300">
          Layout Mode:
        </span>
        <div className="flex gap-1">
          <button
            onClick={() => setSpreadMode(SpreadMode.None)}
            className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors ${
              currentMode === SpreadMode.None
                ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
                : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'
            }`}
          >
            <File size={16} />
            Single Page
          </button>
          <button
            onClick={() => setSpreadMode(SpreadMode.Odd)}
            className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors ${
              currentMode === SpreadMode.Odd
                ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
                : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'
            }`}
          >
            <BookOpen size={16} />
            Two-Page (Odd)
          </button>
          <button
            onClick={() => setSpreadMode(SpreadMode.Even)}
            className={`flex items-center gap-2 rounded px-3 py-1.5 text-sm font-medium transition-colors ${
              currentMode === SpreadMode.Even
                ? 'bg-white text-blue-600 shadow-sm dark:bg-gray-700 dark:text-blue-400'
                : 'text-gray-600 hover:bg-gray-200 dark:text-gray-400 dark:hover:bg-gray-700'
            }`}
          >
            <Book size={16} />
            Two-Page (Even)
          </button>
        </div>
      </div>

      <div className="h-[500px] w-full overflow-hidden rounded-xl border border-gray-300 shadow-lg dark:border-gray-600">
        <PDFViewer
          ref={viewerRef}
          config={{
            theme: { preference: themePreference },
            spread: {
              defaultSpreadMode: SpreadMode.None,
            },
            documentManager: {
              initialDocuments: [
                {
                  url: 'https://snippet.embedpdf.com/ebook.pdf',
                  documentId: 'spread-doc',
                },
              ],
            },
          }}
          style={{ width: '100%', height: '100%' }}
        />
      </div>
    </div>
  )
}

// examples/vue-tailwind/src/examples/spread-example.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { useSpread, SpreadPluginPackage, SpreadMode } from '@embedpdf/plugin-spread/vue';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/vue';

const { engine, isLoading } = usePdfiumEngine();

const plugins = [
  createPluginRegistration(LoaderPluginPackage, {
    loadingOptions: {
      type: 'url',
      pdfFile: { id: 'example-pdf', url: 'https://snippet.embedpdf.com/ebook.pdf' },
    },
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(ZoomPluginPackage, { defaultZoomLevel: ZoomMode.FitPage }),
  createPluginRegistration(SpreadPluginPackage, { defaultSpreadMode: SpreadMode.None }),
];

const { provides: spread, spreadMode } = useSpread();

const modes = [
  { label: 'Single Page', value: SpreadMode.None },
  { label: 'Two-Page (Odd)', value: SpreadMode.Odd },
  { label: 'Two-Page (Even)', value: SpreadMode.Even },
];
</script>

<template>
  <div style="height: 500px">
    <div v-if="isLoading || !engine">Loading PDF Engine...</div>
    <EmbedPDF v-else :engine="engine" :plugins="plugins">
      <div class="flex h-full flex-col">
        <div
          v-if="spread"
          class="mb-4 mt-4 flex flex-wrap items-center gap-3 rounded-lg border border-gray-200 bg-white p-3 shadow-sm"
        >
          <span class="text-xs font-medium uppercase tracking-wide text-gray-600">Page Layout</span>
          <div class="h-6 w-px bg-gray-200"></div>
          <div class="flex items-center gap-2">
            <button
              v-for="mode in modes"
              :key="mode.value"
              @click="spread.setSpreadMode(mode.value)"
              :class="[
                'rounded-md px-3 py-1 text-sm font-medium transition-colors duration-150',
                spreadMode === mode.value
                  ? 'bg-blue-500 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200',
              ]"
            >
              {{ mode.label }}
            </button>
          </div>
        </div>
        <div class="flex-grow" style="position: relative">
          <Viewport
            style="
              background-color: #f1f3f5;
              position: absolute;
              top: 0;
              left: 0;
              right: 0;
              bottom: 0;
            "
          >
            <Scroller>
              <template #default="{ page }">
                <div
                  :style="{
                    width: page.width + 'px',
                    height: page.height + 'px',
                    position: 'relative',
                  }"
                >
                  <RenderLayer :page-index="page.pageIndex" :scale="page.scale" />
                </div>
              </template>
            </Scroller>
          </Viewport>
        </div>
      </div>
    </EmbedPDF>
  </div>
</template>
