// packages/plugin-annotation/src/svelte/components/renderers/CircleRenderer.svelte
<script lang="ts">
  import type { PdfCircleAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Circle from '../annotations/Circle.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfCircleAnnoObject> = $props();
</script>

<Circle {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/circle-renderer.vue
<template>
  <CircleVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfCircleAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import CircleVue from '../annotations/circle.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfCircleAnnoObject>>();
</script>
