// packages/plugin-annotation/src/svelte/components/renderers/HighlightRenderer.svelte
<script lang="ts">
  import type { PdfHighlightAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Highlight from '../text-markup/Highlight.svelte';

  let {
    currentObject,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfHighlightAnnoObject> = $props();
</script>

<Highlight {...currentObject} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/highlight-renderer.vue
<template>
  <HighlightVue
    v-bind="currentObject"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfHighlightAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import HighlightVue from '../text-markup/highlight.vue';

const { currentObject, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfHighlightAnnoObject>>();
</script>
