// packages/plugin-annotation/src/svelte/components/renderers/InkRenderer.svelte
<script lang="ts">
  import type { PdfInkAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Ink from '../annotations/Ink.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfInkAnnoObject> = $props();
</script>

<Ink {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/ink-renderer.vue
<template>
  <InkVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfInkAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import InkVue from '../annotations/ink.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfInkAnnoObject>>();
</script>
