// packages/plugin-annotation/src/svelte/components/renderers/LineRenderer.svelte
<script lang="ts">
  import type { PdfLineAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Line from '../annotations/Line.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfLineAnnoObject> = $props();
</script>

<Line {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/line-renderer.vue
<template>
  <LineVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfLineAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import LineVue from '../annotations/line.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfLineAnnoObject>>();
</script>
