// packages/plugin-annotation/src/svelte/components/renderers/LinkRenderer.svelte
<script lang="ts">
  import type { PdfLinkAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Link from '../annotations/Link.svelte';

  let { currentObject, isSelected, scale, onClick }: AnnotationRendererProps<PdfLinkAnnoObject> =
    $props();
</script>

<Link {...currentObject} {isSelected} {scale} {onClick} hasIRT={!!currentObject.inReplyToId} />

// packages/plugin-annotation/src/vue/components/renderers/link-renderer.vue
<template>
  <LinkVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :hasIRT="!!currentObject.inReplyToId"
  />
</template>

<script setup lang="ts">
import { PdfLinkAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import LinkVue from '../annotations/link.vue';

const { currentObject, isSelected, scale, onClick } =
  defineProps<AnnotationRendererProps<PdfLinkAnnoObject>>();
</script>
