// packages/plugin-annotation/src/svelte/components/renderers/SquareRenderer.svelte
<script lang="ts">
  import type { PdfSquareAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Square from '../annotations/Square.svelte';

  let {
    currentObject,
    isSelected,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfSquareAnnoObject> = $props();
</script>

<Square {...currentObject} {isSelected} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/square-renderer.vue
<template>
  <SquareVue
    v-bind="currentObject"
    :isSelected="isSelected"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfSquareAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import SquareVue from '../annotations/square.vue';

const { currentObject, isSelected, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfSquareAnnoObject>>();
</script>
