// packages/plugin-annotation/src/svelte/components/renderers/SquigglyRenderer.svelte
<script lang="ts">
  import type { PdfSquigglyAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Squiggly from '../text-markup/Squiggly.svelte';

  let {
    currentObject,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfSquigglyAnnoObject> = $props();
</script>

<Squiggly {...currentObject} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/squiggly-renderer.vue
<template>
  <SquigglyVue
    v-bind="currentObject"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfSquigglyAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import SquigglyVue from '../text-markup/squiggly.vue';

const { currentObject, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfSquigglyAnnoObject>>();
</script>
