// packages/plugin-annotation/src/svelte/components/renderers/StampRenderer.svelte
<script lang="ts">
  import type { PdfStampAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Stamp from '../annotations/Stamp.svelte';

  let {
    annotation,
    isSelected,
    documentId,
    pageIndex,
    scale,
    onClick,
  }: AnnotationRendererProps<PdfStampAnnoObject> = $props();
</script>

<Stamp {documentId} {isSelected} {annotation} {pageIndex} {scale} {onClick} />

// packages/plugin-annotation/src/vue/components/renderers/stamp-renderer.vue
<template>
  <StampVue
    :isSelected="isSelected"
    :annotation="annotation"
    :documentId="documentId"
    :pageIndex="pageIndex"
    :scale="scale"
    :onClick="onClick"
  />
</template>

<script setup lang="ts">
import { PdfStampAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import StampVue from '../annotations/stamp.vue';

const { annotation, isSelected, documentId, pageIndex, scale, onClick } =
  defineProps<AnnotationRendererProps<PdfStampAnnoObject>>();
</script>
