// packages/plugin-annotation/src/svelte/components/renderers/StrikeoutRenderer.svelte
<script lang="ts">
  import type { PdfStrikeOutAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Strikeout from '../text-markup/Strikeout.svelte';

  let {
    currentObject,
    scale,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfStrikeOutAnnoObject> = $props();
</script>

<Strikeout {...currentObject} {scale} {onClick} {appearanceActive} />

// packages/plugin-annotation/src/vue/components/renderers/strikeout-renderer.vue
<template>
  <StrikeoutVue
    v-bind="currentObject"
    :scale="scale"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfStrikeOutAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import StrikeoutVue from '../text-markup/strikeout.vue';

const { currentObject, scale, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfStrikeOutAnnoObject>>();
</script>
