// packages/plugin-annotation/src/svelte/components/renderers/TextRenderer.svelte
<script lang="ts">
  import type { PdfTextAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '../../context/types';
  import Text from '../annotations/Text.svelte';

  let {
    currentObject,
    isSelected,
    onClick,
    appearanceActive,
  }: AnnotationRendererProps<PdfTextAnnoObject> = $props();
</script>

<Text
  {isSelected}
  color={currentObject.strokeColor ?? currentObject.color}
  opacity={currentObject.opacity}
  {onClick}
  {appearanceActive}
/>

// packages/plugin-annotation/src/vue/components/renderers/text-renderer.vue
<template>
  <TextVue
    :isSelected="isSelected"
    :color="currentObject.strokeColor ?? currentObject.color"
    :opacity="currentObject.opacity"
    :onClick="onClick"
    :appearanceActive="appearanceActive"
  />
</template>

<script setup lang="ts">
import { PdfTextAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import TextVue from '../annotations/text.vue';

const { currentObject, isSelected, onClick, appearanceActive } =
  defineProps<AnnotationRendererProps<PdfTextAnnoObject>>();
</script>
