// examples/vue-tailwind/src/examples/headless/layout-analysis-example.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import {
  DocumentManagerPluginPackage,
  DocumentContent,
} from '@embedpdf/plugin-document-manager/vue';
import { ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { ScrollPluginPackage } from '@embedpdf/plugin-scroll/vue';
import { RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/vue';
import { createAiRuntime } from '@embedpdf/ai/web';
import { AiManagerPluginPackage } from '@embedpdf/plugin-ai-manager/vue';
import { LayoutAnalysisPluginPackage } from '@embedpdf/plugin-layout-analysis/vue';
import LayoutAnalysisExampleContent from './layout-analysis-example-content.vue';

const { engine, isLoading } = usePdfiumEngine();

const aiRuntime = createAiRuntime({
  backend: 'auto',
  cache: true,
});

const plugins = [
  createPluginRegistration(DocumentManagerPluginPackage, {
    initialDocuments: [{ url: 'https://arxiv.org/pdf/1706.03762' }],
  }),
  createPluginRegistration(ViewportPluginPackage),
  createPluginRegistration(ScrollPluginPackage),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(AiManagerPluginPackage, {
    runtime: aiRuntime,
  }),
  createPluginRegistration(LayoutAnalysisPluginPackage, {
    layoutThreshold: 0.35,
    tableStructureThreshold: 0.8,
    tableStructure: false,
  }),
];
</script>

<template>
  <div v-if="isLoading || !engine" class="flex h-[400px] items-center justify-center">
    <span class="text-sm text-gray-500 dark:text-gray-400">Loading PDF Engine...</span>
  </div>
  <EmbedPDF v-else :engine="engine" :plugins="plugins" v-slot="{ activeDocumentId }">
    <DocumentContent v-if="activeDocumentId" :document-id="activeDocumentId" v-slot="{ isLoaded }">
      <LayoutAnalysisExampleContent v-if="isLoaded" :document-id="activeDocumentId" />
    </DocumentContent>
  </EmbedPDF>
</template>

// examples/svelte-tailwind/src/examples/headless/layout-analysis-example.svelte
<script lang="ts">
  import { usePdfiumEngine } from '@embedpdf/engines/svelte';
  import { EmbedPDF } from '@embedpdf/core/svelte';
  import { createPluginRegistration } from '@embedpdf/core';
  import {
    DocumentManagerPluginPackage,
    DocumentContent,
  } from '@embedpdf/plugin-document-manager/svelte';
  import { ViewportPluginPackage } from '@embedpdf/plugin-viewport/svelte';
  import { ScrollPluginPackage } from '@embedpdf/plugin-scroll/svelte';
  import { RenderPluginPackage } from '@embedpdf/plugin-render/svelte';
  import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/svelte';
  import { createAiRuntime } from '@embedpdf/ai/web';
  import { AiManagerPluginPackage } from '@embedpdf/plugin-ai-manager/svelte';
  import { LayoutAnalysisPluginPackage } from '@embedpdf/plugin-layout-analysis/svelte';
  import LayoutAnalysisExampleContent from './layout-analysis-example-content.svelte';

  const pdfEngine = usePdfiumEngine();

  const aiRuntime = createAiRuntime({
    backend: 'auto',
    cache: true,
  });

  const plugins = [
    createPluginRegistration(DocumentManagerPluginPackage, {
      initialDocuments: [{ url: 'https://arxiv.org/pdf/1706.03762' }],
    }),
    createPluginRegistration(ViewportPluginPackage),
    createPluginRegistration(ScrollPluginPackage),
    createPluginRegistration(RenderPluginPackage),
    createPluginRegistration(ZoomPluginPackage, {
      defaultZoomLevel: ZoomMode.FitPage,
    }),
    createPluginRegistration(AiManagerPluginPackage, {
      runtime: aiRuntime,
    }),
    createPluginRegistration(LayoutAnalysisPluginPackage, {
      layoutThreshold: 0.35,
      tableStructureThreshold: 0.8,
      tableStructure: false,
    }),
  ];
</script>

{#if pdfEngine.isLoading || !pdfEngine.engine}
  <div class="flex h-[400px] items-center justify-center">
    <span class="text-sm text-gray-500 dark:text-gray-400">Loading PDF Engine...</span>
  </div>
{:else}
  <EmbedPDF engine={pdfEngine.engine} {plugins}>
    {#snippet children({ activeDocumentId })}
      {#if activeDocumentId}
        <DocumentContent documentId={activeDocumentId}>
          {#snippet children(documentContent)}
            {#if documentContent.isLoaded}
              <LayoutAnalysisExampleContent documentId={activeDocumentId} />
            {/if}
          {/snippet}
        </DocumentContent>
      {/if}
    {/snippet}
  </EmbedPDF>
{/if}
