// packages/utils/src/vue/components/counter-rotate-container.vue
<template>
  <slot :menu-wrapper-props="menuWrapperProps" :matrix="matrix" :rect="adjustedRect" />
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import type { Rect, Rotation } from '@embedpdf/models';
import { getCounterRotation } from '@embedpdf/utils';

interface CounterRotateProps {
  rect: Rect;
  rotation: Rotation;
}

const props = defineProps<CounterRotateProps>();

const { matrix, width, height } = getCounterRotation(props.rect, props.rotation);

const menuWrapperProps = computed(() => ({
  style: {
    position: 'absolute',
    left: `${props.rect.origin.x}px`,
    top: `${props.rect.origin.y}px`,
    transform: matrix,
    transformOrigin: '0 0',
    width: `${width}px`,
    height: `${height}px`,
    pointerEvents: 'none',
    zIndex: 3,
  } as CSSProperties,
  onPointerDown: (e: PointerEvent) => e.stopPropagation(),
  onTouchStart: (e: TouchEvent) => e.stopPropagation(),
}));

const adjustedRect = computed(() => ({
  origin: { x: props.rect.origin.x, y: props.rect.origin.y },
  size: { width, height },
}));
</script>

// packages/utils/src/shared/components/counter-rotate-container.tsx
import { Rect, Rotation } from '@embedpdf/models';
import { getCounterRotation } from '@embedpdf/utils';
import { ReactNode, CSSProperties, PointerEvent, Fragment, TouchEvent } from '@framework';

interface CounterRotateProps {
  rect: Rect;
  rotation: Rotation;
}

export interface MenuWrapperProps {
  style: CSSProperties;
  onPointerDown: (e: PointerEvent<HTMLDivElement>) => void;
  onTouchStart: (e: TouchEvent<HTMLDivElement>) => void;
}

interface CounterRotateComponentProps extends CounterRotateProps {
  children: (props: {
    matrix: string;
    rect: Rect;
    menuWrapperProps: MenuWrapperProps;
  }) => ReactNode;
}

export function CounterRotate({ children, ...props }: CounterRotateComponentProps) {
  const { rect, rotation } = props;
  const { matrix, width, height } = getCounterRotation(rect, rotation);

  const menuWrapperStyle: CSSProperties = {
    position: 'absolute',
    left: rect.origin.x,
    top: rect.origin.y,
    transform: matrix,
    transformOrigin: '0 0',
    width: width,
    height: height,
    pointerEvents: 'none',
    zIndex: 3,
  };

  const menuWrapperProps = {
    style: menuWrapperStyle,
    onPointerDown: (e: PointerEvent<HTMLDivElement>) => e.stopPropagation(),
    onTouchStart: (e: TouchEvent<HTMLDivElement>) => e.stopPropagation(),
  };

  return (
    <Fragment>
      {children({
        menuWrapperProps,
        matrix,
        rect: {
          origin: { x: rect.origin.x, y: rect.origin.y },
          size: { width: width, height: height },
        },
      })}
    </Fragment>
  );
}
