// packages/plugin-redaction/src/svelte/components/pending-redactions.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { Rect } from '@embedpdf/models';
  import { Rotation } from '@embedpdf/models';
  import { CounterRotate } from '@embedpdf/utils/svelte';
  import type { MenuWrapperProps, SelectionMenuPlacement } from '@embedpdf/utils/svelte';
  import type { RedactionItem } from '@embedpdf/plugin-redaction';
  import { useRedactionCapability } from '../hooks/use-redaction.svelte';
  import Highlight from './highlight.svelte';
  import type {
    RedactionSelectionContext,
    RedactionSelectionMenuRenderFn,
    RedactionSelectionMenuProps,
  } from '../types';

  interface Props {
    documentId: string;
    pageIndex: number;
    scale: number;
    rotation?: Rotation;
    bboxStroke?: string;
    selectionMenu?: RedactionSelectionMenuRenderFn;
    selectionMenuSnippet?: Snippet<[RedactionSelectionMenuProps]>;
  }

  let {
    documentId,
    pageIndex,
    scale,
    rotation = Rotation.Degree0,
    bboxStroke = 'rgba(0,0,0,0.8)',
    selectionMenu,
    selectionMenuSnippet,
  }: Props = $props();

  const redactionCapability = useRedactionCapability();

  let items = $state<RedactionItem[]>([]);
  let selectedId = $state<string | null>(null);

  $effect(() => {
    const redactionValue = redactionCapability.provides;
    if (!redactionValue) {
      items = [];
      selectedId = null;
      return;
    }

    const scoped = redactionValue.forDocument(documentId);
    const currentState = scoped.getState();
    // Only show legacy mode items (not annotation-based redactions)
    items = (currentState.pending[pageIndex] ?? []).filter((it) => it.source === 'legacy');
    selectedId = currentState.selected?.page === pageIndex ? currentState.selected.id : null;

    const off1 = scoped.onPendingChange((map) => {
      // Only show legacy mode items (not annotation-based redactions)
      items = (map[pageIndex] ?? []).filter((it) => it.source === 'legacy');
    });

    const off2 = scoped.onSelectedChange((sel) => {
      selectedId = sel?.page === pageIndex ? sel.id : null;
    });

    return () => {
      off1?.();
      off2?.();
    };
  });

  function select(e: MouseEvent, id: string) {
    e.stopPropagation();
    if (!redactionCapability.provides) return;
    redactionCapability.provides.forDocument(documentId).selectPending(pageIndex, id);
  }

  function shouldShowMenu(itemId: string): boolean {
    const isSelected = selectedId === itemId;
    return isSelected && (!!selectionMenu || !!selectionMenuSnippet);
  }

  function buildContext(item: RedactionItem): RedactionSelectionContext {
    return { type: 'redaction', item, pageIndex };
  }

  const menuPlacement: SelectionMenuPlacement = {
    suggestTop: false,
    spaceAbove: 0,
    spaceBelow: 0,
  };

  function buildMenuProps(
    item: RedactionItem,
    rect: Rect,
    menuWrapperProps: MenuWrapperProps,
  ): RedactionSelectionMenuProps {
    return {
      context: buildContext(item),
      selected: selectedId === item.id,
      rect,
      placement: menuPlacement,
      menuWrapperProps,
    };
  }
</script>

{#if items.length}
  <div style="position: absolute; inset: 0; pointer-events: none;">
    {#each items as item (item.id)}
      {#if item.kind === 'area'}
        <div
          style="
            position: absolute;
            left: {item.rect.origin.x * scale}px;
            top: {item.rect.origin.y * scale}px;
            width: {item.rect.size.width * scale}px;
            height: {item.rect.size.height * scale}px;
            background: transparent;
            outline: {selectedId === item.id ? `1px solid ${bboxStroke}` : 'none'};
            outline-offset: 2px;
            border: 1px solid red;
            pointer-events: auto;
            cursor: pointer;
          "
          onpointerdown={(e) => select(e, item.id)}
        ></div>

        {#if shouldShowMenu(item.id)}
          <CounterRotate
            rect={{
              origin: { x: item.rect.origin.x * scale, y: item.rect.origin.y * scale },
              size: { width: item.rect.size.width * scale, height: item.rect.size.height * scale },
            }}
            {rotation}
          >
            {#snippet children({ rect, menuWrapperProps })}
              {@const menuProps = buildMenuProps(item, rect, menuWrapperProps)}
              {#if selectionMenu}
                {@const result = selectionMenu(menuProps)}
                {#if result}
                  <result.component {...result.props} />
                {/if}
              {:else if selectionMenuSnippet}
                {@render selectionMenuSnippet(menuProps)}
              {/if}
            {/snippet}
          </CounterRotate>
        {/if}
      {:else}
        <div
          style="
            position: absolute;
            left: {item.rect.origin.x * scale}px;
            top: {item.rect.origin.y * scale}px;
            width: {item.rect.size.width * scale}px;
            height: {item.rect.size.height * scale}px;
            background: transparent;
            outline: {selectedId === item.id ? `1px solid ${bboxStroke}` : 'none'};
            outline-offset: 2px;
            pointer-events: auto;
            cursor: {selectedId === item.id ? 'pointer' : 'default'};
          "
        >
          <Highlight
            rect={item.rect}
            rects={item.rects}
            color="transparent"
            border="1px solid red"
            {scale}
            onClick={(e) => select(e, item.id)}
          />
        </div>

        {#if shouldShowMenu(item.id)}
          <CounterRotate
            rect={{
              origin: { x: item.rect.origin.x * scale, y: item.rect.origin.y * scale },
              size: { width: item.rect.size.width * scale, height: item.rect.size.height * scale },
            }}
            {rotation}
          >
            {#snippet children({ rect, menuWrapperProps })}
              {@const menuProps = buildMenuProps(item, rect, menuWrapperProps)}
              {#if selectionMenu}
                {@const result = selectionMenu(menuProps)}
                {#if result}
                  <result.component {...result.props} />
                {/if}
              {:else if selectionMenuSnippet}
                {@render selectionMenuSnippet(menuProps)}
              {/if}
            {/snippet}
          </CounterRotate>
        {/if}
      {/if}
    {/each}
  </div>
{/if}

// packages/plugin-redaction/src/shared/components/pending-redactions.tsx
import { Fragment, useEffect, useState, useCallback, MouseEvent } from '@framework';
import { CounterRotate } from '@embedpdf/utils/@framework';
import { useRedactionCapability } from '../hooks';
import { RedactionItem } from '@embedpdf/plugin-redaction';
import { Highlight } from './highlight';
import { RedactionSelectionMenuRenderFn } from './types';
import { Rotation } from '@embedpdf/models';

interface PendingRedactionsProps {
  documentId: string;
  pageIndex: number;
  scale: number;
  rotation: Rotation;
  bboxStroke?: string;
  selectionMenu?: RedactionSelectionMenuRenderFn;
}

export function PendingRedactions({
  documentId,
  pageIndex,
  scale,
  bboxStroke = 'rgba(0,0,0,0.8)',
  rotation = Rotation.Degree0,
  selectionMenu,
}: PendingRedactionsProps) {
  const { provides: redaction } = useRedactionCapability();
  const [items, setItems] = useState<RedactionItem[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    if (!redaction) return;

    // Use document-scoped hooks so we only receive events for this document
    const scoped = redaction.forDocument(documentId);

    // Initialize with current state - only show legacy mode items
    const currentState = scoped.getState();
    setItems((currentState.pending[pageIndex] ?? []).filter((it) => it.source === 'legacy'));
    setSelectedId(
      currentState.selected && currentState.selected.page === pageIndex
        ? currentState.selected.id
        : null,
    );

    // Subscribe to future changes - only show legacy mode items
    const off1 = scoped.onPendingChange((map) => {
      setItems((map[pageIndex] ?? []).filter((it) => it.source === 'legacy'));
    });
    const off2 = scoped.onSelectedChange((sel) => {
      setSelectedId(sel && sel.page === pageIndex ? sel.id : null);
    });

    return () => {
      off1?.();
      off2?.();
    };
  }, [redaction, documentId, pageIndex]);

  const select = useCallback(
    (e: MouseEvent, id: string) => {
      e.stopPropagation();
      if (!redaction) return;
      redaction.forDocument(documentId).selectPending(pageIndex, id);
    },
    [redaction, documentId, pageIndex],
  );

  if (!items.length) return null;

  return (
    <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }}>
      {items.map((it) => {
        if (it.kind === 'area') {
          const r = it.rect;
          return (
            <Fragment key={it.id}>
              <div
                style={{
                  position: 'absolute',
                  left: r.origin.x * scale,
                  top: r.origin.y * scale,
                  width: r.size.width * scale,
                  height: r.size.height * scale,
                  background: 'transparent',
                  outline: selectedId === it.id ? `1px solid ${bboxStroke}` : 'none',
                  outlineOffset: '2px',
                  border: `1px solid ${it.markColor}`,
                  pointerEvents: 'auto',
                  cursor: 'pointer',
                }}
                onPointerDown={(e) => select(e, it.id)}
              />
              {selectionMenu && (
                <CounterRotate
                  rect={{
                    origin: { x: r.origin.x * scale, y: r.origin.y * scale },
                    size: { width: r.size.width * scale, height: r.size.height * scale },
                  }}
                  rotation={rotation}
                >
                  {(props) =>
                    selectionMenu({
                      ...props,
                      context: {
                        type: 'redaction',
                        item: it,
                        pageIndex,
                      },
                      selected: selectedId === it.id,
                      placement: {
                        suggestTop: false,
                      },
                    })
                  }
                </CounterRotate>
              )}
            </Fragment>
          );
        }

        const b = it.rect;
        return (
          <Fragment key={it.id}>
            <div
              style={{
                position: 'absolute',
                left: b.origin.x * scale,
                top: b.origin.y * scale,
                width: b.size.width * scale,
                height: b.size.height * scale,
                background: 'transparent',
                outline: selectedId === it.id ? `1px solid ${bboxStroke}` : 'none',
                outlineOffset: '2px',
                pointerEvents: 'auto',
                cursor: selectedId === it.id ? 'pointer' : 'default',
              }}
            >
              <Highlight
                rect={b}
                rects={it.rects}
                color="transparent"
                border={`1px solid ${it.markColor}`}
                scale={scale}
                onClick={(e) => select(e, it.id)}
              />
            </div>
            {selectionMenu && (
              <CounterRotate
                rect={{
                  origin: { x: b.origin.x * scale, y: b.origin.y * scale },
                  size: { width: b.size.width * scale, height: b.size.height * scale },
                }}
                rotation={rotation}
              >
                {(props) =>
                  selectionMenu({
                    ...props,
                    context: {
                      type: 'redaction',
                      item: it,
                      pageIndex,
                    },
                    selected: selectedId === it.id,
                    placement: {
                      suggestTop: false,
                    },
                  })
                }
              </CounterRotate>
            )}
          </Fragment>
        );
      })}
    </div>
  );
}
