// packages/plugin-redaction/src/svelte/components/selection-redact.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import { useRedactionPlugin } from '../hooks/use-redaction.svelte';
  import Highlight from './highlight.svelte';

  interface SelectionRedactProps {
    documentId: string;
    pageIndex: number;
    scale: number;
  }

  let { documentId, pageIndex, scale }: SelectionRedactProps = $props();

  const redactionPlugin = useRedactionPlugin();
  let rects = $state<Rect[]>([]);
  let boundingRect = $state<Rect | null>(null);

  // Get stroke color from plugin (annotation mode uses tool defaults, legacy uses red)
  const strokeColor = $derived(redactionPlugin.plugin?.getPreviewStrokeColor() ?? 'red');

  $effect(() => {
    if (!redactionPlugin.plugin) {
      rects = [];
      boundingRect = null;
      return;
    }

    return redactionPlugin.plugin.onRedactionSelectionChange(documentId, (formattedSelection) => {
      const selection = formattedSelection.find((s) => s.pageIndex === pageIndex);
      rects = selection?.segmentRects ?? [];
      boundingRect = selection?.rect ?? null;
    });
  });
</script>

{#if boundingRect}
  <div
    style:mix-blend-mode="normal"
    style:pointer-events="none"
    style:position="absolute"
    style:inset="0"
  >
    <Highlight
      color="transparent"
      opacity={1}
      {rects}
      {scale}
      border={`1px solid ${strokeColor}`}
    />
  </div>
{/if}

// packages/plugin-redaction/src/shared/components/selection-redact.tsx
import { Rect } from '@embedpdf/models';
import { useEffect, useState } from '@framework';
import { useRedactionPlugin } from '../hooks';
import { Highlight } from './highlight';

interface SelectionRedactProps {
  documentId: string;
  pageIndex: number;
  scale: number;
}

export function SelectionRedact({ documentId, pageIndex, scale }: SelectionRedactProps) {
  const { plugin: redactionPlugin } = useRedactionPlugin();
  const [rects, setRects] = useState<Array<Rect>>([]);
  const [boundingRect, setBoundingRect] = useState<Rect | null>(null);

  // Get stroke color from plugin (annotation mode uses tool defaults, legacy uses red)
  const strokeColor = redactionPlugin?.getPreviewStrokeColor() ?? 'red';

  useEffect(() => {
    if (!redactionPlugin) return;
    return redactionPlugin.onRedactionSelectionChange(documentId, (formattedSelection) => {
      const selection = formattedSelection.find((s) => s.pageIndex === pageIndex);
      setRects(selection?.segmentRects ?? []);
      setBoundingRect(selection?.rect ?? null);
    });
  }, [redactionPlugin, documentId, pageIndex]);

  if (!boundingRect) return null;

  return (
    <div
      style={{
        mixBlendMode: 'normal',
        pointerEvents: 'none',
        position: 'absolute',
        inset: 0,
      }}
    >
      <Highlight
        color={'transparent'}
        opacity={1}
        rects={rects}
        scale={scale}
        border={`1px solid ${strokeColor}`}
      />
    </div>
  );
}
