// packages/plugin-loader/src/shared/components/file-picker.tsx
import { ChangeEvent, useEffect, useRef } from '@framework';
import { useLoaderCapability } from '../hooks';

/** Wrap the viewer root */
export function FilePicker() {
  const { provides: cap } = useLoaderCapability(); // capability
  const inputRef = useRef<HTMLInputElement>(null);

  /* ─── listen for “open file” requests ─── */
  useEffect(() => {
    if (!cap) return;
    const unsub = cap.onOpenFileRequest((req) => {
      if (req === 'open' && inputRef.current) inputRef.current.click();
    });
    return unsub;
  }, [cap]);

  /* ─── handle actual file selection ─── */
  const onChange = async (e: ChangeEvent<HTMLInputElement>) => {
    const file = (e.currentTarget as HTMLInputElement).files?.[0];
    if (file && cap)
      await cap.loadDocument({
        type: 'buffer',
        pdfFile: {
          id: Math.random().toString(36).substring(2, 15),
          name: file.name,
          content: await file.arrayBuffer(),
        },
      });
  };

  return (
    <>
      {/* Hidden picker */}
      <input
        ref={inputRef}
        type="file"
        accept="application/pdf"
        style={{ display: 'none' }}
        onChange={onChange}
      />
    </>
  );
}

// packages/plugin-loader/src/svelte/components/file-picker.svelte
<script lang="ts">
  import { useLoaderCapability } from '../hooks';

  const { provides: loaderProvides } = useLoaderCapability();

  let inputRef: HTMLInputElement | null = null;

  // Subscribe/unsubscribe whenever the capability changes
  $effect(() => {
    const cap = loaderProvides;
    if (!cap) return;

    // Listen for "open file" requests
    const unsubscribe = cap.onOpenFileRequest((req) => {
      if (req === 'open' && inputRef) {
        inputRef.click();
      }
    });

    // Cleanup function
    return () => {
      unsubscribe();
    };
  });

  // Handle actual file selection
  async function onChange(event: Event) {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    const cap = loaderProvides;

    if (file && cap) {
      const arrayBuffer = await file.arrayBuffer();
      await cap.loadDocument({
        type: 'buffer',
        pdfFile: {
          id: Math.random().toString(36).substring(2, 15),
          name: file.name,
          content: arrayBuffer,
        },
      });
    }
  }
</script>

<!-- Hidden file picker -->
<input
  bind:this={inputRef}
  type="file"
  accept="application/pdf"
  style="display: none"
  onchange={onChange}
/>
