// packages/plugin-rotate/src/vue/components/rotate.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useDocumentState } from '@embedpdf/core/vue';
import { Rotation } from '@embedpdf/models';
import { useRotatePlugin } from '../hooks';

interface RotateProps {
  documentId: string;
  pageIndex: number;
  rotation?: Rotation;
  scale?: number;
}

const props = defineProps<RotateProps>();

const { plugin: rotatePlugin } = useRotatePlugin();
const documentState = useDocumentState(() => props.documentId);

const page = computed(() => documentState.value?.document?.pages?.[props.pageIndex]);
const width = computed(() => page.value?.size?.width ?? 0);
const height = computed(() => page.value?.size?.height ?? 0);

// If override is provided, use it directly (consistent with other layer components)
// Otherwise, combine page intrinsic rotation with document rotation
const pageRotation = computed(() => page.value?.rotation ?? 0);
const rotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  const docRotation = documentState.value?.rotation ?? 0;
  return (pageRotation.value + docRotation) % 4;
});

const scale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const matrix = computed(() => {
  if (!rotatePlugin.value) return 'matrix(1, 0, 0, 1, 0, 0)';

  return rotatePlugin.value.getMatrixAsString({
    width: width.value * scale.value,
    height: height.value * scale.value,
    rotation: rotation.value,
  });
});
</script>

<template>
  <div
    v-if="page"
    :style="{
      position: 'absolute',
      transformOrigin: '0 0',
      transform: matrix,
    }"
    v-bind="$attrs"
  >
    <slot />
  </div>
</template>

// packages/plugin-rotate/src/shared/components/rotate.tsx
import { ReactNode, HTMLAttributes, CSSProperties } from '@framework';
import { useDocumentState } from '@embedpdf/core/@framework';
import { Rotation } from '@embedpdf/models';

import { useRotatePlugin } from '../hooks';

type RotateProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  children: ReactNode;
  documentId: string;
  pageIndex: number;
  rotation?: Rotation;
  scale?: number;
  style?: CSSProperties;
};

export function Rotate({
  children,
  documentId,
  pageIndex,
  rotation: rotationOverride,
  scale: scaleOverride,
  style,
  ...props
}: RotateProps) {
  const { plugin: rotatePlugin } = useRotatePlugin();
  const documentState = useDocumentState(documentId);

  const page = documentState?.document?.pages?.[pageIndex];
  const width = page?.size?.width ?? 0;
  const height = page?.size?.height ?? 0;
  // If override is provided, use it directly (consistent with other layer components)
  // Otherwise, combine page intrinsic rotation with document rotation
  const pageRotation = page?.rotation ?? 0;
  const docRotation = documentState?.rotation ?? 0;
  const rotation =
    rotationOverride !== undefined ? rotationOverride : (pageRotation + docRotation) % 4;
  const scale = scaleOverride ?? documentState?.scale ?? 1;

  const matrix =
    rotatePlugin?.getMatrixAsString({
      width: width * scale,
      height: height * scale,
      rotation: rotation,
    }) ?? 'matrix(1, 0, 0, 1, 0, 0)';

  if (!page) return null;

  return (
    <div
      {...props}
      style={{
        position: 'absolute',
        transformOrigin: '0 0',
        transform: matrix,
        ...style,
      }}
    >
      {children}
    </div>
  );
}
