// packages/plugin-print/src/svelte/components/print.svelte
<script lang="ts">
  import { usePrintCapability, usePrintPlugin } from '../hooks';

  const printCapability = usePrintCapability();
  const printPlugin = usePrintPlugin();

  let iframeRef = $state<HTMLIFrameElement | null>(null);
  let urlRef: string | null = null;

  $effect(() => {
    if (!printCapability.provides || !printPlugin.plugin) return;

    const unsubscribe = printPlugin.plugin.onPrintRequest(({ buffer, task }) => {
      const iframe = iframeRef;
      if (!iframe) return;

      // cleanup old URL
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
      }

      const url = URL.createObjectURL(new Blob([buffer], { type: 'application/pdf' }));
      urlRef = url;

      iframe.onload = () => {
        if (iframe.src === url) {
          task.progress({ stage: 'iframe-ready', message: 'Ready to print' });
          iframe.contentWindow?.focus();
          iframe.contentWindow?.print();
          task.progress({ stage: 'printing', message: 'Print dialog opened' });
          task.resolve(buffer);
        }
      };

      iframe.src = url;
    });

    return () => {
      unsubscribe();
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
      }
    };
  });
</script>

<iframe
  bind:this={iframeRef}
  title="Print Document"
  src="about:blank"
  style="position: absolute; display: none;"
/>

// packages/plugin-print/src/vue/components/print.vue
<template>
  <iframe
    ref="iframeRef"
    title="Print Document"
    src="about:blank"
    :style="{
      position: 'absolute',
      display: 'none',
    }"
  />
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { PdfErrorCode } from '@embedpdf/models';
import { usePrintCapability, usePrintPlugin } from '../hooks';

const iframeRef = ref<HTMLIFrameElement | null>(null);
const urlRef = ref<string | null>(null);

const { provides: printCapability } = usePrintCapability();
const { plugin: printPlugin } = usePrintPlugin();

let unsubscribe: (() => void) | undefined;

onMounted(() => {
  if (!printCapability.value || !printPlugin.value) return;

  unsubscribe = printPlugin.value.onPrintRequest((request) => {
    const { options, task } = request;
    const iframe = iframeRef.value;

    if (!iframe) {
      task.reject({
        code: PdfErrorCode.Cancelled,
        message: 'Print iframe not available',
      });
      return;
    }

    // Cleanup previous URL
    if (urlRef.value) {
      URL.revokeObjectURL(urlRef.value);
      urlRef.value = null;
    }

    iframe.src = 'about:blank';

    const prepareTask = printPlugin.value!.preparePrintDocument(options);
    prepareTask.wait((buffer) => {
      task.progress({ stage: 'document-ready', message: 'Document prepared successfully' });

      const url = URL.createObjectURL(new Blob([buffer], { type: 'application/pdf' }));
      urlRef.value = url;

      iframe.onload = () => {
        if (iframe.src === url) {
          task.progress({ stage: 'iframe-ready', message: 'Ready to print' });
          iframe.contentWindow?.focus();
          iframe.contentWindow?.print();
          task.progress({ stage: 'printing', message: 'Print dialog opened' });
          task.resolve(buffer);
        }
      };

      iframe.src = url;
    }, task.fail);
  });
});

onUnmounted(() => {
  unsubscribe?.();
  if (urlRef.value) {
    URL.revokeObjectURL(urlRef.value);
  }
});
</script>
