// packages/plugin-selection/src/svelte/components/CopyToClipboard.svelte
<script lang="ts">
  import { useSelectionCapability } from '../hooks/use-selection.svelte';

  const { provides: sel } = $derived(useSelectionCapability());

  $effect(() => {
    if (!sel) return;

    return sel.onCopyToClipboard((text) => {
      navigator.clipboard.writeText(text).catch((err) => {
        console.error('Failed to copy text to clipboard:', err);
      });
    });
  });
</script>

<!-- This component renders nothing to the DOM -->

// packages/plugin-selection/src/preact/components/copy-to-clipboard.tsx
import { useEffect } from 'preact/hooks';

import { useSelectionCapability } from '../hooks';

export function CopyToClipboard() {
  const { provides: sel } = useSelectionCapability();

  useEffect(() => {
    if (!sel) return;
    return sel.onCopyToClipboard((text) => {
      navigator.clipboard.writeText(text);
    });
  }, [sel]);

  return null;
}
