// packages/plugin-annotation/src/shared/components/annotation-layer.tsx
import { HTMLAttributes, CSSProperties, useMemo } from '@framework';
import { useDocumentState } from '@embedpdf/core/@framework';
import { Annotations } from './annotations';
import { TextMarkup } from './text-markup';
import {
  ResizeHandleUI,
  VertexHandleUI,
  CustomAnnotationRenderer,
  AnnotationSelectionMenuRenderFn,
  GroupSelectionMenuRenderFn,
  BoxedAnnotationRenderer,
} from './types';
import { AnnotationPaintLayer } from './annotation-paint-layer';
import { PdfAnnotationObject, Rotation } from '@embedpdf/models';
import { useRegisteredRenderers } from '../context/renderer-registry';

type AnnotationLayerProps = Omit<HTMLAttributes<HTMLDivElement>, 'style'> & {
  /** The ID of the document that this layer displays annotations for */
  documentId: string;
  pageIndex: number;
  scale?: number;
  rotation?: number;
  /** Customize selection menu across all annotations on this layer */
  selectionMenu?: AnnotationSelectionMenuRenderFn;
  /** Customize group selection menu across all annotations on this layer */
  groupSelectionMenu?: GroupSelectionMenuRenderFn;
  style?: CSSProperties;
  /** Customize resize handles */
  resizeUI?: ResizeHandleUI;
  /** Customize vertex handles */
  vertexUI?: VertexHandleUI;
  /** Customize selection outline color */
  selectionOutlineColor?: string;
  /** Customize annotation renderer */
  customAnnotationRenderer?: CustomAnnotationRenderer<PdfAnnotationObject>;
  /** Custom renderers for specific annotation types (provided by external plugins) */
  annotationRenderers?: BoxedAnnotationRenderer[];
};

export function AnnotationLayer({
  style,
  documentId,
  pageIndex,
  scale: overrideScale,
  rotation: overrideRotation,
  selectionMenu,
  groupSelectionMenu,
  resizeUI,
  vertexUI,
  selectionOutlineColor,
  customAnnotationRenderer,
  annotationRenderers,
  ...props
}: AnnotationLayerProps) {
  const documentState = useDocumentState(documentId);
  const page = documentState?.document?.pages?.[pageIndex];
  const width = page?.size?.width ?? 0;
  const height = page?.size?.height ?? 0;

  // Auto-load renderers from context
  const contextRenderers = useRegisteredRenderers();

  // Merge: context + explicit props (props take precedence by id)
  const allRenderers = useMemo(() => {
    const merged = [...contextRenderers];
    for (const renderer of annotationRenderers ?? []) {
      const idx = merged.findIndex((r) => r.id === renderer.id);
      if (idx >= 0) merged[idx] = renderer;
      else merged.push(renderer);
    }
    return merged;
  }, [contextRenderers, annotationRenderers]);

  const actualScale = useMemo(() => {
    if (overrideScale !== undefined) return overrideScale;
    return documentState?.scale ?? 1;
  }, [overrideScale, documentState?.scale]);

  const actualRotation = useMemo(() => {
    if (overrideRotation !== undefined) return overrideRotation;
    // Combine page intrinsic rotation with document rotation
    const pageRotation = page?.rotation ?? 0;
    const docRotation = documentState?.rotation ?? 0;
    return ((pageRotation + docRotation) % 4) as Rotation;
  }, [overrideRotation, page?.rotation, documentState?.rotation]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      <Annotations
        documentId={documentId}
        selectionMenu={selectionMenu}
        groupSelectionMenu={groupSelectionMenu}
        pageIndex={pageIndex}
        scale={actualScale}
        rotation={actualRotation}
        pageWidth={width}
        pageHeight={height}
        resizeUI={resizeUI}
        vertexUI={vertexUI}
        selectionOutlineColor={selectionOutlineColor}
        customAnnotationRenderer={customAnnotationRenderer}
        annotationRenderers={allRenderers}
      />
      <TextMarkup documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
      <AnnotationPaintLayer documentId={documentId} pageIndex={pageIndex} scale={actualScale} />
    </div>
  );
}

// packages/plugin-annotation/src/vue/components/annotation-layer.vue
<template>
  <div>
    <Annotations
      :documentId="documentId"
      :pageIndex="pageIndex"
      :scale="actualScale"
      :rotation="actualRotation"
      :pageWidth="pageWidth"
      :pageHeight="pageHeight"
      :resizeUI="resizeUI"
      :vertexUI="vertexUI"
      :selectionOutlineColor="selectionOutlineColor"
      :selectionMenu="selectionMenu"
      :groupSelectionMenu="groupSelectionMenu"
      :annotationRenderers="allRenderers"
    >
      <!-- Forward slots for manual customization (only used if selectionMenu prop not provided) -->
      <template #selection-menu="slotProps">
        <slot name="selection-menu" v-bind="slotProps"></slot>
      </template>
      <template #group-selection-menu="slotProps">
        <slot name="group-selection-menu" v-bind="slotProps"></slot>
      </template>
      <template #resize-handle="slotProps">
        <slot name="resize-handle" v-bind="slotProps"></slot>
      </template>
      <template #vertex-handle="slotProps">
        <slot name="vertex-handle" v-bind="slotProps"></slot>
      </template>
    </Annotations>
    <TextMarkup :documentId="documentId" :pageIndex="pageIndex" :scale="actualScale" />
    <AnnotationPaintLayer :documentId="documentId" :pageIndex="pageIndex" :scale="actualScale" />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useDocumentState } from '@embedpdf/core/vue';
import { Rotation } from '@embedpdf/models';
import Annotations from './annotations.vue';
import TextMarkup from './text-markup.vue';
import AnnotationPaintLayer from './annotation-paint-layer.vue';
import {
  AnnotationSelectionMenuRenderFn,
  GroupSelectionMenuRenderFn,
  ResizeHandleUI,
  VertexHandleUI,
} from '../types';
import { useRendererRegistry, type BoxedAnnotationRenderer } from '../context';

const props = defineProps<{
  /** The ID of the document that this layer displays annotations for */
  documentId: string;
  pageIndex: number;
  scale?: number;
  rotation?: number;
  /** Customize resize handles */
  resizeUI?: ResizeHandleUI;
  /** Customize vertex handles */
  vertexUI?: VertexHandleUI;
  /** Customize selection outline color */
  selectionOutlineColor?: string;
  /** Customize selection menu */
  selectionMenu?: AnnotationSelectionMenuRenderFn;
  /** Customize group selection menu */
  groupSelectionMenu?: GroupSelectionMenuRenderFn;
  /** Custom renderers for specific annotation types (provided by external plugins) */
  annotationRenderers?: BoxedAnnotationRenderer[];
}>();

// Get renderers from registry (provided by parent)
const registry = useRendererRegistry();

// Merge: registry + explicit props (props take precedence by id)
const allRenderers = computed(() => {
  const fromRegistry = registry?.getAll() ?? [];
  const fromProps = props.annotationRenderers ?? [];
  const merged = [...fromRegistry];
  for (const r of fromProps) {
    const idx = merged.findIndex((m) => m.id === r.id);
    if (idx >= 0) merged[idx] = r;
    else merged.push(r);
  }
  return merged;
});

const documentState = useDocumentState(() => props.documentId);
const page = computed(() => documentState.value?.document?.pages?.[props.pageIndex]);
const pageWidth = computed(() => page.value?.size?.width ?? 0);
const pageHeight = computed(() => page.value?.size?.height ?? 0);

const actualScale = computed(() => {
  if (props.scale !== undefined) return props.scale;
  return documentState.value?.scale ?? 1;
});

const actualRotation = computed(() => {
  if (props.rotation !== undefined) return props.rotation;
  // Combine page intrinsic rotation with document rotation
  const pageRotation = page.value?.rotation ?? 0;
  const docRotation = documentState.value?.rotation ?? 0;
  return ((pageRotation + docRotation) % 4) as Rotation;
});
</script>
