// packages/plugin-annotation/src/svelte/components/GroupSelectionBox.svelte
<!-- GroupSelectionBox.svelte -->
<script lang="ts">
  import { boundingRectOrEmpty, type Rect } from '@embedpdf/models';
  import type { TrackedAnnotation } from '@embedpdf/plugin-annotation';
  import {
    useInteractionHandles,
    CounterRotate,
    type MenuWrapperProps,
  } from '@embedpdf/utils/svelte';
  import { useDocumentPermissions } from '@embedpdf/core/svelte';
  import { useAnnotationPlugin } from '../hooks';
  import type {
    GroupSelectionContext,
    GroupSelectionMenuProps,
    GroupSelectionMenuRenderFn,
    ResizeHandleUI,
  } from '../types';
  import type { Snippet } from 'svelte';

  interface GroupSelectionBoxProps {
    documentId: string;
    pageIndex: number;
    scale: number;
    rotation: number;
    pageWidth: number;
    pageHeight: number;
    /** All selected annotations on this page */
    selectedAnnotations: TrackedAnnotation[];
    /** Whether the group is draggable (all annotations must be group-draggable) */
    isDraggable: boolean;
    /** Whether the group is resizable (all annotations must be group-resizable) */
    isResizable: boolean;
    /** Resize handle UI customization */
    resizeUI?: ResizeHandleUI;
    /** Selection outline color */
    selectionOutlineColor?: string;
    /** Outline offset */
    outlineOffset?: number;
    /** Z-index for the group box */
    zIndex?: number;
    /** Group selection menu render function */
    groupSelectionMenu?: GroupSelectionMenuRenderFn;
    /** Snippet for custom group selection menu (slot-based approach) */
    groupSelectionMenuSnippet?: Snippet<[GroupSelectionMenuProps]>;
  }

  let {
    documentId,
    pageIndex,
    scale,
    rotation,
    pageWidth,
    pageHeight,
    selectedAnnotations,
    isDraggable,
    isResizable,
    resizeUI,
    selectionOutlineColor = '#007ACC',
    outlineOffset = 2,
    zIndex = 100,
    groupSelectionMenu,
    groupSelectionMenuSnippet,
  }: GroupSelectionBoxProps = $props();

  const annotationPlugin = useAnnotationPlugin();
  const permissions = useDocumentPermissions(() => documentId);
  let gestureBase = $state<Rect | null>(null);
  let isDraggingRef = $state(false);
  let isResizingRef = $state(false);

  // Check permissions before allowing drag/resize
  const effectiveIsDraggable = $derived(permissions.canModifyAnnotations && isDraggable);
  const effectiveIsResizable = $derived(permissions.canModifyAnnotations && isResizable);

  // Helper to compute group box on demand
  function getGroupBox(): Rect {
    const rects = selectedAnnotations.map((ta) => ta.object.rect);
    return boundingRectOrEmpty(rects);
  }

  // Compute the group bounding box from all selected annotations (for reactive bindings)
  const groupBox = $derived.by(getGroupBox);

  // Preview state for the group box during drag/resize
  let previewGroupBox = $state<Rect>(getGroupBox());

  // Sync preview with actual group box when not dragging/resizing
  $effect(() => {
    if (!isDraggingRef && !isResizingRef) {
      const newBox = groupBox;
      // Only update if values actually changed (not just object reference)
      if (
        previewGroupBox.origin.x !== newBox.origin.x ||
        previewGroupBox.origin.y !== newBox.origin.y ||
        previewGroupBox.size.width !== newBox.size.width ||
        previewGroupBox.size.height !== newBox.size.height
      ) {
        previewGroupBox = newBox;
      }
    }
  });

  // UI constants
  const HANDLE_COLOR = $derived(resizeUI?.color ?? '#007ACC');
  const HANDLE_SIZE = $derived(resizeUI?.size ?? 12);

  // Use interaction handles for both drag and resize
  const interactionHandles = useInteractionHandles(() => ({
    controller: {
      element: previewGroupBox,
      constraints: {
        minWidth: 20,
        minHeight: 20,
        boundingBox: { width: pageWidth, height: pageHeight },
      },
      maintainAspectRatio: false,
      pageRotation: rotation,
      scale: scale,
      enabled: true,
      onUpdate: (event) => {
        if (!event.transformData?.type) return;
        if (!annotationPlugin.plugin) return;

        const plugin = annotationPlugin.plugin;
        const transformType = event.transformData.type;
        const isMove = transformType === 'move';
        const isResize = transformType === 'resize';

        // Skip drag operations if group is not draggable
        if (isMove && !effectiveIsDraggable) return;

        if (event.state === 'start') {
          gestureBase = getGroupBox();

          if (isMove) {
            isDraggingRef = true;
            // Use unified drag API - plugin handles attached links automatically
            plugin.startDrag(documentId, {
              annotationIds: selectedAnnotations.map((ta) => ta.object.id),
              pageSize: { width: pageWidth, height: pageHeight },
            });
          } else if (isResize) {
            isResizingRef = true;
            // Use unified resize API - plugin handles attached links automatically
            plugin.startResize(documentId, {
              annotationIds: selectedAnnotations.map((ta) => ta.object.id),
              pageSize: { width: pageWidth, height: pageHeight },
              resizeHandle: event.transformData.metadata?.handle ?? 'se',
            });
          }
        }

        const base = gestureBase ?? getGroupBox();

        if (isMove && event.transformData.changes.rect) {
          // Calculate delta from original position
          const newRect = event.transformData.changes.rect;
          const rawDelta = {
            x: newRect.origin.x - base.origin.x,
            y: newRect.origin.y - base.origin.y,
          };

          // Plugin clamps delta and emits events (attached links receive updates too)
          const clampedDelta = plugin.updateDrag(documentId, rawDelta);

          // Update preview group box with clamped delta
          previewGroupBox = {
            ...base,
            origin: {
              x: base.origin.x + clampedDelta.x,
              y: base.origin.y + clampedDelta.y,
            },
          };
        } else if (isResize && event.transformData.changes.rect) {
          const newGroupBox = event.transformData.changes.rect;

          // Plugin computes rects for all participants and emits events
          plugin.updateResize(documentId, newGroupBox);

          // Update preview
          previewGroupBox = newGroupBox;
        }

        if (event.state === 'end') {
          gestureBase = null;

          if (isMove && isDraggingRef) {
            isDraggingRef = false;
            // Plugin commits all patches (selected + attached links) - no patch building needed!
            plugin.commitDrag(documentId);
          } else if (isResize && isResizingRef) {
            isResizingRef = false;
            // Plugin commits all patches (selected + attached links) - no patch building needed!
            plugin.commitResize(documentId);
          }
        }
      },
    },
    resizeUI: {
      handleSize: HANDLE_SIZE,
      spacing: outlineOffset,
      offsetMode: 'outside',
      includeSides: true,
      zIndex: zIndex + 1,
    },
    vertexUI: {
      vertexSize: 0,
      zIndex: zIndex,
    },
    includeVertices: false,
  }));

  // Derived accessors for template
  const resizeHandles = $derived(interactionHandles.resize);

  // --- Group Selection Menu Logic ---

  // Check if we should show menu
  const shouldShowMenu = $derived(!!groupSelectionMenu || !!groupSelectionMenuSnippet);

  // Build context object for group selection menu
  function buildContext(): GroupSelectionContext {
    return {
      type: 'group',
      annotations: selectedAnnotations,
      pageIndex,
    };
  }

  // Build menu props
  function buildMenuProps(rect: Rect, menuWrapperProps: MenuWrapperProps): GroupSelectionMenuProps {
    return {
      context: buildContext(),
      selected: true,
      rect,
      placement: { suggestTop: false },
      menuWrapperProps,
    };
  }
</script>

{#if selectedAnnotations.length >= 2}
  <div data-group-selection-box data-no-interaction>
    <!-- Group box - draggable only if effectiveIsDraggable is true -->
    <div
      {...effectiveIsDraggable
        ? interactionHandles.dragProps
        : { onpointerdown: (e: PointerEvent) => e.stopPropagation() }}
      style:position="absolute"
      style:left="{previewGroupBox.origin.x * scale}px"
      style:top="{previewGroupBox.origin.y * scale}px"
      style:width="{previewGroupBox.size.width * scale}px"
      style:height="{previewGroupBox.size.height * scale}px"
      style:outline="2px dashed {selectionOutlineColor}"
      style:outline-offset="{outlineOffset - 1}px"
      style:cursor={effectiveIsDraggable ? 'move' : 'default'}
      style:touch-action="none"
      style:z-index={zIndex}
    >
      <!-- Resize handles -->
      {#if effectiveIsResizable}
        {#each resizeHandles as { key, style: handleStyle, ...hProps } (key)}
          {#if resizeUI?.component}
            {@render resizeUI.component({ ...hProps, backgroundColor: HANDLE_COLOR })}
          {:else}
            <div {...hProps} style="{handleStyle}; background-color: {HANDLE_COLOR};"></div>
          {/if}
        {/each}
      {/if}
    </div>

    <!-- Group selection menu -->
    {#if shouldShowMenu}
      <CounterRotate
        rect={{
          origin: {
            x: previewGroupBox.origin.x * scale,
            y: previewGroupBox.origin.y * scale,
          },
          size: {
            width: previewGroupBox.size.width * scale,
            height: previewGroupBox.size.height * scale,
          },
        }}
        {rotation}
      >
        {#snippet children({ rect, menuWrapperProps })}
          {@const menuProps = buildMenuProps(rect, menuWrapperProps)}
          {#if groupSelectionMenu}
            <!-- Priority 1: Render function (schema-driven) -->
            {@const result = groupSelectionMenu(menuProps)}
            {#if result}
              <result.component {...result.props} />
            {/if}
          {:else if groupSelectionMenuSnippet}
            <!-- Priority 2: Snippet (manual customization) -->
            {@render groupSelectionMenuSnippet(menuProps)}
          {/if}
        {/snippet}
      </CounterRotate>
    {/if}
  </div>
{/if}

// packages/plugin-annotation/src/vue/components/group-selection-box.vue
<template>
  <div v-if="selectedAnnotations.length >= 2" data-group-selection-box data-no-interaction>
    <!-- Group box - draggable only if effectiveIsDraggable is true -->
    <div
      v-bind="effectiveIsDraggable ? dragProps : {}"
      :style="boxStyle"
      @pointerdown="!effectiveIsDraggable ? $event.stopPropagation() : undefined"
    >
      <!-- Resize handles -->
      <template v-if="effectiveIsResizable">
        <template v-for="{ key, style, ...handle } in resize" :key="key">
          <slot
            v-if="slots['resize-handle']"
            name="resize-handle"
            v-bind="{ key, style, ...handle, backgroundColor: HANDLE_COLOR }"
          >
            <div v-bind="handle" :style="[style, { backgroundColor: HANDLE_COLOR }]" />
          </slot>
          <div v-else v-bind="handle" :style="[style, { backgroundColor: HANDLE_COLOR }]" />
        </template>
      </template>
    </div>

    <!-- Group selection menu -->
    <CounterRotate v-if="shouldShowMenu" :rect="menuRect" :rotation="rotation">
      <template #default="{ rect, menuWrapperProps }">
        <!-- Priority 1: Render function prop (schema-driven) -->
        <component v-if="groupSelectionMenu" :is="renderGroupMenu(rect, menuWrapperProps)" />

        <!-- Priority 2: Slot (manual customization) -->
        <slot
          v-else
          name="group-selection-menu"
          :context="menuContext"
          :selected="true"
          :rect="rect"
          :placement="menuPlacement"
          :menuWrapperProps="menuWrapperProps"
        />
      </template>
    </CounterRotate>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, useSlots, VNode, shallowRef, watch } from 'vue';
import { Rect, boundingRectOrEmpty } from '@embedpdf/models';
import {
  CounterRotate,
  MenuWrapperProps,
  SelectionMenuPlacement,
  useInteractionHandles,
} from '@embedpdf/utils/vue';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import { useDocumentPermissions } from '@embedpdf/core/vue';
import { useAnnotationPlugin } from '../hooks';
import {
  GroupSelectionContext,
  GroupSelectionMenuProps,
  GroupSelectionMenuRenderFn,
  ResizeHandleUI,
} from '../types';

const props = withDefaults(
  defineProps<{
    documentId: string;
    pageIndex: number;
    scale: number;
    rotation: number;
    pageWidth: number;
    pageHeight: number;
    /** All selected annotations on this page */
    selectedAnnotations: TrackedAnnotation[];
    /** Whether the group is draggable (all annotations must be group-draggable) */
    isDraggable: boolean;
    /** Whether the group is resizable (all annotations must be group-resizable) */
    isResizable: boolean;
    /** Resize handle UI customization */
    resizeUI?: ResizeHandleUI;
    /** Selection outline color */
    selectionOutlineColor?: string;
    /** Outline offset */
    outlineOffset?: number;
    /** Z-index for the group box */
    zIndex?: number;
    /** Group selection menu render function */
    groupSelectionMenu?: GroupSelectionMenuRenderFn;
  }>(),
  {
    selectionOutlineColor: '#007ACC',
    outlineOffset: 2,
    zIndex: 100,
  },
);

const slots = useSlots();
const { plugin: annotationPlugin } = useAnnotationPlugin();
const permissions = useDocumentPermissions(() => props.documentId);
const gestureBase = shallowRef<Rect | null>(null);
const isDraggingRef = ref(false);
const isResizingRef = ref(false);

// Check permissions before allowing drag/resize
const effectiveIsDraggable = computed(
  () => permissions.value.canModifyAnnotations && props.isDraggable,
);
const effectiveIsResizable = computed(
  () => permissions.value.canModifyAnnotations && props.isResizable,
);

const HANDLE_COLOR = computed(() => props.resizeUI?.color ?? '#007ACC');
const HANDLE_SIZE = computed(() => props.resizeUI?.size ?? 12);

// Compute the group bounding box from all selected annotations
const groupBox = computed(() => {
  const rects = props.selectedAnnotations.map((ta) => ta.object.rect);
  return boundingRectOrEmpty(rects);
});

// Preview state for the group box during drag/resize
const previewGroupBox = shallowRef<Rect>(groupBox.value);

// Watch for groupBox changes and sync previewGroupBox when not dragging/resizing
// Use watchEffect equivalent via computed with side effects won't work, need explicit watch
watch(
  () => groupBox.value,
  (newGroupBox) => {
    if (!isDraggingRef.value && !isResizingRef.value) {
      previewGroupBox.value = newGroupBox;
    }
  },
  { immediate: true },
);

// Box styling
const boxStyle = computed(() => ({
  position: 'absolute' as 'absolute',
  left: `${previewGroupBox.value.origin.x * props.scale}px`,
  top: `${previewGroupBox.value.origin.y * props.scale}px`,
  width: `${previewGroupBox.value.size.width * props.scale}px`,
  height: `${previewGroupBox.value.size.height * props.scale}px`,
  outline: `2px dashed ${props.selectionOutlineColor}`,
  outlineOffset: `${props.outlineOffset - 1}px`,
  cursor: effectiveIsDraggable.value ? 'move' : 'default',
  touchAction: 'none',
  zIndex: props.zIndex,
}));

// Menu rect for counter-rotate component
const menuRect = computed<Rect>(() => ({
  origin: {
    x: previewGroupBox.value.origin.x * props.scale,
    y: previewGroupBox.value.origin.y * props.scale,
  },
  size: {
    width: previewGroupBox.value.size.width * props.scale,
    height: previewGroupBox.value.size.height * props.scale,
  },
}));

// Menu context
const menuContext = computed<GroupSelectionContext>(() => ({
  type: 'group',
  annotations: props.selectedAnnotations,
  pageIndex: props.pageIndex,
}));

// Placement hints
const menuPlacement = computed<SelectionMenuPlacement>(() => ({
  suggestTop: false,
}));

// Check if we should show menu
const shouldShowMenu = computed(() => {
  return props.groupSelectionMenu || slots['group-selection-menu'];
});

// Render menu via function
const renderGroupMenu = (rect: Rect, menuWrapperProps: MenuWrapperProps): VNode | null => {
  if (!props.groupSelectionMenu) return null;

  return props.groupSelectionMenu({
    rect,
    menuWrapperProps,
    selected: true,
    placement: menuPlacement.value,
    context: menuContext.value,
  });
};

// Element snapshot for interaction handles
const elementSnapshot = computed(() => previewGroupBox.value);

// Constraints
const constraintsSnapshot = computed(() => ({
  minWidth: 20,
  minHeight: 20,
  boundingBox: {
    width: props.pageWidth,
    height: props.pageHeight,
  },
}));

// Use interaction handles for both drag and resize
const { dragProps, resize } = useInteractionHandles({
  controller: {
    element: elementSnapshot,
    vertices: computed(() => []),
    constraints: constraintsSnapshot,
    maintainAspectRatio: computed(() => false),
    pageRotation: computed(() => props.rotation),
    scale: computed(() => props.scale),
    enabled: computed(() => true),
    onUpdate: (event) => {
      if (!event.transformData?.type) return;
      if (!annotationPlugin.value) return;

      const plugin = annotationPlugin.value;
      const transformType = event.transformData.type;
      const isMove = transformType === 'move';
      const isResize = transformType === 'resize';

      // Skip drag operations if group is not draggable
      if (isMove && !effectiveIsDraggable.value) return;

      if (event.state === 'start') {
        gestureBase.value = groupBox.value;

        if (isMove) {
          isDraggingRef.value = true;
          // Use unified drag API - plugin handles attached links automatically
          plugin.startDrag(props.documentId, {
            annotationIds: props.selectedAnnotations.map((ta) => ta.object.id),
            pageSize: { width: props.pageWidth, height: props.pageHeight },
          });
        } else if (isResize) {
          isResizingRef.value = true;
          // Use unified resize API - plugin handles attached links automatically
          plugin.startResize(props.documentId, {
            annotationIds: props.selectedAnnotations.map((ta) => ta.object.id),
            pageSize: { width: props.pageWidth, height: props.pageHeight },
            resizeHandle: event.transformData.metadata?.handle ?? 'se',
          });
        }
      }

      const base = gestureBase.value ?? groupBox.value;

      if (isMove && event.transformData.changes.rect) {
        // Calculate delta from original position
        const newRect = event.transformData.changes.rect;
        const rawDelta = {
          x: newRect.origin.x - base.origin.x,
          y: newRect.origin.y - base.origin.y,
        };

        // Plugin clamps delta and emits events (attached links receive updates too)
        const clampedDelta = plugin.updateDrag(props.documentId, rawDelta);

        // Update preview group box with clamped delta
        previewGroupBox.value = {
          ...base,
          origin: {
            x: base.origin.x + clampedDelta.x,
            y: base.origin.y + clampedDelta.y,
          },
        };
      } else if (isResize && event.transformData.changes.rect) {
        const newGroupBox = event.transformData.changes.rect;

        // Plugin computes rects for all participants and emits events
        plugin.updateResize(props.documentId, newGroupBox);

        // Update preview
        previewGroupBox.value = newGroupBox;
      }

      if (event.state === 'end') {
        gestureBase.value = null;

        if (isMove && isDraggingRef.value) {
          isDraggingRef.value = false;
          // Plugin commits all patches (selected + attached links) - no patch building needed!
          plugin.commitDrag(props.documentId);
        } else if (isResize && isResizingRef.value) {
          isResizingRef.value = false;
          // Plugin commits all patches (selected + attached links) - no patch building needed!
          plugin.commitResize(props.documentId);
        }
      }
    },
  },
  resizeUI: {
    handleSize: HANDLE_SIZE.value,
    spacing: props.outlineOffset,
    offsetMode: 'outside',
    includeSides: true,
    zIndex: props.zIndex + 1,
  },
  vertexUI: {
    vertexSize: 0,
    zIndex: props.zIndex,
  },
  includeVertices: false,
});
</script>
