// packages/plugin-annotation/src/vue/components/annotations/link-locked.vue
<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { PdfLinkAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../../context/types';
import { useAnnotationCapability } from '../../hooks';

const props = defineProps<AnnotationRendererProps<PdfLinkAnnoObject>>();

const { provides } = useAnnotationCapability();

const handleClick = () => {
  const target = props.annotation.object.target;
  if (!target || !provides.value) return;
  provides.value.forDocument(props.documentId).navigateTarget(target);
};
</script>

<template>
  <div
    @click="handleClick"
    :style="{
      width: '100%',
      height: '100%',
      cursor: 'pointer',
      pointerEvents: 'auto',
    }"
  />
</template>

// packages/plugin-annotation/src/shared/components/annotations/link-locked.tsx
import { useCallback } from '@framework';
import { PdfLinkAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '../types';
import { useAnnotationCapability } from '../../hooks/use-annotation';

export function LinkLockedMode({
  annotation,
  documentId,
}: AnnotationRendererProps<PdfLinkAnnoObject>) {
  const { provides } = useAnnotationCapability();

  const handleClick = useCallback(() => {
    const target = annotation.object.target;
    if (!target || !provides) return;

    provides.forDocument(documentId).navigateTarget(target);
  }, [annotation.object.target, provides, documentId]);

  return (
    <div
      onClick={handleClick}
      style={{
        width: '100%',
        height: '100%',
        cursor: 'pointer',
        pointerEvents: 'auto',
      }}
    />
  );
}
