// packages/plugin-annotation/src/vue/components/annotations/stamp.vue
<template>
  <div
    :style="{
      position: 'absolute',
      width: '100%',
      height: '100%',
      zIndex: 2,
      pointerEvents: !onClick ? 'none' : isSelected ? 'none' : 'auto',
      cursor: onClick ? 'pointer' : 'default',
    }"
    @pointerdown="onClick"
  >
    <RenderAnnotation
      :documentId="documentId"
      :pageIndex="pageIndex"
      :annotation="{ ...annotation.object, id: annotation.object.id }"
      :scaleFactor="scale"
      :unrotated="unrotated"
    />
  </div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { PdfStampAnnoObject } from '@embedpdf/models';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import RenderAnnotation from '../render-annotation.vue';

const props = defineProps<{
  isSelected: boolean;
  annotation: TrackedAnnotation<PdfStampAnnoObject>;
  documentId: string;
  pageIndex: number;
  scale: number;
  onClick?: (e: PointerEvent) => void;
}>();

const unrotated = computed(
  () => !!props.annotation.object.rotation && !!props.annotation.object.unrotatedRect,
);
</script>

// packages/plugin-annotation/src/shared/components/annotations/stamp.tsx
import { MouseEvent } from '@framework';
import { PdfStampAnnoObject } from '@embedpdf/models';
import { TrackedAnnotation } from '@embedpdf/plugin-annotation';
import { RenderAnnotation } from '../render-annotation';

interface StampProps {
  isSelected: boolean;
  annotation: TrackedAnnotation<PdfStampAnnoObject>;
  documentId: string;
  pageIndex: number;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
}

export function Stamp({
  isSelected,
  annotation,
  documentId,
  pageIndex,
  scale,
  onClick,
}: StampProps) {
  const unrotated = !!annotation.object.rotation && !!annotation.object.unrotatedRect;

  return (
    <div
      style={{
        position: 'absolute',
        width: '100%',
        height: '100%',
        zIndex: 2,
        pointerEvents: !onClick ? 'none' : isSelected ? 'none' : 'auto',
        cursor: onClick ? 'pointer' : 'default',
      }}
      onPointerDown={onClick}
    >
      <RenderAnnotation
        documentId={documentId}
        pageIndex={pageIndex}
        annotation={{ ...annotation.object, id: annotation.object.id }}
        scaleFactor={scale}
        unrotated={unrotated}
      />
    </div>
  );
}
