// packages/plugin-thumbnail/src/vue/components/thumbnails-pane.vue
<script setup lang="ts">
import { onMounted, onBeforeUnmount, ref, watchEffect, nextTick, useAttrs } from 'vue';
import { useThumbnailPlugin } from '../hooks';
import type { WindowState } from '@embedpdf/plugin-thumbnail';

const attrs = useAttrs();

const { plugin: thumbnailPlugin } = useThumbnailPlugin();
const viewportRef = ref<HTMLDivElement | null>(null);
const windowState = ref<WindowState | null>(null);

let offWindow: (() => void) | null = null;
let offScrollTo: (() => void) | null = null;

watchEffect((onCleanup) => {
  if (!thumbnailPlugin.value) return;
  offWindow?.();
  offWindow = thumbnailPlugin.value.onWindow((w) => (windowState.value = w));
  onCleanup(() => offWindow?.());
});

// Setup scroll listener on mount
onMounted(() => {
  const vp = viewportRef.value;
  if (!vp || !thumbnailPlugin.value) return;

  const onScroll = () => thumbnailPlugin.value!.updateWindow(vp.scrollTop, vp.clientHeight);
  vp.addEventListener('scroll', onScroll);

  // Setup resize observer for viewport changes
  const resizeObserver = new ResizeObserver(() => {
    thumbnailPlugin.value!.updateWindow(vp.scrollTop, vp.clientHeight);
  });
  resizeObserver.observe(vp);

  // initial push
  thumbnailPlugin.value.updateWindow(vp.scrollTop, vp.clientHeight);

  onBeforeUnmount(() => {
    vp.removeEventListener('scroll', onScroll);
    resizeObserver.disconnect();
  });
});

// Setup scrollTo subscription only after window is ready
watchEffect((onCleanup) => {
  const vp = viewportRef.value;
  if (!vp || !thumbnailPlugin.value || !windowState.value) return;

  offScrollTo = thumbnailPlugin.value.onScrollTo(({ top, behavior }) => {
    // Wait for Vue to finish rendering the content before scrolling
    nextTick(() => {
      vp.scrollTo({ top, behavior });
    });
  });

  onCleanup(() => offScrollTo?.());
});

onBeforeUnmount(() => {
  offWindow?.();
  offScrollTo?.();
});
</script>

<template>
  <div
    ref="viewportRef"
    :style="{
      overflowY: 'auto',
      position: 'relative',
      paddingTop: (thumbnailPlugin?.cfg?.paddingY ?? 0) + 'px',
      paddingBottom: (thumbnailPlugin?.cfg?.paddingY ?? 0) + 'px',
    }"
    v-bind="attrs"
  >
    <div :style="{ height: (windowState?.totalHeight ?? 0) + 'px', position: 'relative' }">
      <!-- ✅ Use a template v-for to render the default scoped slot -->
      <template v-for="m in windowState?.items ?? []" :key="m.pageIndex">
        <slot :meta="m" />
      </template>
    </div>
  </div>
</template>

// packages/plugin-thumbnail/src/svelte/components/ThumbnailsPane.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ThumbMeta, WindowState } from '@embedpdf/plugin-thumbnail';
  import { useThumbnailPlugin } from '../hooks';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
    children: Snippet<[ThumbMeta]>;
  }

  const { children, ...divProps }: Props = $props();

  const { plugin: thumbnailPlugin } = useThumbnailPlugin();

  let viewportRef: HTMLDivElement | undefined;
  let window = $state<WindowState | null>(null);

  // 1) subscribe once to window updates
  $effect(() => {
    if (!thumbnailPlugin) return;
    return thumbnailPlugin.onWindow((newWindow) => {
      window = newWindow;
    });
  });

  // 2) keep plugin in sync while the user scrolls
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin) return;

    const onScroll = () => {
      thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
    };

    vp.addEventListener('scroll', onScroll);
    return () => vp.removeEventListener('scroll', onScroll);
  });

  // 2.5) keep plugin in sync when viewport resizes (e.g., menu opens/closes)
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin) return;

    const resizeObserver = new ResizeObserver(() => {
      thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
    });

    resizeObserver.observe(vp);
    return () => resizeObserver.disconnect();
  });

  // 3) kick-start after document change
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin || !window) return;

    // push initial metrics
    thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
  });

  // 4) let plugin drive scroll – only after window is set, and only once
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin || !window) return;

    return thumbnailPlugin.onScrollTo(({ top, behavior }) => {
      vp.scrollTo({ top, behavior });
    });
  });

  const paddingY = $derived(thumbnailPlugin?.cfg.paddingY ?? 0);
  const totalHeight = $derived(window?.totalHeight ?? 0);
  const items = $derived(window?.items ?? []);
</script>

<div
  bind:this={viewportRef}
  style:overflow-y="auto"
  style:position="relative"
  style:padding-top="{paddingY}px"
  style:padding-bottom="{paddingY}px"
  style:height="100%"
  {...divProps}
>
  <div style:height="{totalHeight}px" style:position="relative">
    {#each items as meta (meta.pageIndex)}
      {@render children(meta)}
    {/each}
  </div>
</div>
