// packages/plugin-thumbnail/src/shared/components/thumbnails-pane.tsx
import { useEffect, useRef, useState, HTMLAttributes, CSSProperties, ReactNode } from '@framework';
import { ThumbMeta, WindowState } from '@embedpdf/plugin-thumbnail';
import { useThumbnailPlugin } from '../hooks';

type ThumbnailsProps = Omit<HTMLAttributes<HTMLDivElement>, 'style' | 'children'> & {
  style?: CSSProperties;
  children: (m: ThumbMeta) => ReactNode;
  /** @deprecated use scrollToThumb via capability or rely on autoScroll */
  selectedPage?: number;
  /** @deprecated behavior is now controlled by ThumbnailPluginConfig.scrollBehavior */
  scrollOptions?: ScrollIntoViewOptions;
};

export function ThumbnailsPane({ style, scrollOptions, selectedPage, ...props }: ThumbnailsProps) {
  const { plugin: thumbnailPlugin } = useThumbnailPlugin();
  const viewportRef = useRef<HTMLDivElement>(null);

  const [window, setWindow] = useState<WindowState | null>(null);

  // 1) subscribe once to window updates
  useEffect(() => thumbnailPlugin?.onWindow(setWindow), [thumbnailPlugin]);

  // 2) keep plugin in sync while the user scrolls
  useEffect(() => {
    const vp = viewportRef.current;
    if (!vp) return;
    const onScroll = () => thumbnailPlugin?.updateWindow(vp.scrollTop, vp.clientHeight);
    vp.addEventListener('scroll', onScroll);
    return () => vp.removeEventListener('scroll', onScroll);
  }, [thumbnailPlugin]);

  // 2.5) keep plugin in sync when viewport resizes (e.g., menu opens/closes)
  useEffect(() => {
    const vp = viewportRef.current;
    if (!vp || !thumbnailPlugin) return;

    const resizeObserver = new ResizeObserver(() => {
      thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
    });
    resizeObserver.observe(vp);

    return () => resizeObserver.disconnect();
  }, [thumbnailPlugin]);

  // 3) kick-start after document change
  useEffect(() => {
    const vp = viewportRef.current;
    if (!vp || !thumbnailPlugin) return;

    // push initial metrics
    thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
  }, [window, thumbnailPlugin]);

  // 4) let plugin drive scroll – only after window is set, and only once
  useEffect(() => {
    const vp = viewportRef.current;
    if (!vp || !thumbnailPlugin || !window) return;

    return thumbnailPlugin.onScrollTo(({ top, behavior }) => {
      vp.scrollTo({ top, behavior });
    });
  }, [thumbnailPlugin, !!window]); // Note: !!window to prevent re-subscription on window updates

  const paddingY = thumbnailPlugin?.cfg.paddingY ?? 0;

  return (
    <div
      ref={viewportRef}
      style={{
        overflowY: 'auto',
        position: 'relative',
        paddingTop: paddingY,
        paddingBottom: paddingY,
        ...style,
      }}
      {...props}
    >
      <div style={{ height: window?.totalHeight ?? 0, position: 'relative' }}>
        {window?.items.map((m) => props.children(m))}
      </div>
    </div>
  );
}

// packages/plugin-thumbnail/src/svelte/components/ThumbnailsPane.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import type { ThumbMeta, WindowState } from '@embedpdf/plugin-thumbnail';
  import { useThumbnailPlugin } from '../hooks';
  import type { HTMLAttributes } from 'svelte/elements';

  interface Props extends Omit<HTMLAttributes<HTMLDivElement>, 'children'> {
    children: Snippet<[ThumbMeta]>;
  }

  const { children, ...divProps }: Props = $props();

  const { plugin: thumbnailPlugin } = useThumbnailPlugin();

  let viewportRef: HTMLDivElement | undefined;
  let window = $state<WindowState | null>(null);

  // 1) subscribe once to window updates
  $effect(() => {
    if (!thumbnailPlugin) return;
    return thumbnailPlugin.onWindow((newWindow) => {
      window = newWindow;
    });
  });

  // 2) keep plugin in sync while the user scrolls
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin) return;

    const onScroll = () => {
      thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
    };

    vp.addEventListener('scroll', onScroll);
    return () => vp.removeEventListener('scroll', onScroll);
  });

  // 2.5) keep plugin in sync when viewport resizes (e.g., menu opens/closes)
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin) return;

    const resizeObserver = new ResizeObserver(() => {
      thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
    });

    resizeObserver.observe(vp);
    return () => resizeObserver.disconnect();
  });

  // 3) kick-start after document change
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin || !window) return;

    // push initial metrics
    thumbnailPlugin.updateWindow(vp.scrollTop, vp.clientHeight);
  });

  // 4) let plugin drive scroll – only after window is set, and only once
  $effect(() => {
    const vp = viewportRef;
    if (!vp || !thumbnailPlugin || !window) return;

    return thumbnailPlugin.onScrollTo(({ top, behavior }) => {
      vp.scrollTo({ top, behavior });
    });
  });

  const paddingY = $derived(thumbnailPlugin?.cfg.paddingY ?? 0);
  const totalHeight = $derived(window?.totalHeight ?? 0);
  const items = $derived(window?.items ?? []);
</script>

<div
  bind:this={viewportRef}
  style:overflow-y="auto"
  style:position="relative"
  style:padding-top="{paddingY}px"
  style:padding-bottom="{paddingY}px"
  style:height="100%"
  {...divProps}
>
  <div style:height="{totalHeight}px" style:position="relative">
    {#each items as meta (meta.pageIndex)}
      {@render children(meta)}
    {/each}
  </div>
</div>
