// examples/vue-tailwind/src/ui/SchemaModal.vue
<template>
  <component :is="modalContent" v-if="modalContent" />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import type { ModalSchema } from '@embedpdf/plugin-ui';
import { useItemRenderer } from '@embedpdf/plugin-ui/vue';

/**
 * Schema-driven Modal Renderer for Vue
 *
 * Renders modals defined in the UI schema.
 * Supports animation lifecycle via isOpen and onExited props.
 */

interface Props {
  schema: ModalSchema;
  documentId: string;
  isOpen: boolean;
  onClose: () => void;
  onExited: () => void;
}

const props = defineProps<Props>();

const { renderCustomComponent } = useItemRenderer();

const modalContent = computed(() => {
  const { content } = props.schema;

  if (content.type !== 'component') {
    console.warn(`SchemaModal only supports component content type, got: ${content.type}`);
    return null;
  }

  return renderCustomComponent(content.componentId, props.documentId, {
    isOpen: props.isOpen,
    onClose: props.onClose,
    onExited: props.onExited,
  });
});
</script>

// examples/svelte-tailwind/src/lib/ui/SchemaModal.svelte
<script lang="ts">
  import type { ModalRendererProps } from '@embedpdf/plugin-ui/svelte';
  import { useItemRenderer } from '@embedpdf/plugin-ui/svelte';

  /**
   * Schema-driven Modal Renderer for Svelte
   *
   * Renders modals defined in the UI schema.
   * Supports animation lifecycle via isOpen and onExited props.
   */

  interface Props extends ModalRendererProps {}

  let { schema, documentId, isOpen, onClose, onExited }: Props = $props();

  const { getCustomComponent } = useItemRenderer();

  const ModalComponent = $derived.by(() => {
    const { content } = schema;

    if (content.type !== 'component') {
      console.warn(`SchemaModal only supports component content type, got: ${content.type}`);
      return undefined;
    }

    return getCustomComponent(content.componentId);
  });
</script>

{#if ModalComponent}
  <ModalComponent {documentId} {isOpen} {onClose} {onExited} />
{/if}
