// packages/plugin-form/src/svelte/components/fill-mode/ComboboxFillMode.svelte
<script lang="ts">
  import type { PdfWidgetAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/svelte';
  import { useFormWidgetState } from '../../hooks/use-form-widget-state.svelte';
  import { useFormDocumentState } from '../../hooks/use-form.svelte';
  import RenderWidget from '../RenderWidget.svelte';
  import ComboboxField from '../fields/ComboboxField.svelte';
  import type { ComboboxFieldProps } from '../../../shared/components/types';

  let props: AnnotationRendererProps<PdfWidgetAnnoObject> = $props();
  const widgetState = useFormWidgetState(props);
  const formDocState = useFormDocumentState(() => props.documentId);
  const comboboxAnnotation = $derived(widgetState.annotation as ComboboxFieldProps['annotation']);

  let wrapperEl: HTMLDivElement;
  let selectEl: HTMLElement | null = null;

  const isFocused = $derived(formDocState.state.selectedFieldId === widgetState.annotation.id);

  $effect(() => {
    if (isFocused && selectEl && document.activeElement !== selectEl) {
      selectEl.focus();
    }
  });

  function handleFocus() {
    if (widgetState.isReadOnly) return;
    widgetState.scope?.selectField(widgetState.annotation.id);
  }

  function handleBlur() {
    requestAnimationFrame(() => {
      if (wrapperEl?.contains(document.activeElement)) return;
      if (widgetState.scope?.getSelectedFieldId() === widgetState.annotation.id) {
        widgetState.scope?.deselectField();
      }
    });
  }

  function selectInputRef(el: HTMLElement | null) {
    selectEl = el;
  }
</script>

<div
  bind:this={wrapperEl}
  style="width: 100%; height: 100%; overflow: hidden; position: relative; cursor: {widgetState.isReadOnly
    ? 'default'
    : 'pointer'}; pointer-events: auto; outline: {isFocused
    ? '2px solid rgba(66, 133, 244, 0.8)'
    : 'none'}; outline-offset: -2px;"
>
  <RenderWidget
    pageIndex={widgetState.pageIndex}
    annotation={widgetState.annotation}
    scaleFactor={widgetState.scale}
    renderKey={widgetState.renderKey}
    style="position: absolute; inset: 0; pointer-events: none;"
  />
  <ComboboxField
    annotation={comboboxAnnotation}
    scale={widgetState.scale}
    pageIndex={widgetState.pageIndex}
    isEditable={true}
    onChangeField={widgetState.handleChangeField}
    onFocus={handleFocus}
    onBlur={handleBlur}
    inputRef={selectInputRef}
  />
</div>

// packages/plugin-form/src/vue/components/fill-mode/combobox-fill-mode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { PdfWidgetAnnoObject } from '@embedpdf/models';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import RenderWidget from '../render-widget.vue';
import ComboboxField from '../fields/combobox-field.vue';
import type { ComboboxFieldProps } from '../../../shared/components/types';

const props = defineProps<AnnotationRendererProps<PdfWidgetAnnoObject>>();
const ws = useFormWidgetState(props);
const { state: formState } = useFormDocumentState(() => props.documentId);

const wrapperEl = ref<HTMLDivElement | null>(null);
const selectEl = ref<HTMLElement | null>(null);

const isFocused = computed(() => formState.value.selectedFieldId === ws.annotation.value.id);

watch(isFocused, (focused) => {
  if (focused && wrapperEl.value && !wrapperEl.value.contains(document.activeElement)) {
    (selectEl.value ?? wrapperEl.value).focus();
  }
});

function handleFocus() {
  ws.scope.value?.selectField(ws.annotation.value.id);
}

function handleBlur() {
  requestAnimationFrame(() => {
    if (wrapperEl.value?.contains(document.activeElement)) return;
    if (ws.scope.value?.getSelectedFieldId() === ws.annotation.value.id) {
      ws.scope.value?.deselectField();
    }
  });
}

function selectInputRef(el: HTMLElement | null) {
  selectEl.value = el;
}
</script>

<template>
  <div
    ref="wrapperEl"
    @focus="handleFocus"
    @blur="handleBlur"
    :style="{
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      cursor: ws.isReadOnly.value ? 'default' : 'pointer',
      pointerEvents: 'auto',
      outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
      outlineOffset: '-2px',
    }"
  >
    <RenderWidget
      :pageIndex="ws.pageIndex.value"
      :annotation="ws.annotation.value"
      :scaleFactor="ws.scale.value"
      :renderKey="ws.renderKey.value"
      :style="{ pointerEvents: 'none' }"
    />
    <ComboboxField
      :annotation="ws.annotation.value as ComboboxFieldProps['annotation']"
      :scale="ws.scale.value"
      :pageIndex="ws.pageIndex.value"
      :isEditable="true"
      :onChangeField="ws.handleChangeField"
      :inputRef="selectInputRef"
    />
  </div>
</template>
