// packages/plugin-form/src/svelte/components/fill-mode/ListboxFillMode.svelte
<script lang="ts">
  import type { PdfWidgetAnnoObject } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/svelte';
  import { useFormWidgetState } from '../../hooks/use-form-widget-state.svelte';
  import { useFormDocumentState } from '../../hooks/use-form.svelte';
  import RenderWidget from '../RenderWidget.svelte';
  import ListboxField from '../fields/ListboxField.svelte';
  import type { ListboxFieldProps } from '../../../shared/components/types';

  let props: AnnotationRendererProps<PdfWidgetAnnoObject> = $props();
  const widgetState = useFormWidgetState(props);
  const formDocState = useFormDocumentState(() => props.documentId);

  let editing = $state(false);
  let wrapperEl: HTMLDivElement;

  const isFocused = $derived(formDocState.state.selectedFieldId === widgetState.annotation.id);

  $effect(() => {
    if (isFocused && wrapperEl && !wrapperEl.contains(document.activeElement)) {
      wrapperEl.focus();
    }
  });

  function handleFocus() {
    if (widgetState.isReadOnly) return;
    widgetState.scope?.selectField(widgetState.annotation.id);
    editing = true;
  }

  function handleBlur() {
    requestAnimationFrame(() => {
      if (wrapperEl?.contains(document.activeElement)) return;
      editing = false;
      if (widgetState.scope?.getSelectedFieldId() === widgetState.annotation.id) {
        widgetState.scope?.deselectField();
      }
    });
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  bind:this={wrapperEl}
  tabindex={widgetState.isReadOnly ? -1 : 0}
  onfocus={handleFocus}
  onblur={handleBlur}
  style="width: 100%; height: 100%; overflow: hidden; cursor: {widgetState.isReadOnly
    ? 'default'
    : 'pointer'}; pointer-events: auto; outline: {isFocused && !editing
    ? '2px solid rgba(66, 133, 244, 0.8)'
    : 'none'}; outline-offset: -2px;"
>
  <ListboxField
    annotation={widgetState.annotation as ListboxFieldProps['annotation']}
    scale={widgetState.scale}
    pageIndex={widgetState.pageIndex}
    isEditable={true}
    onChangeField={widgetState.handleChangeField}
  />
  {#if !editing}
    <RenderWidget
      pageIndex={widgetState.pageIndex}
      annotation={widgetState.annotation}
      scaleFactor={widgetState.scale}
      renderKey={widgetState.renderKey}
      style="pointer-events: none;"
    />
  {/if}
</div>

// packages/plugin-form/src/vue/components/fill-mode/listbox-fill-mode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { PdfWidgetAnnoObject } from '@embedpdf/models';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import RenderWidget from '../render-widget.vue';
import ListboxField from '../fields/listbox-field.vue';
import type { ListboxFieldProps } from '../../../shared/components/types';

const props = defineProps<AnnotationRendererProps<PdfWidgetAnnoObject>>();
const ws = useFormWidgetState(props);
const { state: formState } = useFormDocumentState(() => props.documentId);

const editing = ref(false);
const wrapperEl = ref<HTMLDivElement | null>(null);

const isFocused = computed(() => formState.value.selectedFieldId === ws.annotation.value.id);

watch(isFocused, (focused) => {
  if (focused && wrapperEl.value && !wrapperEl.value.contains(document.activeElement)) {
    wrapperEl.value.focus();
  }
});

function handleFocus() {
  if (ws.isReadOnly.value) return;
  ws.scope.value?.selectField(ws.annotation.value.id);
  editing.value = true;
}

function handleBlur() {
  requestAnimationFrame(() => {
    if (wrapperEl.value?.contains(document.activeElement)) return;
    editing.value = false;
    if (ws.scope.value?.getSelectedFieldId() === ws.annotation.value.id) {
      ws.scope.value?.deselectField();
    }
  });
}
</script>

<template>
  <div
    ref="wrapperEl"
    :tabindex="ws.isReadOnly.value ? -1 : 0"
    @focus="handleFocus"
    @blur="handleBlur"
    :style="{
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      cursor: ws.isReadOnly.value ? 'default' : 'pointer',
      pointerEvents: 'auto',
      outline: isFocused && !editing ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
      outlineOffset: '-2px',
    }"
  >
    <ListboxField
      :annotation="ws.annotation.value as ListboxFieldProps['annotation']"
      :scale="ws.scale.value"
      :pageIndex="ws.pageIndex.value"
      :isEditable="true"
      :onChangeField="ws.handleChangeField"
    />
    <RenderWidget
      v-if="!editing"
      :pageIndex="ws.pageIndex.value"
      :annotation="ws.annotation.value"
      :scaleFactor="ws.scale.value"
      :renderKey="ws.renderKey.value"
      :style="{ pointerEvents: 'none' }"
    />
  </div>
</template>
