// packages/plugin-form/src/shared/components/fill-mode/toggle-fill-mode.tsx
import { useCallback, useEffect, useRef } from '@framework';
import { PdfWidgetAnnoObject, isWidgetChecked } from '@embedpdf/models';
import { AnnotationRendererProps } from '@embedpdf/plugin-annotation/@framework';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import { RenderWidget } from '../render-widget';

export function ToggleFillMode(props: AnnotationRendererProps<PdfWidgetAnnoObject>) {
  const { annotation, field, scale, pageIndex, scope, handleChangeField, renderKey, isReadOnly } =
    useFormWidgetState(props);
  const formState = useFormDocumentState(props.documentId);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const isFocused = formState.selectedFieldId === annotation.id;

  useEffect(() => {
    if (isFocused && wrapperRef.current && document.activeElement !== wrapperRef.current) {
      wrapperRef.current.focus();
    }
  }, [isFocused]);

  const toggle = useCallback(() => {
    if (isReadOnly) return;
    const checked = isWidgetChecked(annotation);
    const newValue = checked ? 'Off' : (annotation.exportValue ?? 'Yes');
    handleChangeField({ ...field, value: newValue });
  }, [isReadOnly, annotation, field, handleChangeField]);

  const handleClick = useCallback(() => {
    if (isReadOnly) return;
    scope?.selectField(annotation.id);
    toggle();
  }, [isReadOnly, scope, annotation.id, toggle]);

  const handleFocus = useCallback(() => {
    if (isReadOnly) return;
    scope?.selectField(annotation.id);
  }, [isReadOnly, scope, annotation.id]);

  const handleBlur = useCallback(() => {
    if (scope?.getSelectedFieldId() === annotation.id) {
      scope?.deselectField();
    }
  }, [scope, annotation.id]);

  const handleKeyDown = useCallback(
    (e: { key: string; preventDefault: () => void }) => {
      if (e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        toggle();
      }
    },
    [toggle],
  );

  return (
    <div
      ref={wrapperRef}
      tabIndex={isReadOnly ? -1 : 0}
      onClick={handleClick}
      onFocus={handleFocus}
      onBlur={handleBlur}
      onKeyDown={handleKeyDown}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        cursor: isReadOnly ? 'default' : 'pointer',
        pointerEvents: 'auto',
        outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
        outlineOffset: -2,
      }}
    >
      <RenderWidget
        pageIndex={pageIndex}
        annotation={annotation}
        scaleFactor={scale}
        renderKey={renderKey}
        style={{ pointerEvents: 'none' }}
      />
    </div>
  );
}

// packages/plugin-form/src/vue/components/fill-mode/toggle-fill-mode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { PdfWidgetAnnoObject } from '@embedpdf/models';
import { isWidgetChecked } from '@embedpdf/models';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import RenderWidget from '../render-widget.vue';

const props = defineProps<AnnotationRendererProps<PdfWidgetAnnoObject>>();
const ws = useFormWidgetState(props);
const { state: formState } = useFormDocumentState(() => props.documentId);

const wrapperEl = ref<HTMLDivElement | null>(null);

const isFocused = computed(() => formState.value.selectedFieldId === ws.annotation.value.id);

watch(isFocused, (focused) => {
  if (focused && wrapperEl.value && document.activeElement !== wrapperEl.value) {
    wrapperEl.value.focus();
  }
});

function toggle() {
  if (ws.isReadOnly.value) return;
  const checked = isWidgetChecked(ws.annotation.value);
  const newValue = checked ? 'Off' : (ws.annotation.value.exportValue ?? 'Yes');
  ws.handleChangeField({ ...ws.field.value, value: newValue });
}

function handleClick() {
  if (ws.isReadOnly.value) return;
  ws.scope.value?.selectField(ws.annotation.value.id);
  toggle();
}

function handleFocus() {
  if (ws.isReadOnly.value) return;
  ws.scope.value?.selectField(ws.annotation.value.id);
}

function handleBlur() {
  if (ws.scope.value?.getSelectedFieldId() === ws.annotation.value.id) {
    ws.scope.value?.deselectField();
  }
}

function handleKeyDown(e: KeyboardEvent) {
  if (e.key === ' ' || e.key === 'Enter') {
    e.preventDefault();
    toggle();
  }
}
</script>

<template>
  <div
    ref="wrapperEl"
    :tabindex="ws.isReadOnly.value ? -1 : 0"
    @click="handleClick"
    @focus="handleFocus"
    @blur="handleBlur"
    @keydown="handleKeyDown"
    :style="{
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      cursor: ws.isReadOnly.value ? 'default' : 'pointer',
      pointerEvents: 'auto',
      outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
      outlineOffset: '-2px',
    }"
  >
    <RenderWidget
      :pageIndex="ws.pageIndex.value"
      :annotation="ws.annotation.value"
      :scaleFactor="ws.scale.value"
      :renderKey="ws.renderKey.value"
      :style="{ pointerEvents: 'none' }"
    />
  </div>
</template>
