// examples/vue-vuetify/src/components/Application.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/vue';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/vue';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/vue';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate/vue';
import { Rotate } from '@embedpdf/plugin-rotate/vue';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/vue';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/vue';
import { PanPluginPackage } from '@embedpdf/plugin-pan/vue';
import { ExportPluginPackage } from '@embedpdf/plugin-export/vue';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/vue';
import { PrintPluginPackage } from '@embedpdf/plugin-print/vue';
import Toolbar from './Toolbar.vue';

const { engine, isLoading: engineLoading, error: engineError } = usePdfiumEngine();
</script>

<template>
  <!-- Loading state -->
  <div v-if="engineLoading" class="d-flex fill-height align-center justify-center">
    <div class="text-center">
      <v-progress-circular indeterminate color="primary" size="64"></v-progress-circular>
      <div class="text-body-1 text-medium-emphasis mt-4">Loading PDF engine...</div>
    </div>
  </div>

  <!-- Error state -->
  <div v-else-if="engineError" class="d-flex fill-height align-center justify-center">
    <v-alert type="error" variant="tonal" class="ma-4">
      <v-alert-title>Error</v-alert-title>
      {{ engineError.message }}
    </v-alert>
  </div>

  <!-- Main application -->
  <div v-else-if="engine" class="fill-height">
    <EmbedPDF
      :engine="engine"
      :plugins="[
        createPluginRegistration(LoaderPluginPackage, {
          loadingOptions: {
            type: 'url',
            pdfFile: {
              id: 'sample-pdf',
              name: 'embedpdf-ebook.pdf',
              url: 'https://snippet.embedpdf.com/ebook.pdf',
            },
          },
        }),
        createPluginRegistration(ViewportPluginPackage, {
          viewportGap: 10,
        }),
        createPluginRegistration(ScrollPluginPackage, {
          strategy: ScrollStrategy.Vertical,
          pageGap: 10,
        }),
        createPluginRegistration(RenderPluginPackage),
        createPluginRegistration(TilingPluginPackage, {
          tileSize: 768,
          overlapPx: 2.5,
          extraRings: 0,
        }),
        createPluginRegistration(InteractionManagerPluginPackage),
        createPluginRegistration(SelectionPluginPackage),
        createPluginRegistration(RotatePluginPackage),
        createPluginRegistration(FullscreenPluginPackage),
        createPluginRegistration(ZoomPluginPackage, {
          defaultZoomLevel: ZoomMode.FitPage,
        }),
        createPluginRegistration(PanPluginPackage),
        createPluginRegistration(ExportPluginPackage),
        createPluginRegistration(SpreadPluginPackage),
        createPluginRegistration(PrintPluginPackage),
      ]"
    >
      <template #default="{ pluginsReady }">
        <v-layout class="fill-height" id="pdf-app-layout">
          <!-- Toolbar -->
          <Toolbar />

          <!-- Main content -->
          <v-main class="fill-height">
            <div class="fill-height position-relative">
              <GlobalPointerProvider>
                <Viewport class="fill-height" style="background-color: #f5f5f5; overflow: auto">
                  <div v-if="!pluginsReady" class="d-flex fill-height align-center justify-center">
                    <div class="text-center">
                      <v-progress-circular
                        indeterminate
                        color="primary"
                        size="48"
                      ></v-progress-circular>
                      <div class="text-body-1 text-medium-emphasis mt-4">Loading plugins...</div>
                    </div>
                  </div>
                  <Scroller v-else>
                    <template #default="{ page }">
                      <Rotate :page-size="{ width: page.width, height: page.height }">
                        <PagePointerProvider
                          :page-index="page.pageIndex"
                          :page-width="page.width"
                          :page-height="page.height"
                          :rotation="page.rotation"
                          :scale="page.scale"
                          class="position-absolute"
                          :style="{
                            width: page.width + 'px',
                            height: page.height + 'px',
                          }"
                        >
                          <RenderLayer :page-index="page.pageIndex" style="pointer-events: none" />
                          <TilingLayer
                            :page-index="page.pageIndex"
                            :scale="page.scale"
                            style="pointer-events: none"
                          />
                          <SelectionLayer :page-index="page.pageIndex" :scale="page.scale" />
                        </PagePointerProvider>
                      </Rotate>
                    </template>
                  </Scroller>
                  <!-- Page Controls Overlay -->
                  <PageControls />
                </Viewport>
              </GlobalPointerProvider>
            </div>
          </v-main>
        </v-layout>
      </template>
    </EmbedPDF>
  </div>

  <!-- Engine not ready state -->
  <div v-else class="d-flex fill-height align-center justify-center">
    <div class="text-body-1 text-medium-emphasis text-center">Engine not ready</div>
  </div>
</template>

<style scoped>
#pdf-app-layout {
  user-select: none;
}
.flex-1-1-100 {
  flex: 1 1 100%;
}
</style>

// examples/react-tailwind/src/application.tsx
import { useRef } from 'react';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/react';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom/react';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/react';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan/react';
import { ViewportPluginPackage, Viewport } from '@embedpdf/plugin-viewport/react';
import { ScrollPluginPackage, ScrollStrategy, Scroller } from '@embedpdf/plugin-scroll/react';
import { TilingPluginPackage, TilingLayer } from '@embedpdf/plugin-tiling/react';
import { RotatePluginPackage, Rotate } from '@embedpdf/plugin-rotate/react';
import { RenderPluginPackage, RenderLayer } from '@embedpdf/plugin-render/react';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/react';
import { SelectionPluginPackage, SelectionLayer } from '@embedpdf/plugin-selection/react';

export default function DocumentViewer() {
  const containerRef = useRef<HTMLDivElement>(null);
  const { engine, isLoading, error } = usePdfiumEngine();

  if (error) {
    return <div>Error: {error.message}</div>;
  }

  if (isLoading || !engine) {
    return <div>Loading...</div>;
  }

  return (
    <div className="flex h-screen flex-1 flex-col overflow-hidden" ref={containerRef}>
      <div className="flex flex-1 overflow-hidden">
        <EmbedPDF
          engine={engine}
          plugins={[
            createPluginRegistration(LoaderPluginPackage, {
              loadingOptions: {
                type: 'url',
                pdfFile: {
                  id: '1',
                  url: 'https://snippet.embedpdf.com/ebook.pdf',
                },
                options: {
                  mode: 'full-fetch',
                },
              },
            }),
            createPluginRegistration(ViewportPluginPackage, {
              viewportGap: 10,
            }),
            createPluginRegistration(ScrollPluginPackage, {
              strategy: ScrollStrategy.Vertical,
            }),
            createPluginRegistration(RenderPluginPackage),
            createPluginRegistration(TilingPluginPackage, {
              tileSize: 768,
              overlapPx: 2.5,
              extraRings: 0,
            }),
            createPluginRegistration(ZoomPluginPackage, {
              defaultZoomLevel: ZoomMode.FitPage,
            }),
            createPluginRegistration(RotatePluginPackage),
            createPluginRegistration(SpreadPluginPackage),
            createPluginRegistration(FullscreenPluginPackage),
            createPluginRegistration(ExportPluginPackage),
            createPluginRegistration(InteractionManagerPluginPackage),
            createPluginRegistration(SelectionPluginPackage),
            createPluginRegistration(PanPluginPackage),
            createPluginRegistration(ThumbnailPluginPackage),
          ]}
        >
          {({ pluginsReady }) => (
            <GlobalPointerProvider>
              <Viewport className="h-full w-full flex-1 select-none overflow-auto bg-gray-100">
                {pluginsReady ? (
                  <Scroller
                    renderPage={({
                      pageIndex,
                      scale,
                      width,
                      height,
                      document,
                      rotation,
                      rotatedWidth,
                      rotatedHeight,
                    }) => (
                      <Rotate key={document?.id} pageSize={{ width, height }}>
                        <PagePointerProvider
                          rotation={rotation}
                          scale={scale}
                          pageWidth={rotatedWidth}
                          pageHeight={rotatedHeight}
                          pageIndex={pageIndex}
                          style={{
                            width,
                            height,
                          }}
                        >
                          <RenderLayer pageIndex={pageIndex} className="pointer-events-none" />
                          <TilingLayer
                            pageIndex={pageIndex}
                            scale={scale}
                            className="pointer-events-none"
                          />
                          <SelectionLayer pageIndex={pageIndex} scale={scale} />
                        </PagePointerProvider>
                      </Rotate>
                    )}
                  />
                ) : (
                  <div>Loading plugins...</div>
                )}
              </Viewport>
            </GlobalPointerProvider>
          )}
        </EmbedPDF>
      </div>
    </div>
  );
}
