// packages/plugin-form/src/vue/components/previews/checkbox-preview.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Rect } from '@embedpdf/models';
import type { WidgetPreviewData } from '../types';

const props = defineProps<{
  data: WidgetPreviewData;
  bounds: Rect;
  scale: number;
}>();

const style = computed(() => ({
  position: 'absolute' as const,
  left: 0,
  top: 0,
  width: `${props.bounds.size.width * props.scale}px`,
  height: `${props.bounds.size.height * props.scale}px`,
  border: '1px dashed rgba(66, 133, 244, 0.6)',
  backgroundColor: 'rgba(255, 255, 255, 0.9)',
  boxSizing: 'border-box' as const,
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
}));
</script>

<template>
  <div :style="style" />
</template>

// packages/plugin-form/src/svelte/components/previews/CheckboxPreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  let { bounds, scale }: { data: unknown; bounds: Rect; scale: number } = $props();
</script>

<div
  style:position="absolute"
  style:left="0"
  style:top="0"
  style:width="{bounds.size.width * scale}px"
  style:height="{bounds.size.height * scale}px"
  style:border="1px dashed rgba(66, 133, 244, 0.6)"
  style:background-color="rgba(255, 255, 255, 0.9)"
  style:box-sizing="border-box"
  style:display="flex"
  style:align-items="center"
  style:justify-content="center"
></div>
