// packages/plugin-viewport/src/preact/components/viewport.tsx
/** @jsxImportSource preact */
import { ComponentChildren, JSX } from 'preact';
import { useEffect, useState } from 'preact/hooks';

import { useViewportCapability } from '../hooks';
import { useViewportRef } from '../hooks/use-viewport-ref';

type ViewportProps = JSX.HTMLAttributes<HTMLDivElement> & {
  children: ComponentChildren;
};

export function Viewport({ children, ...props }: ViewportProps) {
  const [viewportGap, setViewportGap] = useState(0);
  const viewportRef = useViewportRef();
  const { provides: viewportProvides } = useViewportCapability();

  useEffect(() => {
    if (viewportProvides) {
      setViewportGap(viewportProvides.getViewportGap());
    }
  }, [viewportProvides]);

  const { style, ...restProps } = props;
  return (
    <div
      {...restProps}
      ref={viewportRef}
      style={{
        ...(typeof style === 'object' ? style : {}),
        padding: `${viewportGap}px`,
      }}
    >
      {children}
    </div>
  );
}

// packages/plugin-viewport/src/svelte/components/Viewport.svelte
<script lang="ts">
    import {useViewportCapability, useViewportRef} from '../hooks';
    import type {HTMLAttributes} from 'svelte/elements';
    import type {Snippet} from 'svelte';

    type ViewportProps = HTMLAttributes<HTMLDivElement> & {
    children: Snippet;
    class?: string;
  };

  let { children, class: propsClass, ...restProps }: ViewportProps = $props();

  let viewportGap = $state(0);

  let viewportRef = useViewportRef();

  const {provides} = useViewportCapability();

  $effect(() => {
    if (provides) {
      viewportGap = provides.getViewportGap();
    }
  });
</script>

<div
  {...restProps}
  bind:this={viewportRef.ref}
  style:width="100%"
  style:height="100%"
  style:overflow="auto"
  style:padding={`${viewportGap}px`}
  class={propsClass}
>
  {@render children()}
</div>
