// packages/plugin-redaction/src/shared/components/marquee-redact.tsx
import { useEffect, useState } from '@framework';
import { useDocumentState } from '@embedpdf/core/@framework';
import { Rect } from '@embedpdf/models';

import { useRedactionPlugin } from '../hooks/use-redaction';

interface MarqueeRedactProps {
  /** The ID of the document */
  documentId: string;
  /** Index of the page this layer lives on */
  pageIndex: number;
  /** Scale of the page */
  scale?: number;
  /** Optional CSS class applied to the marquee rectangle */
  className?: string;
  /** Stroke / fill colours (defaults below) */
  stroke?: string;
  fill?: string;
}

export const MarqueeRedact = ({
  documentId,
  pageIndex,
  scale: scaleOverride,
  className,
  stroke,
  fill = 'transparent',
}: MarqueeRedactProps) => {
  const { plugin: redactionPlugin } = useRedactionPlugin();
  const documentState = useDocumentState(documentId);

  const [rect, setRect] = useState<Rect | null>(null);

  const scale = scaleOverride ?? documentState?.scale ?? 1;

  // Get stroke color from plugin (annotation mode uses tool defaults, legacy uses red)
  // Allow prop override for backwards compatibility
  const strokeColor = stroke ?? redactionPlugin?.getPreviewStrokeColor() ?? 'red';

  useEffect(() => {
    if (!redactionPlugin || !documentId) return;
    return redactionPlugin.onRedactionMarqueeChange(documentId, (data) => {
      setRect(data.pageIndex === pageIndex ? data.rect : null);
    });
  }, [redactionPlugin, documentId, pageIndex]);

  if (!rect) return null;

  return (
    <div
      style={{
        position: 'absolute',
        pointerEvents: 'none',
        left: rect.origin.x * scale,
        top: rect.origin.y * scale,
        width: rect.size.width * scale,
        height: rect.size.height * scale,
        border: `1px solid ${strokeColor}`,
        background: fill,
        boxSizing: 'border-box',
      }}
      className={className}
    />
  );
};

// packages/plugin-redaction/src/svelte/components/marquee-redact.svelte
<script lang="ts">
  import { useDocumentState } from '@embedpdf/core/svelte';
  import type { Rect } from '@embedpdf/models';
  import { useRedactionPlugin } from '../hooks/use-redaction.svelte';

  interface MarqueeRedactProps {
    /** The ID of the document */
    documentId: string;
    /** Index of the page this layer lives on */
    pageIndex: number;
    /** Scale of the page */
    scale?: number;
    /** Optional CSS class applied to the marquee rectangle */
    className?: string;
    /** Stroke / fill colours (defaults below) */
    stroke?: string;
    fill?: string;
  }

  let {
    documentId,
    pageIndex,
    scale: scaleOverride,
    className = '',
    stroke,
    fill = 'transparent',
  }: MarqueeRedactProps = $props();

  const redactionPlugin = useRedactionPlugin();
  const documentState = useDocumentState(() => documentId);
  let rect = $state<Rect | null>(null);

  const actualScale = $derived(
    scaleOverride !== undefined ? scaleOverride : (documentState.current?.scale ?? 1),
  );

  // Get stroke color from plugin (annotation mode uses tool defaults, legacy uses red)
  // Allow prop override for backwards compatibility
  const strokeColor = $derived(stroke ?? redactionPlugin.plugin?.getPreviewStrokeColor() ?? 'red');

  $effect(() => {
    if (!redactionPlugin.plugin || !documentId) {
      rect = null;
      return;
    }

    return redactionPlugin.plugin.onRedactionMarqueeChange(documentId, (data) => {
      rect = data.pageIndex === pageIndex ? data.rect : null;
    });
  });
</script>

{#if rect}
  <div
    class={className}
    style:position="absolute"
    style:pointer-events="none"
    style:left={`${rect.origin.x * actualScale}px`}
    style:top={`${rect.origin.y * actualScale}px`}
    style:width={`${rect.size.width * actualScale}px`}
    style:height={`${rect.size.height * actualScale}px`}
    style:border={`1px solid ${strokeColor}`}
    style:background={fill}
    style:box-sizing="border-box"
  ></div>
{/if}
