// packages/plugin-selection/src/shared/components/selection-layer.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from '@framework';
import { ignore, PdfErrorCode, PdfPageGeometry, Position, Rect } from '@embedpdf/models';
import {
  useCursor,
  useInteractionManagerCapability,
  usePointerHandlers,
} from '@embedpdf/plugin-interaction-manager/@framework';
import { PointerEventHandlersWithLifecycle } from '@embedpdf/plugin-interaction-manager';
import { glyphAt } from '@embedpdf/plugin-selection';

import { useSelectionCapability } from '../hooks';

type Props = {
  pageIndex: number;
  scale: number;
  background?: string;
};

export function SelectionLayer({ pageIndex, scale, background = 'rgba(33,150,243)' }: Props) {
  const { provides: sel } = useSelectionCapability();
  const { provides: im } = useInteractionManagerCapability();
  const { register } = usePointerHandlers({ pageIndex });
  const [rects, setRects] = useState<Array<Rect>>([]);
  const [boundingRect, setBoundingRect] = useState<Rect | null>(null);
  const { setCursor, removeCursor } = useCursor();
  const geoCacheRef = useRef<PdfPageGeometry | null>(null);

  /* subscribe to rect updates */
  useEffect(() => {
    if (!sel) return;
    return sel.onSelectionChange(() => {
      const mode = im?.getActiveMode();
      if (mode === 'pointerMode') {
        setRects(sel.getHighlightRectsForPage(pageIndex));
        setBoundingRect(sel.getBoundingRectForPage(pageIndex));
      } else {
        setRects([]);
        setBoundingRect(null);
      }
    });
  }, [sel, pageIndex]);

  /* cheap glyphAt cache for the active page */
  const cachedGlyphAt = useCallback((pt: Position) => {
    const geo = geoCacheRef.current;
    return geo ? glyphAt(geo, pt) : -1;
  }, []);

  // Initialize geometry cache
  useEffect(() => {
    if (!sel) return;
    const task = sel.getGeometry(pageIndex);
    task.wait((g) => (geoCacheRef.current = g), ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'Cancelled',
      });
      geoCacheRef.current = null;
    };
  }, [sel, pageIndex]);

  const handlers = useMemo(
    (): PointerEventHandlersWithLifecycle<PointerEvent> => ({
      onPointerDown: (point, _evt, modeId) => {
        if (!sel) return;
        if (!sel.isEnabledForMode(modeId)) return;
        // clear the selection
        sel.clear();
        const task = sel.getGeometry(pageIndex);
        task.wait((geo) => {
          const g = glyphAt(geo, point);
          if (g !== -1) sel.begin(pageIndex, g);
        }, ignore);
      },
      onPointerMove: (point, _evt, modeId) => {
        if (!sel) return;
        if (!sel.isEnabledForMode(modeId)) return;
        const g = cachedGlyphAt(point);
        if (g !== -1) {
          setCursor('selection-text', 'text', 10);
        } else {
          removeCursor('selection-text');
        }
        if (g !== -1) sel.update(pageIndex, g);
      },
      onPointerUp: (_point, _evt, modeId) => {
        if (!sel) return;
        if (!sel.isEnabledForMode(modeId)) return;
        sel.end();
      },
      onHandlerActiveEnd(modeId) {
        if (!sel) return;
        if (!sel.isEnabledForMode(modeId)) return;

        sel.clear();
      },
    }),
    [sel, pageIndex, cachedGlyphAt],
  );

  useEffect(() => {
    if (!register) return;
    return register(handlers);
  }, [register, handlers]);

  if (!boundingRect) return null;

  return (
    <div
      style={{
        position: 'absolute',
        left: boundingRect.origin.x * scale,
        top: boundingRect.origin.y * scale,
        width: boundingRect.size.width * scale,
        height: boundingRect.size.height * scale,
        mixBlendMode: 'multiply',
        isolation: 'isolate',
      }}
    >
      {rects.map((b, i) => (
        <div
          key={i}
          style={{
            position: 'absolute',
            left: (b.origin.x - boundingRect.origin.x) * scale,
            top: (b.origin.y - boundingRect.origin.y) * scale,
            width: b.size.width * scale,
            height: b.size.height * scale,
            background,
            pointerEvents: 'none',
          }}
        />
      ))}
    </div>
  );
}

// packages/plugin-selection/src/vue/components/selection-layer.vue
<script setup lang="ts">
import { ref, watchEffect, computed } from 'vue';
import { ignore, PdfErrorCode, PdfPageGeometry, Rect } from '@embedpdf/models';
import {
  useCursor,
  useInteractionManagerCapability,
  usePointerHandlers,
} from '@embedpdf/plugin-interaction-manager/vue';
import { PointerEventHandlersWithLifecycle } from '@embedpdf/plugin-interaction-manager';
import { glyphAt } from '@embedpdf/plugin-selection';
import { useSelectionCapability } from '../hooks';

interface Props {
  pageIndex: number;
  scale: number;
  background?: string;
}

const props = withDefaults(defineProps<Props>(), {
  background: 'rgba(33, 150, 243)', // Default selection color
});

const { provides: sel } = useSelectionCapability();
const { provides: im } = useInteractionManagerCapability();
const { register } = usePointerHandlers({ pageIndex: props.pageIndex });
const { setCursor, removeCursor } = useCursor();

const rects = ref<Rect[]>([]);
const boundingRect = ref<Rect | null>(null);

// Subscribe to selection changes and update the rendered rectangles
watchEffect((onCleanup) => {
  if (sel.value) {
    const unsubscribe = sel.value.onSelectionChange(() => {
      const mode = im.value?.getActiveMode();
      if (mode === 'pointerMode') {
        rects.value = sel.value!.getHighlightRectsForPage(props.pageIndex);
        boundingRect.value = sel.value!.getBoundingRectForPage(props.pageIndex);
      } else {
        rects.value = [];
        boundingRect.value = null;
      }
    });
    onCleanup(unsubscribe);
  }
});

// Cache page geometry for faster hit-testing during pointer moves
let geoCache: PdfPageGeometry | undefined;
watchEffect((onCleanup) => {
  if (sel.value) {
    const task = sel.value.getGeometry(props.pageIndex);
    task.wait((g) => (geoCache = g), ignore);

    onCleanup(() => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'SelectionLayer unmounted',
      });
    });
  }
});

const handlers = computed(
  (): PointerEventHandlersWithLifecycle<PointerEvent> => ({
    onPointerDown: (point, _evt, modeId) => {
      if (!sel.value || !sel.value.isEnabledForMode(modeId)) return;
      sel.value.clear();
      const task = sel.value.getGeometry(props.pageIndex);
      task.wait((geo) => {
        const g = glyphAt(geo, point);
        if (g !== -1) sel.value!.begin(props.pageIndex, g);
      }, ignore);
    },
    onPointerMove: (point, _evt, modeId) => {
      if (!sel.value || !sel.value.isEnabledForMode(modeId)) return;
      const g = geoCache ? glyphAt(geoCache, point) : -1;
      if (g !== -1) {
        setCursor('selection-text', 'text', 10);
        sel.value.update(props.pageIndex, g);
      } else {
        removeCursor('selection-text');
      }
    },
    onPointerUp: (_point, _evt, modeId) => {
      if (!sel.value || !sel.value.isEnabledForMode(modeId)) return;
      sel.value.end();
    },
    onHandlerActiveEnd: (modeId) => {
      if (!sel.value || !sel.value.isEnabledForMode(modeId)) return;
      sel.value.clear();
    },
  }),
);

// Register the pointer handlers with the interaction manager
watchEffect((onCleanup) => {
  if (register) {
    const cleanup = register(handlers.value);
    if (cleanup) onCleanup(cleanup);
  }
});
</script>

<template>
  <div
    v-if="boundingRect"
    :style="{
      position: 'absolute',
      left: `${boundingRect.origin.x * scale}px`,
      top: `${boundingRect.origin.y * scale}px`,
      width: `${boundingRect.size.width * scale}px`,
      height: `${boundingRect.size.height * scale}px`,
      mixBlendMode: 'multiply',
      isolation: 'isolate',
      pointerEvents: 'none',
    }"
  >
    <div
      v-for="(rect, i) in rects"
      :key="i"
      :style="{
        position: 'absolute',
        left: `${(rect.origin.x - boundingRect.origin.x) * scale}px`,
        top: `${(rect.origin.y - boundingRect.origin.y) * scale}px`,
        width: `${rect.size.width * scale}px`,
        height: `${rect.size.height * scale}px`,
        background: background,
      }"
    />
  </div>
</template>
