// viewers/snippet/src/components/command-button.tsx
import { h, Fragment } from 'preact';
import { useCommand } from '@embedpdf/plugin-commands/preact';
import { useRegisterAnchor } from '@embedpdf/plugin-ui/preact';
import { twMerge } from 'tailwind-merge';
import { Button } from './ui/button';
import { Tooltip } from './ui/tooltip';
import { Icon } from './ui/icon';

type CommandButtonProps = {
  commandId: string;
  documentId: string;
  variant?: 'icon' | 'text' | 'icon-text' | 'tab';
  itemId?: string; // Unique ID for this button instance (for anchor registry)
  className?: string;
};

/**
 * A button that executes a command when clicked.
 * Uses the useCommand hook to get the command state and execution function.
 */
export function CommandButton({
  commandId,
  documentId,
  variant = 'icon',
  itemId,
  className,
}: CommandButtonProps) {
  const command = useCommand(commandId, documentId);
  // Register this button with the anchor registry if itemId is provided
  const finalItemId = itemId || commandId;
  const anchorRef = useRegisterAnchor(documentId, finalItemId);

  if (!command || !command.visible) return null;

  const iconProps = command.iconProps || {};

  const handleClick = () => {
    if (!command.disabled) {
      command.execute();
    }
  };

  return (
    <Tooltip
      content={command.label}
      position="bottom"
      delay={500}
      trigger={command.active || command.disabled ? 'none' : 'hover'}
    >
      <Button
        elementRef={anchorRef}
        onClick={handleClick}
        active={command.active}
        disabled={command.disabled}
        className={className || 'p-1'}
        aria-label={command.label}
      >
        {variant === 'text' ? (
          <span className="text-sm">{command.label}</span>
        ) : variant === 'icon-text' ? (
          <>
            {command.icon && (
              <Icon
                icon={command.icon}
                className="mr-2 h-5 w-5"
                primaryColor={iconProps.primaryColor}
                secondaryColor={iconProps.secondaryColor}
              />
            )}
            <span>{command.label}</span>
          </>
        ) : variant === 'tab' ? (
          <span className="px-3 py-1">{command.label}</span>
        ) : command.icon ? (
          <Icon
            icon={command.icon}
            className={twMerge('h-5 w-5', iconProps.className)}
            primaryColor={iconProps.primaryColor}
            secondaryColor={iconProps.secondaryColor}
          />
        ) : (
          <span>{command.label}</span>
        )}
      </Button>
    </Tooltip>
  );
}

// examples/vue-tailwind/src/components/CommandButton.vue
<template>
  <ToolbarButton
    :ref="anchorRef"
    @click="handleClick"
    :isActive="command?.active"
    :disabled="command?.disabled || !command?.visible"
    :aria-label="command?.label"
    :title="command?.label"
    :class="className"
  >
    <template v-if="variant === 'text'">
      <span class="text-sm">{{ command?.label }}</span>
    </template>
    <template v-else-if="variant === 'icon-text'">
      <component
        v-if="IconComponent"
        :is="IconComponent"
        :class="twMerge('mr-2 h-5 w-5', iconProps.className)"
        :title="command?.label"
        :style="{ color: iconProps.primaryColor }"
      />
      <span>{{ command?.label }}</span>
    </template>
    <template v-else-if="variant === 'tab'">
      <span class="px-3 py-1">{{ command?.label }}</span>
    </template>
    <template v-else>
      <!-- Default: icon only -->
      <component
        v-if="IconComponent"
        :is="IconComponent"
        :class="twMerge('h-5 w-5', iconProps.className)"
        :title="command?.label"
        :style="{
          color: iconProps.primaryColor,
          fill: iconProps.secondaryColor,
        }"
      />
      <span v-else>{{ command?.label }}</span>
    </template>
  </ToolbarButton>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useCommand } from '@embedpdf/plugin-commands/vue';
import { useRegisterAnchor } from '@embedpdf/plugin-ui/vue';
import { twMerge } from 'tailwind-merge';
import ToolbarButton from './ui/ToolbarButton.vue';
import * as Icons from './icons';

/**
 * A button that executes a command when clicked.
 * Uses the useCommand hook to get the command state and execution function.
 * The icon is automatically retrieved from the command definition.
 *
 * Automatically registers itself with the anchor registry so menus can anchor to it.
 */

interface Props {
  commandId: string;
  documentId: string;
  variant?: 'icon' | 'text' | 'icon-text' | 'tab';
  itemId?: string; // Unique ID for this button instance (for anchor registry)
  className?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'icon',
  itemId: undefined,
  className: undefined,
});

const command = useCommand(
  () => props.commandId,
  () => props.documentId,
);

// Register this button with the anchor registry if itemId is provided
// This allows menus to anchor to it when opened via UI state changes
const finalItemId = computed(() => props.itemId || props.commandId);
const anchorRef = useRegisterAnchor(() => props.documentId, finalItemId);

// Get the icon component from the command's icon property
const iconName = computed(() => (command.value?.icon ? `${command.value.icon}Icon` : null));
const IconComponent = computed(() => {
  if (!iconName.value) return null;
  return (Icons as any)[iconName.value];
});

// Get iconProps if available (for dynamic colors, etc.)
const iconProps = computed(() => command.value?.iconProps || {});

const handleClick = () => {
  if (command.value) {
    command.value.execute();
  }
};
</script>
