// packages/plugin-form/src/shared/components/render-widget.tsx
import { Fragment, HTMLAttributes, CSSProperties, useEffect, useRef, useState } from '@framework';
import { ignore, PdfErrorCode, PdfWidgetAnnoObject } from '@embedpdf/models';

import { useFormCapability } from '../hooks/use-form';

type RenderWidgetProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  pageIndex: number;
  annotation: PdfWidgetAnnoObject;
  scaleFactor?: number;
  dpr?: number;
  renderKey?: number;
  style?: CSSProperties;
};

export function RenderWidget({
  pageIndex,
  annotation,
  scaleFactor = 1,
  renderKey = 0,
  style,
  ...props
}: RenderWidgetProps) {
  const { provides: formProvides } = useFormCapability();
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);

  const { width, height } = annotation.rect.size;

  useEffect(() => {
    if (!formProvides) return;

    const task = formProvides.renderWidget({
      pageIndex,
      annotation,
      options: {
        scaleFactor,
        dpr: window.devicePixelRatio,
      },
    });

    task.wait((blob) => {
      const url = URL.createObjectURL(blob);
      if (urlRef.current) {
        URL.revokeObjectURL(urlRef.current);
      }
      urlRef.current = url;
      setImageUrl(url);
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
    };
  }, [pageIndex, scaleFactor, formProvides, annotation.id, width, height, renderKey]);

  useEffect(() => {
    return () => {
      if (urlRef.current) {
        URL.revokeObjectURL(urlRef.current);
        urlRef.current = null;
      }
    };
  }, []);

  return (
    <Fragment>
      {imageUrl && (
        <img
          src={imageUrl}
          {...props}
          style={{
            width: '100%',
            height: '100%',
            display: 'block',
            ...(style || {}),
          }}
        />
      )}
    </Fragment>
  );
}

// packages/plugin-form/src/svelte/components/RenderWidget.svelte
<script lang="ts">
  import type { PdfWidgetAnnoObject } from '@embedpdf/models';
  import { ignore, PdfErrorCode } from '@embedpdf/models';
  import { useFormCapability } from '../hooks/use-form.svelte';
  import { deepToRaw } from '@embedpdf/utils/svelte';

  interface RenderWidgetProps {
    pageIndex: number;
    annotation: PdfWidgetAnnoObject;
    scaleFactor?: number;
    renderKey?: number;
    style?: string;
  }

  let {
    pageIndex,
    annotation,
    scaleFactor = 1,
    renderKey = 0,
    style = '',
  }: RenderWidgetProps = $props();

  const formCapability = useFormCapability();
  let imageUrl = $state<string | null>(null);
  let prevUrl: string | null = null;

  $effect(() => {
    if (!formCapability.provides) return;

    const { width, height } = annotation.rect.size;
    const id = annotation.id;
    const sf = scaleFactor;
    const rk = renderKey;
    const pi = pageIndex;

    const task = formCapability.provides.renderWidget({
      pageIndex: pi,
      annotation: deepToRaw(annotation),
      options: {
        scaleFactor: sf,
        dpr: window.devicePixelRatio,
      },
    });

    task.wait((blob) => {
      const url = URL.createObjectURL(blob);
      if (prevUrl) {
        URL.revokeObjectURL(prevUrl);
      }
      prevUrl = url;
      imageUrl = url;
    }, ignore);

    return () => {
      task.abort({
        code: PdfErrorCode.Cancelled,
        message: 'canceled render task',
      });
      if (prevUrl) {
        URL.revokeObjectURL(prevUrl);
        prevUrl = null;
      }
    };
  });
</script>

{#if imageUrl}
  <img src={imageUrl} alt="" style="width: 100%; height: 100%; display: block; {style}" />
{/if}
