// examples/react-mui/src/application.tsx
import { createPluginRegistration } from '@embedpdf/core';
import { EmbedPDF } from '@embedpdf/core/react';
import { usePdfiumEngine } from '@embedpdf/engines/react';
import { ViewportPluginPackage } from '@embedpdf/plugin-viewport';
import { Viewport } from '@embedpdf/plugin-viewport/react';
import { ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll';
import { Scroller } from '@embedpdf/plugin-scroll/react';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader';
import { FilePicker } from '@embedpdf/plugin-loader/react';
import { RenderPluginPackage } from '@embedpdf/plugin-render';
import { RenderLayer } from '@embedpdf/plugin-render/react';
import { TilingPluginPackage } from '@embedpdf/plugin-tiling';
import { TilingLayer } from '@embedpdf/plugin-tiling/react';
import { ZoomMode, ZoomPluginPackage } from '@embedpdf/plugin-zoom';
import { MarqueeZoom } from '@embedpdf/plugin-zoom/react';
import { SearchPluginPackage } from '@embedpdf/plugin-search';
import { SearchLayer } from '@embedpdf/plugin-search/react';
import { InteractionManagerPluginPackage } from '@embedpdf/plugin-interaction-manager';
import {
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/react';
import { PanPluginPackage } from '@embedpdf/plugin-pan';
import { PanMode } from '@embedpdf/plugin-pan/react';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate';
import { Rotate } from '@embedpdf/plugin-rotate/react';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen';
import { FullscreenProvider } from '@embedpdf/plugin-fullscreen/react';
import { ExportPluginPackage } from '@embedpdf/plugin-export';
import { Download } from '@embedpdf/plugin-export/react';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail';
import { SelectionPluginPackage } from '@embedpdf/plugin-selection';
import { SelectionLayer } from '@embedpdf/plugin-selection/react';

import { CircularProgress, Box, Alert } from '@mui/material';
import SearchOutlinedIcon from '@mui/icons-material/SearchOutlined';

import { PageControls } from './components/page-controls';
import { Search } from './components/search';
import { Drawer, DrawerComponent, DrawerProvider } from './components/drawer-system';
import { Sidebar } from './components/sidebar';
import { Toolbar } from './components/toolbar';
import { ViewSidebarReverseIcon } from './icons';

const plugins = [
  createPluginRegistration(LoaderPluginPackage, {
    loadingOptions: {
      type: 'url',
      pdfFile: {
        id: 'pdf',
        url: 'https://snippet.embedpdf.com/ebook.pdf',
      },
      options: {
        mode: 'full-fetch',
      },
    },
  }),
  createPluginRegistration(ViewportPluginPackage, {
    viewportGap: 10,
  }),
  createPluginRegistration(ScrollPluginPackage, {
    strategy: ScrollStrategy.Vertical,
  }),
  createPluginRegistration(RenderPluginPackage),
  createPluginRegistration(TilingPluginPackage, {
    tileSize: 768,
    overlapPx: 2.5,
    extraRings: 0,
  }),
  createPluginRegistration(ZoomPluginPackage, {
    defaultZoomLevel: ZoomMode.FitPage,
  }),
  createPluginRegistration(SearchPluginPackage),
  createPluginRegistration(InteractionManagerPluginPackage),
  createPluginRegistration(PanPluginPackage),
  createPluginRegistration(RotatePluginPackage),
  createPluginRegistration(SpreadPluginPackage),
  createPluginRegistration(FullscreenPluginPackage),
  createPluginRegistration(ExportPluginPackage),
  createPluginRegistration(ThumbnailPluginPackage),
  createPluginRegistration(SelectionPluginPackage),
];

const drawerComponents: DrawerComponent[] = [
  {
    id: 'search',
    component: Search,
    icon: SearchOutlinedIcon,
    label: 'Search',
    position: 'right',
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: ViewSidebarReverseIcon,
    label: 'Sidebar',
    position: 'left',
  },
];

function App() {
  const { engine, isLoading, error } = usePdfiumEngine();

  if (error) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Alert severity="error">Failed to initialize PDF viewer:</Alert>
      </Box>
    );
  }

  if (isLoading || !engine) {
    return (
      <Box
        sx={{
          height: '100%',
          width: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <CircularProgress size={48} />
      </Box>
    );
  }

  return (
    <DrawerProvider components={drawerComponents}>
      <EmbedPDF engine={engine} plugins={plugins}>
        {({ pluginsReady }) => (
          <FullscreenProvider>
            <Box
              sx={{
                height: '100%',
                width: '100%',
                display: 'flex',
                flexDirection: 'column',
                position: 'relative',
                userSelect: 'none',
              }}
            >
              <Toolbar />

              {/* Main content area with sidebars */}
              <Box sx={{ display: 'flex', flexGrow: 1, overflow: 'hidden' }}>
                {/* Left Sidebar */}
                <Drawer position="left" />

                {/* Main Viewport */}
                <Box
                  sx={{
                    flex: '1 1 0', // grow / shrink, flex-basis 0
                    minWidth: 0, // allow shrinking inside flex row
                    display: 'flex',
                    flexDirection: 'column',
                    position: 'relative',
                  }}
                >
                  <GlobalPointerProvider>
                    <PanMode />
                    <Viewport
                      style={{
                        width: '100%',
                        height: '100%',
                        flexGrow: 1,
                        backgroundColor: '#f1f3f5',
                        overflow: 'auto',
                      }}
                    >
                      {!pluginsReady && (
                        <Box
                          sx={{
                            display: 'flex',
                            justifyContent: 'center',
                            alignItems: 'center',
                            height: '100%',
                            width: '100%',
                          }}
                        >
                          <CircularProgress size={48} />
                        </Box>
                      )}
                      {pluginsReady && (
                        <Scroller
                          renderPage={({
                            document,
                            width,
                            height,
                            pageIndex,
                            scale,
                            rotatedHeight,
                            rotatedWidth,
                            rotation,
                          }) => (
                            <Rotate key={document?.id} pageSize={{ width, height }}>
                              <PagePointerProvider
                                pageIndex={pageIndex}
                                pageWidth={rotatedWidth}
                                pageHeight={rotatedHeight}
                                rotation={rotation}
                                scale={scale}
                                style={{
                                  width,
                                  height,
                                }}
                              >
                                <RenderLayer
                                  pageIndex={pageIndex}
                                  style={{ pointerEvents: 'none' }}
                                />
                                <TilingLayer
                                  pageIndex={pageIndex}
                                  scale={scale}
                                  style={{ pointerEvents: 'none' }}
                                />
                                <SearchLayer
                                  pageIndex={pageIndex}
                                  scale={scale}
                                  style={{ pointerEvents: 'none' }}
                                />
                                <MarqueeZoom
                                  pageIndex={pageIndex}
                                  scale={scale}
                                  pageWidth={width}
                                  pageHeight={height}
                                />
                                <SelectionLayer pageIndex={pageIndex} scale={scale} />
                              </PagePointerProvider>
                            </Rotate>
                          )}
                        />
                      )}
                      <PageControls />
                    </Viewport>
                  </GlobalPointerProvider>
                </Box>

                {/* Right Sidebar */}
                <Drawer position="right" />
              </Box>
            </Box>
            <Download />
            <FilePicker />
          </FullscreenProvider>
        )}
      </EmbedPDF>
    </DrawerProvider>
  );
}

export default App;

// examples/vue-vuetify/src/components/Application.vue
<script setup lang="ts">
import { usePdfiumEngine } from '@embedpdf/engines/vue';
import { EmbedPDF } from '@embedpdf/core/vue';
import { createPluginRegistration } from '@embedpdf/core';
import { LoaderPluginPackage } from '@embedpdf/plugin-loader/vue';
import { Viewport, ViewportPluginPackage } from '@embedpdf/plugin-viewport/vue';
import { Scroller, ScrollPluginPackage, ScrollStrategy } from '@embedpdf/plugin-scroll/vue';
import { RenderLayer, RenderPluginPackage } from '@embedpdf/plugin-render/vue';
import { TilingLayer, TilingPluginPackage } from '@embedpdf/plugin-tiling/vue';
import { SelectionLayer, SelectionPluginPackage } from '@embedpdf/plugin-selection/vue';
import {
  InteractionManagerPluginPackage,
  GlobalPointerProvider,
  PagePointerProvider,
} from '@embedpdf/plugin-interaction-manager/vue';
import { RotatePluginPackage } from '@embedpdf/plugin-rotate/vue';
import { Rotate } from '@embedpdf/plugin-rotate/vue';
import { FullscreenPluginPackage } from '@embedpdf/plugin-fullscreen/vue';
import { ZoomMode, ZoomPluginPackage, MarqueeZoom } from '@embedpdf/plugin-zoom/vue';
import { PanPluginPackage } from '@embedpdf/plugin-pan/vue';
import { ExportPluginPackage } from '@embedpdf/plugin-export/vue';
import { SpreadPluginPackage } from '@embedpdf/plugin-spread/vue';
import { PrintPluginPackage } from '@embedpdf/plugin-print/vue';
import { SearchPluginPackage, SearchLayer } from '@embedpdf/plugin-search/vue';
import { ThumbnailPluginPackage } from '@embedpdf/plugin-thumbnail/vue';

import Toolbar from './Toolbar.vue';
import DrawerProvider from './drawer-system/DrawerProvider.vue';
import Drawer from './drawer-system/Drawer.vue';
import Search from './Search.vue';
import Sidebar from './Sidebar.vue';

// Define drawer components
const drawerComponents = [
  {
    id: 'search',
    component: Search,
    icon: 'mdi-magnify',
    label: 'Search',
    position: 'right' as const,
  },
  {
    id: 'sidebar',
    component: Sidebar,
    icon: 'mdi-dock-left',
    label: 'Sidebar',
    position: 'left' as const,
  },
];

const { engine, isLoading: engineLoading, error: engineError } = usePdfiumEngine();
</script>

<template>
  <!-- Loading state -->
  <div v-if="engineLoading" class="d-flex fill-height align-center justify-center">
    <div class="text-center">
      <v-progress-circular indeterminate color="primary" size="64"></v-progress-circular>
      <div class="text-body-1 text-medium-emphasis mt-4">Loading PDF engine...</div>
    </div>
  </div>

  <!-- Error state -->
  <div v-else-if="engineError" class="d-flex fill-height align-center justify-center">
    <v-alert type="error" variant="tonal" class="ma-4">
      <v-alert-title>Error</v-alert-title>
      {{ engineError.message }}
    </v-alert>
  </div>

  <!-- Main application -->
  <div v-else-if="engine" class="fill-height">
    <EmbedPDF
      :engine="engine"
      :plugins="[
        createPluginRegistration(LoaderPluginPackage, {
          loadingOptions: {
            type: 'url',
            pdfFile: {
              id: 'sample-pdf',
              name: 'embedpdf-ebook.pdf',
              url: 'https://snippet.embedpdf.com/ebook.pdf',
            },
          },
        }),
        createPluginRegistration(ViewportPluginPackage, {
          viewportGap: 10,
        }),
        createPluginRegistration(ScrollPluginPackage, {
          strategy: ScrollStrategy.Vertical,
          pageGap: 10,
        }),
        createPluginRegistration(RenderPluginPackage),
        createPluginRegistration(TilingPluginPackage, {
          tileSize: 768,
          overlapPx: 2.5,
          extraRings: 0,
        }),
        createPluginRegistration(InteractionManagerPluginPackage),
        createPluginRegistration(SelectionPluginPackage),
        createPluginRegistration(RotatePluginPackage),
        createPluginRegistration(FullscreenPluginPackage),
        createPluginRegistration(ZoomPluginPackage, {
          defaultZoomLevel: ZoomMode.FitPage,
        }),
        createPluginRegistration(PanPluginPackage),
        createPluginRegistration(ExportPluginPackage),
        createPluginRegistration(SpreadPluginPackage),
        createPluginRegistration(PrintPluginPackage),
        createPluginRegistration(ThumbnailPluginPackage, {
          imagePadding: 10,
          labelHeight: 25,
        }),
        createPluginRegistration(SearchPluginPackage, {
          flags: [],
          showAllResults: true,
        }),
      ]"
    >
      <template #default="{ pluginsReady }">
        <DrawerProvider :components="drawerComponents">
          <v-layout class="fill-height" id="pdf-app-layout">
            <!-- Toolbar -->
            <Toolbar />

            <!-- Left Drawer -->
            <Drawer position="left" />

            <!-- Main content -->
            <v-main class="fill-height">
              <div class="fill-height position-relative">
                <GlobalPointerProvider>
                  <Viewport class="fill-height" style="background-color: #f5f5f5; overflow: auto">
                    <div
                      v-if="!pluginsReady"
                      class="d-flex fill-height align-center justify-center"
                    >
                      <div class="text-center">
                        <v-progress-circular
                          indeterminate
                          color="primary"
                          size="48"
                        ></v-progress-circular>
                        <div class="text-body-1 text-medium-emphasis mt-4">Loading plugins...</div>
                      </div>
                    </div>
                    <Scroller v-else>
                      <template #default="{ page }">
                        <Rotate
                          :key="page.document?.id"
                          :page-size="{ width: page.width, height: page.height }"
                        >
                          <PagePointerProvider
                            :page-index="page.pageIndex"
                            :page-width="page.width"
                            :page-height="page.height"
                            :rotation="page.rotation"
                            :scale="page.scale"
                            class="position-absolute"
                          >
                            <RenderLayer
                              :page-index="page.pageIndex"
                              style="pointer-events: none"
                            />
                            <TilingLayer
                              :page-index="page.pageIndex"
                              :scale="page.scale"
                              style="pointer-events: none"
                            />
                            <MarqueeZoom :page-index="page.pageIndex" :scale="page.scale" />
                            <SearchLayer :page-index="page.pageIndex" :scale="page.scale" />
                            <SelectionLayer :page-index="page.pageIndex" :scale="page.scale" />
                          </PagePointerProvider>
                        </Rotate>
                      </template>
                    </Scroller>
                    <!-- Page Controls Overlay -->
                    <PageControls />
                  </Viewport>
                </GlobalPointerProvider>
              </div>
            </v-main>

            <!-- Right Drawer -->
            <Drawer position="right" />
          </v-layout>
        </DrawerProvider>
      </template>
    </EmbedPDF>
  </div>

  <!-- Engine not ready state -->
  <div v-else class="d-flex fill-height align-center justify-center">
    <div class="text-body-1 text-medium-emphasis text-center">Engine not ready</div>
  </div>
</template>

<style scoped>
#pdf-app-layout {
  user-select: none;
}
.flex-1-1-100 {
  flex: 1 1 100%;
}
</style>
