// examples/react-mui/src/components/toolbar/index.tsx
import { usePan } from '@embedpdf/plugin-pan/react';
import { useRotateCapability } from '@embedpdf/plugin-rotate/react';
import { useSpread } from '@embedpdf/plugin-spread/react';
import MenuIcon from '@mui/icons-material/Menu';
import BackHandOutlinedIcon from '@mui/icons-material/BackHandOutlined';
import RotateRightIcon from '@mui/icons-material/RotateRight';
import RotateLeftIcon from '@mui/icons-material/RotateLeft';
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import MenuBookOutlinedIcon from '@mui/icons-material/MenuBookOutlined';
import BookOutlinedIcon from '@mui/icons-material/BookOutlined';
import FullscreenOutlinedIcon from '@mui/icons-material/FullscreenOutlined';
import FullscreenExitOutlinedIcon from '@mui/icons-material/FullscreenExitOutlined';
import DownloadOutlinedIcon from '@mui/icons-material/DownloadOutlined';
import FileOpenOutlinedIcon from '@mui/icons-material/FileOpenOutlined';
import {
  Box,
  Divider,
  AppBar,
  Toolbar as MuiToolbar,
  Menu,
  MenuItem,
  ListItemIcon,
  ListItemText,
  ListSubheader,
} from '@mui/material';
import { useState, MouseEvent } from 'react';

import { ZoomControls } from '../zoom-controls';
import { PageSettingsIcon } from '../../icons';
import { DrawerToggleButton } from '../drawer-system';
import { ToggleIconButton } from '../toggle-icon-button';
import { SpreadMode } from '@embedpdf/plugin-spread';
import { useFullscreen } from '@embedpdf/plugin-fullscreen/react';
import { useExportCapability } from '@embedpdf/plugin-export/react';
import { useLoaderCapability } from '@embedpdf/plugin-loader/react';

export const Toolbar = () => {
  const { provides: panProvider, isPanning } = usePan();
  const { provides: rotateProvider } = useRotateCapability();
  const { spreadMode, provides: spreadProvider } = useSpread();
  const { provides: fullscreenProvider, state: fullscreenState } = useFullscreen();
  const { provides: exportProvider } = useExportCapability();
  const { provides: loaderProvider } = useLoaderCapability();
  // Menu state for page settings
  const [pageSettingsAnchorEl, setPageSettingsAnchorEl] = useState<null | HTMLElement>(null);
  const pageSettingsOpen = Boolean(pageSettingsAnchorEl);

  // Menu state for main menu
  const [menuAnchorEl, setMenuAnchorEl] = useState<null | HTMLElement>(null);
  const menuOpen = Boolean(menuAnchorEl);

  const handleTogglePanMode = () => {
    panProvider?.togglePan();
  };

  const handleRotateForward = () => {
    rotateProvider?.rotateForward();
    setPageSettingsAnchorEl(null); // Close menu after action
  };

  const handleRotateBackward = () => {
    rotateProvider?.rotateBackward();
    setPageSettingsAnchorEl(null); // Close menu after action
  };

  const handlePageSettingsClick = (event: MouseEvent<HTMLElement>) => {
    setPageSettingsAnchorEl(event.currentTarget);
  };

  const handlePageSettingsClose = () => {
    setPageSettingsAnchorEl(null);
  };

  const handleMenuClick = (event: MouseEvent<HTMLElement>) => {
    setMenuAnchorEl(event.currentTarget);
  };

  const handleMenuClose = () => {
    setMenuAnchorEl(null);
  };

  const handleSpreadModeChange = (mode: SpreadMode) => {
    spreadProvider?.setSpreadMode(mode);
    handlePageSettingsClose();
  };

  const handleFullscreenToggle = () => {
    fullscreenProvider?.toggleFullscreen();
    handlePageSettingsClose();
    handleMenuClose();
  };

  const handleDownload = () => {
    exportProvider?.download();
    handleMenuClose();
  };

  const handleOpenFilePicker = () => {
    loaderProvider?.openFileDialog();
    handleMenuClose();
  };

  return (
    <AppBar position="static">
      <MuiToolbar variant="dense" disableGutters sx={{ gap: 1.5, px: 1.5 }}>
        <ToggleIconButton isOpen={menuOpen} onClick={handleMenuClick}>
          <MenuIcon fontSize="small" />
        </ToggleIconButton>
        <Menu
          anchorEl={menuAnchorEl}
          open={menuOpen}
          onClose={handleMenuClose}
          disablePortal
          anchorOrigin={{
            vertical: 'bottom',
            horizontal: 'left',
          }}
          transformOrigin={{
            vertical: 'top',
            horizontal: 'left',
          }}
        >
          <MenuItem onClick={handleOpenFilePicker}>
            <ListItemIcon>
              <FileOpenOutlinedIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Open File</ListItemText>
          </MenuItem>
          <MenuItem onClick={handleDownload}>
            <ListItemIcon>
              <DownloadOutlinedIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Download</ListItemText>
          </MenuItem>
          <MenuItem onClick={handleFullscreenToggle}>
            <ListItemIcon>
              {fullscreenState.isFullscreen ? (
                <FullscreenExitOutlinedIcon fontSize="small" />
              ) : (
                <FullscreenOutlinedIcon fontSize="small" />
              )}
            </ListItemIcon>
            <ListItemText>
              {fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
            </ListItemText>
          </MenuItem>
        </Menu>
        <Divider
          orientation="vertical"
          flexItem
          sx={{ backgroundColor: 'white', my: 1.2, opacity: 0.5 }}
        />
        <DrawerToggleButton componentId="sidebar" />
        <ToggleIconButton isOpen={pageSettingsOpen} onClick={handlePageSettingsClick}>
          <PageSettingsIcon fontSize="small" />
        </ToggleIconButton>
        <Menu
          anchorEl={pageSettingsAnchorEl}
          open={pageSettingsOpen}
          onClose={handlePageSettingsClose}
          disablePortal
          anchorOrigin={{
            vertical: 'bottom',
            horizontal: 'left',
          }}
          transformOrigin={{
            vertical: 'top',
            horizontal: 'left',
          }}
        >
          <ListSubheader>Page Orientation</ListSubheader>
          <MenuItem onClick={handleRotateForward}>
            <ListItemIcon>
              <RotateRightIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Rotate Clockwise</ListItemText>
          </MenuItem>
          <MenuItem onClick={handleRotateBackward}>
            <ListItemIcon>
              <RotateLeftIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Rotate Counter-clockwise</ListItemText>
          </MenuItem>
          <Divider />
          <ListSubheader>Page Layout</ListSubheader>
          <MenuItem
            onClick={() => handleSpreadModeChange(SpreadMode.None)}
            selected={spreadMode === SpreadMode.None}
          >
            <ListItemIcon>
              <DescriptionOutlinedIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Single Page</ListItemText>
          </MenuItem>
          <MenuItem
            onClick={() => handleSpreadModeChange(SpreadMode.Odd)}
            selected={spreadMode === SpreadMode.Odd}
          >
            <ListItemIcon>
              <MenuBookOutlinedIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Odd Pages</ListItemText>
          </MenuItem>
          <MenuItem
            onClick={() => handleSpreadModeChange(SpreadMode.Even)}
            selected={spreadMode === SpreadMode.Even}
          >
            <ListItemIcon>
              <BookOutlinedIcon fontSize="small" />
            </ListItemIcon>
            <ListItemText>Even Pages</ListItemText>
          </MenuItem>
          <Divider />
          <MenuItem onClick={handleFullscreenToggle}>
            <ListItemIcon>
              {fullscreenState.isFullscreen ? (
                <FullscreenExitOutlinedIcon fontSize="small" />
              ) : (
                <FullscreenOutlinedIcon fontSize="small" />
              )}
            </ListItemIcon>
            <ListItemText>
              {fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen'}
            </ListItemText>
          </MenuItem>
        </Menu>
        <Divider
          orientation="vertical"
          flexItem
          sx={{ backgroundColor: 'white', my: 1.2, opacity: 0.5 }}
        />
        <ZoomControls />
        <Divider
          orientation="vertical"
          flexItem
          sx={{ backgroundColor: 'white', my: 1.2, opacity: 0.5 }}
        />
        <ToggleIconButton isOpen={isPanning} onClick={handleTogglePanMode}>
          <BackHandOutlinedIcon fontSize="small" />
        </ToggleIconButton>
        <Box sx={{ flexGrow: 1 }} />
        <DrawerToggleButton componentId="search" />
      </MuiToolbar>
    </AppBar>
  );
};

// examples/vue-vuetify/src/components/Toolbar.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useFullscreen } from '@embedpdf/plugin-fullscreen/vue';
import { usePan } from '@embedpdf/plugin-pan/vue';
import { useRotateCapability } from '@embedpdf/plugin-rotate/vue';
import { useExportCapability } from '@embedpdf/plugin-export/vue';
import { useLoaderCapability } from '@embedpdf/plugin-loader/vue';
import { useSpread, SpreadMode } from '@embedpdf/plugin-spread/vue';
import { useInteractionManager } from '@embedpdf/plugin-interaction-manager/vue';
import PrintDialog from './PrintDialog.vue';
import ZoomControls from './ZoomControls.vue';
import DrawerToggleButton from './drawer-system/DrawerToggleButton.vue';

const { provides: fullscreenProvider, state: fullscreenState } = useFullscreen();
const { provides: panProvider, isPanning } = usePan();
const { provides: rotateProvider } = useRotateCapability();
const { provides: exportProvider } = useExportCapability();
const { provides: loaderProvider } = useLoaderCapability();
const { spreadMode, provides: spreadProvider } = useSpread();
const { provides: pointerProvider, state: interactionManagerState } = useInteractionManager();

// Menu state
const mainMenuOpen = ref(false);
const pageSettingsMenuOpen = ref(false);
const printDialogOpen = ref(false);

const handleFullscreenToggle = () => {
  fullscreenProvider?.value?.toggleFullscreen();
  mainMenuOpen.value = false;
  pageSettingsMenuOpen.value = false;
};

const handlePanMode = () => {
  panProvider?.value?.togglePan();
};

const handlePointerMode = () => {
  pointerProvider?.value?.activate('pointerMode');
};

const handleRotateForward = () => {
  rotateProvider?.value?.rotateForward();
  pageSettingsMenuOpen.value = false;
};

const handleRotateBackward = () => {
  rotateProvider?.value?.rotateBackward();
  pageSettingsMenuOpen.value = false;
};

const handleDownload = () => {
  exportProvider?.value?.download();
  mainMenuOpen.value = false;
};

const handleOpenFilePicker = () => {
  loaderProvider?.value?.openFileDialog();
  mainMenuOpen.value = false;
};

const handleSpreadModeChange = (mode: SpreadMode) => {
  spreadProvider?.value?.setSpreadMode(mode);
  pageSettingsMenuOpen.value = false;
};

const handlePrint = () => {
  printDialogOpen.value = true;
  mainMenuOpen.value = false;
};

const handlePrintDialogClose = () => {
  printDialogOpen.value = false;
};
</script>

<template>
  <v-app-bar elevation="0" density="compact" color="surface" class="toolbar">
    <!-- Main Menu -->
    <v-menu v-model="mainMenuOpen" :close-on-content-click="false" attach="#pdf-app-layout">
      <template v-slot:activator="{ props }">
        <v-btn v-bind="props" icon="mdi-menu" variant="text" size="small" :active="mainMenuOpen" />
      </template>
      <v-list density="compact">
        <v-list-item @click="handleOpenFilePicker">
          <template v-slot:prepend>
            <v-icon>mdi-file-document-outline</v-icon>
          </template>
          <v-list-item-title>Open File</v-list-item-title>
        </v-list-item>
        <v-list-item @click="handleDownload">
          <template v-slot:prepend>
            <v-icon>mdi-download-outline</v-icon>
          </template>
          <v-list-item-title>Download</v-list-item-title>
        </v-list-item>
        <v-list-item @click="handlePrint">
          <template v-slot:prepend>
            <v-icon>mdi-printer-outline</v-icon>
          </template>
          <v-list-item-title>Print</v-list-item-title>
        </v-list-item>
        <v-list-item @click="handleFullscreenToggle">
          <template v-slot:prepend>
            <v-icon>
              {{ fullscreenState.isFullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen' }}
            </v-icon>
          </template>
          <v-list-item-title>
            {{ fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen' }}
          </v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>

    <v-divider vertical class="mx-3 my-3"></v-divider>

    <!-- Sidebar Toggle (placeholder) -->
    <DrawerToggleButton component-id="sidebar" />

    <!-- Page Settings Menu -->
    <v-menu v-model="pageSettingsMenuOpen" :close-on-content-click="false" attach="#pdf-app-layout">
      <template v-slot:activator="{ props }">
        <v-btn
          v-bind="props"
          icon="mdi-cog-outline"
          variant="text"
          size="small"
          :active="pageSettingsMenuOpen"
        />
      </template>
      <v-list density="compact">
        <v-list-subheader>Page Orientation</v-list-subheader>
        <v-list-item @click="handleRotateForward">
          <template v-slot:prepend>
            <v-icon>mdi-rotate-right</v-icon>
          </template>
          <v-list-item-title>Rotate Clockwise</v-list-item-title>
        </v-list-item>
        <v-list-item @click="handleRotateBackward">
          <template v-slot:prepend>
            <v-icon>mdi-rotate-left</v-icon>
          </template>
          <v-list-item-title>Rotate Counter-clockwise</v-list-item-title>
        </v-list-item>

        <v-divider class="my-1"></v-divider>

        <v-list-subheader>Page Layout</v-list-subheader>
        <v-list-item
          @click="() => handleSpreadModeChange(SpreadMode.None)"
          :active="spreadMode === SpreadMode.None"
        >
          <template v-slot:prepend>
            <v-icon>mdi-file-document-outline</v-icon>
          </template>
          <v-list-item-title>Single Page</v-list-item-title>
        </v-list-item>
        <v-list-item
          @click="() => handleSpreadModeChange(SpreadMode.Odd)"
          :active="spreadMode === SpreadMode.Odd"
        >
          <template v-slot:prepend>
            <v-icon>mdi-book-open-page-variant-outline</v-icon>
          </template>
          <v-list-item-title>Odd Pages</v-list-item-title>
        </v-list-item>
        <v-list-item
          @click="() => handleSpreadModeChange(SpreadMode.Even)"
          :active="spreadMode === SpreadMode.Even"
        >
          <template v-slot:prepend>
            <v-icon>mdi-book-open-outline</v-icon>
          </template>
          <v-list-item-title>Even Pages</v-list-item-title>
        </v-list-item>

        <v-divider class="my-1"></v-divider>

        <v-list-item @click="handleFullscreenToggle">
          <template v-slot:prepend>
            <v-icon>
              {{ fullscreenState.isFullscreen ? 'mdi-fullscreen-exit' : 'mdi-fullscreen' }}
            </v-icon>
          </template>
          <v-list-item-title>
            {{ fullscreenState.isFullscreen ? 'Exit Fullscreen' : 'Fullscreen' }}
          </v-list-item-title>
        </v-list-item>
      </v-list>
    </v-menu>

    <v-divider vertical class="mx-3 my-3"></v-divider>

    <!-- Zoom Controls -->
    <ZoomControls />

    <v-divider vertical class="mx-3 my-3"></v-divider>

    <!-- Pan Mode -->
    <v-tooltip text="Pan Mode" location="bottom">
      <template v-slot:activator="{ props }">
        <v-btn
          v-bind="props"
          @click="handlePanMode"
          icon="mdi-hand-back-left-outline"
          variant="text"
          size="small"
          :active="isPanning"
        />
      </template>
    </v-tooltip>

    <!-- Pointer Mode -->
    <v-tooltip text="Pointer Mode" location="bottom">
      <template v-slot:activator="{ props }">
        <v-btn
          v-bind="props"
          @click="handlePointerMode"
          icon="mdi-cursor-default-outline"
          variant="text"
          size="small"
          :active="interactionManagerState.activeMode === 'pointerMode'"
        />
      </template>
    </v-tooltip>

    <v-spacer></v-spacer>

    <!-- Search Toggle -->
    <DrawerToggleButton component-id="search" />
  </v-app-bar>

  <!-- Print Dialog -->
  <PrintDialog :open="printDialogOpen" @close="handlePrintDialogClose" />
</template>

<style scoped>
.toolbar {
  border-bottom: 1px solid #cfd4da;
  padding: 0 12px;
}
</style>
