// packages/plugin-export/src/svelte/components/Download.svelte
<script lang="ts">
  import { ignore } from '@embedpdf/models';
  import { useExportCapability, useExportPlugin } from '../hooks';

  const { provides: exportCapability } = useExportCapability();
  const { plugin: exportPlugin } = useExportPlugin();

  let anchorElement: HTMLAnchorElement | undefined;

  $effect(() => {
    if (!exportCapability) return;
    if (!exportPlugin) return;

    const unsub = exportPlugin.onRequest((action) => {
      if (action === 'download') {
        const el = anchorElement;
        if (!el) return;

        const task = exportPlugin.saveAsCopyAndGetBufferAndName();
        task.wait(({ buffer, name }) => {
          const url = URL.createObjectURL(new Blob([buffer]));
          el.href = url;
          el.download = name;
          el.click();
          URL.revokeObjectURL(url);
        }, ignore);
      }
    });

    return unsub;
  });
</script>

<a style="display: none" bind:this={anchorElement} href="/" aria-label="Download link"></a>

// packages/plugin-export/src/preact/components/download.tsx
/** @jsxImportSource preact */
import { ignore } from '@embedpdf/models';
import { useEffect, useRef } from 'preact/hooks';

import { useExportCapability } from '../hooks';

export function Download() {
  const { provides: exportCapability } = useExportCapability();
  const ref = useRef<HTMLAnchorElement>(null);

  useEffect(() => {
    if (!exportCapability) return;

    const unsub = exportCapability.onRequest(async (action) => {
      if (action === 'download') {
        const el = ref.current;
        if (!el) return;

        const task = exportCapability.saveAsCopy();
        task.wait((buffer) => {
          const url = URL.createObjectURL(new Blob([buffer]));
          el.href = url;
          el.download = 'document.pdf';
          el.click();
          URL.revokeObjectURL(url);
        }, ignore);
      }
    });

    return unsub;
  }, [exportCapability]);

  return <a style={{ display: 'none' }} ref={ref} />;
}
