// packages/plugin-stamp/src/shared/components/stamp-img.tsx
import { useEffect, useState, useRef, HTMLAttributes, CSSProperties } from '@framework';
import { ignore, PdfErrorCode } from '@embedpdf/models';
import { useStampCapability } from '../hooks';

type StampImgProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  libraryId: string;
  pageIndex: number;
  width: number;
  dpr?: number;
  style?: CSSProperties;
};

export function StampImg({ libraryId, pageIndex, width, dpr, style, ...props }: StampImgProps) {
  const { provides } = useStampCapability();
  const [url, setUrl] = useState<string>();
  const urlRef = useRef<string | null>(null);

  useEffect(() => {
    if (!provides) return;

    const task = provides.renderStamp(libraryId, pageIndex, width, dpr ?? window.devicePixelRatio);

    task.wait((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      urlRef.current = objectUrl;
      setUrl(objectUrl);
    }, ignore);

    return () => {
      if (urlRef.current) {
        URL.revokeObjectURL(urlRef.current);
        urlRef.current = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled stamp render task',
        });
      }
    };
  }, [provides, libraryId, pageIndex, width, dpr]);

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  return url ? <img src={url} onLoad={handleImageLoad} style={style} {...props} /> : null;
}

// packages/plugin-stamp/src/svelte/components/StampImg.svelte
<script lang="ts">
  import { ignore, PdfErrorCode } from '@embedpdf/models';
  import { useStampCapability } from '../hooks';
  import type { HTMLImgAttributes } from 'svelte/elements';

  interface Props extends HTMLImgAttributes {
    libraryId: string;
    pageIndex: number;
    width: number;
    dpr?: number;
  }

  const { libraryId, pageIndex, width, dpr, ...imgProps }: Props = $props();

  const stampCapability = useStampCapability();

  let url = $state<string | undefined>(undefined);
  let urlRef: string | null = null;

  $effect(() => {
    if (!stampCapability.provides) return;

    const task = stampCapability.provides.renderStamp(
      libraryId,
      pageIndex,
      width,
      dpr ?? window.devicePixelRatio,
    );

    task.wait((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      urlRef = objectUrl;
      url = objectUrl;
    }, ignore);

    return () => {
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled stamp render task',
        });
      }
    };
  });

  const handleImageLoad = () => {
    if (urlRef) {
      URL.revokeObjectURL(urlRef);
      urlRef = null;
    }
  };
</script>

{#if url}
  <img src={url} onload={handleImageLoad} {...imgProps} alt="Stamp preview" />
{/if}
