// packages/plugin-annotation/src/shared/components/annotation-paint-layer.tsx
import { useEffect, useMemo, useRef, useState } from '@framework';
import { useAnnotationPlugin } from '../hooks';
import { PreviewState, HandlerServices } from '@embedpdf/plugin-annotation';
import { PreviewRenderer } from './preview-renderer';

interface Props {
  documentId: string;
  pageIndex: number;
  scale: number;
}

export function AnnotationPaintLayer({ documentId, pageIndex, scale }: Props) {
  const { plugin: annotationPlugin } = useAnnotationPlugin();
  const [previews, setPreviews] = useState<Map<string, PreviewState>>(new Map());

  const fileInputRef = useRef<HTMLInputElement>(null);

  const services = useMemo<HandlerServices>(
    () => ({
      requestFile: ({ accept, onFile }) => {
        if (!fileInputRef.current) return;
        const input = fileInputRef.current;
        input.accept = accept;
        input.onchange = (e) => {
          const file = (e.target as HTMLInputElement).files?.[0];
          if (file) {
            onFile(file);
            input.value = '';
          }
        };
        input.click();
      },
    }),
    [],
  );

  useEffect(() => {
    if (!annotationPlugin) return;

    return annotationPlugin.registerPageHandlers(documentId, pageIndex, scale, {
      services,
      onPreview: (toolId, state) => {
        setPreviews((prev) => {
          const next = new Map(prev);
          if (state) {
            next.set(toolId, state);
          } else {
            next.delete(toolId);
          }
          return next;
        });
      },
    });
  }, [documentId, pageIndex, scale, annotationPlugin, services]);

  return (
    <>
      <input ref={fileInputRef} type="file" style={{ display: 'none' }} />

      {/* Render any active previews from any tool */}
      {Array.from(previews.entries()).map(([toolId, preview]) => (
        <PreviewRenderer key={toolId} toolId={toolId} preview={preview} scale={scale} />
      ))}
    </>
  );
}

// packages/plugin-annotation/src/svelte/components/AnnotationPaintLayer.svelte
<script lang="ts">
  import { useAnnotationPlugin } from '../hooks';
  import type { PreviewState, HandlerServices } from '@embedpdf/plugin-annotation';
  import PreviewRenderer from './PreviewRenderer.svelte';

  interface AnnotationPaintLayerProps {
    documentId: string;
    pageIndex: number;
    scale: number;
  }

  let { documentId, pageIndex, scale }: AnnotationPaintLayerProps = $props();

  const annotationPlugin = useAnnotationPlugin();
  let previews = $state<Map<string, PreviewState>>(new Map());

  let fileInputRef: HTMLInputElement | null = $state(null);

  const services: HandlerServices = {
    requestFile: ({ accept, onFile }) => {
      if (!fileInputRef) return;
      const input = fileInputRef;
      input.accept = accept;
      input.onchange = (e) => {
        const file = (e.target as HTMLInputElement).files?.[0];
        if (file) {
          onFile(file);
          input.value = '';
        }
      };
      input.click();
    },
  };

  $effect(() => {
    if (!annotationPlugin.plugin) return;

    return annotationPlugin.plugin.registerPageHandlers(documentId, pageIndex, scale, {
      services,
      onPreview: (toolId, state) => {
        previews = new Map(previews);
        if (state) {
          previews.set(toolId, state);
        } else {
          previews.delete(toolId);
        }
      },
    });
  });
</script>

<input bind:this={fileInputRef} type="file" style:display="none" />

<!-- Render any active previews from any tool -->
{#each Array.from(previews.entries()) as [toolId, preview] (toolId)}
  <PreviewRenderer {toolId} {preview} {scale} />
{/each}
