// packages/plugin-render/src/svelte/components/RenderLayer.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { HTMLImgAttributes } from 'svelte/elements';

  import { ignore, PdfErrorCode } from '@embedpdf/models';

  import { useRenderCapability, useRenderPlugin } from '../hooks';

  interface RenderLayerProps extends Omit<HTMLImgAttributes, 'style'> {
    pageIndex: number;
    /**
     * The scale factor for rendering the page.
     */
    scale?: number;
    dpr?: number;
    class?: string;
  }

  let { pageIndex, scale, dpr, class: propsClass, ...props }: RenderLayerProps = $props();

  const renderCapability = useRenderCapability();
  const renderPlugin = useRenderPlugin();

  const actualScale = $derived(scale ?? 1);

  let imageUrl = $state<string | null>(null);
  let urlRef: string | null = null;
  let refreshTick = $state(0);

  // Handle refresh subscription
  onMount(() => {
    if (!renderPlugin.plugin) return;
    const unsubscribe = renderPlugin.plugin.onRefreshPages((pages) => {
      if (pages.includes(pageIndex)) {
        refreshTick++;
      }
    });

    return unsubscribe;
  });
  // Handle rendering
  $effect(() => {
    if (renderCapability.provides || (renderCapability.provides && refreshTick)) {
      const task = renderCapability.provides.renderPage({
        pageIndex,
        options: { scaleFactor: actualScale, dpr: dpr || window.devicePixelRatio }
      });

      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        imageUrl = url;
        urlRef = url;
      }, ignore);

      return () => {
        if (urlRef) {
          URL.revokeObjectURL(urlRef);
          urlRef = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task'
          });
        }
      };
    }
  });

  function handleImageLoad() {
    if (urlRef) {
      URL.revokeObjectURL(urlRef);
      urlRef = null;
    }
  }
</script>

{#if imageUrl}
  <img
    src={imageUrl}
    onload={handleImageLoad}
    {...props}
    style="width: 100%; height: 100%;"
    class={propsClass}
    alt=""
  />
{/if}

// packages/plugin-render/src/shared/components/render-layer.tsx
import { Fragment, useEffect, useRef, useState } from '@framework';
import type { CSSProperties, HTMLAttributes } from '@framework';

import { ignore, PdfErrorCode } from '@embedpdf/models';

import { useRenderCapability, useRenderPlugin } from '../hooks/use-render';

type RenderLayerProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  pageIndex: number;
  scaleFactor?: number;
  dpr?: number;
  style?: CSSProperties;
};

export function RenderLayer({
  pageIndex,
  scaleFactor = 1,
  dpr,
  style,
  ...props
}: RenderLayerProps) {
  const { provides: renderProvides } = useRenderCapability();
  const { plugin: renderPlugin } = useRenderPlugin();

  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);
  const [refreshTick, setRefreshTick] = useState(0);

  useEffect(() => {
    if (!renderPlugin) return;
    return renderPlugin.onRefreshPages((pages) => {
      if (pages.includes(pageIndex)) {
        setRefreshTick((tick) => tick + 1);
      }
    });
  }, [renderPlugin]);

  useEffect(() => {
    if (renderProvides) {
      const task = renderProvides.renderPage({
        pageIndex,
        options: { scaleFactor, dpr: dpr || window.devicePixelRatio },
      });
      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        setImageUrl(url);
        urlRef.current = url;
      }, ignore);

      return () => {
        if (urlRef.current) {
          URL.revokeObjectURL(urlRef.current);
          urlRef.current = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      };
    }
  }, [pageIndex, scaleFactor, dpr, renderProvides, refreshTick]);

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  return (
    <Fragment>
      {imageUrl && (
        <img
          src={imageUrl}
          onLoad={handleImageLoad}
          {...props}
          style={{
            width: '100%',
            height: '100%',
            ...(style || {}),
          }}
        />
      )}
    </Fragment>
  );
}
