// packages/plugin-render/src/vue/components/render-layer.vue
<script setup lang="ts">
import { ref, watch, onBeforeUnmount } from 'vue';
import { ignore, PdfErrorCode, PdfErrorReason, Task } from '@embedpdf/models';

import { useRenderCapability, useRenderPlugin } from '../hooks';

interface Props {
  pageIndex: number;
  scaleFactor?: number;
  dpr?: number;
}

const props = withDefaults(defineProps<Props>(), {
  scaleFactor: 1,
});

const { provides: renderProvides } = useRenderCapability();
const { plugin: renderPlugin } = useRenderPlugin();

const imageUrl = ref<string | null>(null);
const refreshTick = ref(0);

let currentBlobUrl: string | null = null;
let currentTask: Task<Blob, PdfErrorReason> | null = null;

/* ------------------------------------------ */
/* Helper function to abort current task */
/* ------------------------------------------ */
function abortCurrentTask() {
  if (currentTask && !currentBlobUrl) {
    currentTask.abort({
      code: PdfErrorCode.Cancelled,
      message: 'canceled render task',
    });
  }
}

/* ------------------------------------------ */
/* render whenever pageIndex/scale/dpr/tick change */
/* ------------------------------------------ */
function revoke() {
  if (currentBlobUrl) {
    URL.revokeObjectURL(currentBlobUrl);
    currentBlobUrl = null;
  }
}

function startRender() {
  abortCurrentTask();
  revoke();
  imageUrl.value = null;
  currentTask = null;

  if (!renderProvides.value) return;

  const task = renderProvides.value.renderPage({
    pageIndex: props.pageIndex,
    options: {
      scaleFactor: props.scaleFactor,
      dpr: props.dpr || window.devicePixelRatio,
    },
  });

  currentTask = task;

  task.wait((blob) => {
    currentBlobUrl = URL.createObjectURL(blob);
    imageUrl.value = currentBlobUrl;
    currentTask = null;
  }, ignore);
}

// Watch for external refresh events
watch(
  renderPlugin,
  (pluginInstance, _, onCleanup) => {
    if (pluginInstance) {
      const unsubscribe = pluginInstance.onRefreshPages((pages: number[]) => {
        if (pages.includes(props.pageIndex)) {
          refreshTick.value++;
        }
      });
      onCleanup(unsubscribe);
    }
  },
  { immediate: true },
);

// Watch for changes that require a re-render
watch(
  () => [props.pageIndex, props.scaleFactor, props.dpr, renderProvides.value, refreshTick.value],
  startRender,
  { immediate: true },
);

/* ------------------------------------------ */
onBeforeUnmount(() => {
  abortCurrentTask();
  revoke();
});
</script>

<template>
  <img v-if="imageUrl" :src="imageUrl" :style="{ width: '100%', height: '100%' }" @load="revoke" />
</template>

// packages/plugin-render/src/shared/components/render-layer.tsx
import { Fragment, useEffect, useRef, useState } from '@framework';
import type { CSSProperties, HTMLAttributes } from '@framework';

import { ignore, PdfErrorCode } from '@embedpdf/models';

import { useRenderCapability, useRenderPlugin } from '../hooks/use-render';

type RenderLayerProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  pageIndex: number;
  scaleFactor?: number;
  dpr?: number;
  style?: CSSProperties;
};

export function RenderLayer({
  pageIndex,
  scaleFactor = 1,
  dpr,
  style,
  ...props
}: RenderLayerProps) {
  const { provides: renderProvides } = useRenderCapability();
  const { plugin: renderPlugin } = useRenderPlugin();

  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);
  const [refreshTick, setRefreshTick] = useState(0);

  useEffect(() => {
    if (!renderPlugin) return;
    return renderPlugin.onRefreshPages((pages) => {
      if (pages.includes(pageIndex)) {
        setRefreshTick((tick) => tick + 1);
      }
    });
  }, [renderPlugin]);

  useEffect(() => {
    if (renderProvides) {
      const task = renderProvides.renderPage({
        pageIndex,
        options: { scaleFactor, dpr: dpr || window.devicePixelRatio },
      });
      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        setImageUrl(url);
        urlRef.current = url;
      }, ignore);

      return () => {
        if (urlRef.current) {
          URL.revokeObjectURL(urlRef.current);
          urlRef.current = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      };
    }
  }, [pageIndex, scaleFactor, dpr, renderProvides, refreshTick]);

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  return (
    <Fragment>
      {imageUrl && (
        <img
          src={imageUrl}
          onLoad={handleImageLoad}
          {...props}
          style={{
            width: '100%',
            height: '100%',
            ...(style || {}),
          }}
        />
      )}
    </Fragment>
  );
}
