// packages/plugin-annotation/src/shared/components/text-markup/highlight.tsx
import { CSSProperties, MouseEvent } from '@framework';
import { Rect } from '@embedpdf/models';

type HighlightProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Highlight({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: HighlightProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';

  return (
    <>
      {segmentRects.map((b, i) => (
        <div
          key={i}
          onPointerDown={onClick}
          style={{
            position: 'absolute',
            left: (rect ? b.origin.x - rect.origin.x : b.origin.x) * scale,
            top: (rect ? b.origin.y - rect.origin.y : b.origin.y) * scale,
            width: b.size.width * scale,
            height: b.size.height * scale,
            background: appearanceActive ? 'transparent' : resolvedColor,
            opacity: appearanceActive ? undefined : opacity,
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : undefined,
            ...style,
          }}
        />
      ))}
    </>
  );
}

// packages/plugin-annotation/src/vue/components/text-markup/highlight.vue
<template>
  <div
    v-for="(b, i) in segmentRects"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      left: `${(rect ? b.origin.x - rect.origin.x : b.origin.x) * scale}px`,
      top: `${(rect ? b.origin.y - rect.origin.y : b.origin.y) * scale}px`,
      width: `${b.size.width * scale}px`,
      height: `${b.size.height * scale}px`,
      background: appearanceActive ? 'transparent' : resolvedColor,
      opacity: appearanceActive ? undefined : opacity,
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : undefined,
    }"
  ></div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Rect } from '@embedpdf/models';

const props = withDefaults(
  defineProps<{
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    /** When true, AP image provides the visual; only render hit area */
    appearanceActive?: boolean;
  }>(),
  {
    opacity: 0.5,
    appearanceActive: false,
  },
);

const resolvedColor = computed(() => props.strokeColor ?? '#FFFF00');
</script>
