// packages/plugin-annotation/src/shared/components/text-markup/squiggly.tsx
import { CSSProperties, MouseEvent } from '@framework';
import { Rect } from '@embedpdf/models';

type SquigglyProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Squiggly({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: SquigglyProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';
  const amplitude = 2 * scale; // wave height
  const period = 6 * scale; // wave length

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${period}" height="${amplitude * 2}" viewBox="0 0 ${period} ${amplitude * 2}">
      <path d="M0 ${amplitude} Q ${period / 4} 0 ${period / 2} ${amplitude} T ${period} ${amplitude}"
            fill="none" stroke="${resolvedColor}" stroke-width="${amplitude}" stroke-linecap="round"/>
    </svg>`;

  // Completely escape the SVG markup
  const svgDataUri = `url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`;

  return (
    <>
      {segmentRects.map((r, i) => (
        <div
          key={i}
          onPointerDown={onClick}
          style={{
            position: 'absolute',
            left: (rect ? r.origin.x - rect.origin.x : r.origin.x) * scale,
            top: (rect ? r.origin.y - rect.origin.y : r.origin.y) * scale,
            width: r.size.width * scale,
            height: r.size.height * scale,
            background: 'transparent',
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : 0,
            ...style,
          }}
        >
          {/* Visual -- hidden when AP active, never interactive */}
          {!appearanceActive && (
            <div
              style={{
                position: 'absolute',
                left: 0,
                bottom: 0,
                width: '100%',
                height: amplitude * 2,
                backgroundImage: svgDataUri,
                backgroundRepeat: 'repeat-x',
                backgroundSize: `${period}px ${amplitude * 2}px`,
                opacity: opacity,
                pointerEvents: 'none',
              }}
            />
          )}
        </div>
      ))}
    </>
  );
}

// packages/plugin-annotation/src/vue/components/text-markup/squiggly.vue
<template>
  <div
    v-for="(r, i) in segmentRects"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      left: `${(rect ? r.origin.x - rect.origin.x : r.origin.x) * scale}px`,
      top: `${(rect ? r.origin.y - rect.origin.y : r.origin.y) * scale}px`,
      width: `${r.size.width * scale}px`,
      height: `${r.size.height * scale}px`,
      background: 'transparent',
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : 0,
    }"
  >
    <!-- Visual -- hidden when AP active, never interactive -->
    <div
      v-if="!appearanceActive"
      :style="{
        position: 'absolute',
        left: 0,
        bottom: 0,
        width: '100%',
        height: `${amplitude * 2}px`,
        backgroundImage: svgDataUri,
        backgroundRepeat: 'repeat-x',
        backgroundSize: `${period}px ${amplitude * 2}px`,
        opacity: opacity,
        pointerEvents: 'none',
      }"
    />
  </div>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Rect } from '@embedpdf/models';

const props = withDefaults(
  defineProps<{
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    /** When true, AP image provides the visual; only render hit area */
    appearanceActive?: boolean;
  }>(),
  {
    opacity: 0.5,
    appearanceActive: false,
  },
);

const resolvedColor = computed(() => props.strokeColor ?? '#FFFF00');
const amplitude = computed(() => 2 * props.scale);
const period = computed(() => 6 * props.scale);

const svgDataUri = computed(() => {
  const amp = amplitude.value;
  const per = period.value;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${per}" height="${
    amp * 2
  }" viewBox="0 0 ${per} ${amp * 2}">
    <path d="M0 ${amp} Q ${per / 4} 0 ${per / 2} ${amp} T ${per} ${amp}"
          fill="none" stroke="${resolvedColor.value}" stroke-width="${amp}" stroke-linecap="round"/>
  </svg>`;
  return `url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`;
});
</script>
