// packages/plugin-redaction/src/svelte/components/highlight.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface HighlightProps {
    color?: string;
    opacity?: number;
    border?: string;
    rects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent) => void;
    style?: string;
  }

  let {
    color = '#FFFF00',
    opacity = 1,
    border = '1px solid red',
    rects,
    rect,
    scale,
    onClick,
    style = '',
  }: HighlightProps = $props();

  // Rename rect to boundingRect for clarity
  const boundingRect = $derived(rect);
</script>

{#each rects as b, i (i)}
  <div
    onpointerdown={onClick}
    style:position="absolute"
    style:border
    style:left={`${(boundingRect ? b.origin.x - boundingRect.origin.x : b.origin.x) * scale}px`}
    style:top={`${(boundingRect ? b.origin.y - boundingRect.origin.y : b.origin.y) * scale}px`}
    style:width={`${b.size.width * scale}px`}
    style:height={`${b.size.height * scale}px`}
    style:background={color}
    style:opacity
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? '1' : undefined}
    {style}
  ></div>
{/each}

// packages/plugin-redaction/src/vue/components/highlight.vue
<template>
  <div
    v-for="(rect, i) in rects"
    :key="i"
    @pointerdown="onClick"
    :style="{
      position: 'absolute',
      border,
      left: `${(boundingRect ? rect.origin.x - boundingRect.origin.x : rect.origin.x) * scale}px`,
      top: `${(boundingRect ? rect.origin.y - boundingRect.origin.y : rect.origin.y) * scale}px`,
      width: `${rect.size.width * scale}px`,
      height: `${rect.size.height * scale}px`,
      background: color,
      opacity: opacity,
      pointerEvents: onClick ? 'auto' : 'none',
      cursor: onClick ? 'pointer' : 'default',
      zIndex: onClick ? 1 : undefined,
    }"
    v-bind="$attrs"
  />
</template>

<script setup lang="ts">
import type { Rect } from '@embedpdf/models';

interface HighlightProps {
  color?: string;
  opacity?: number;
  border?: string;
  rects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: PointerEvent) => void;
}

const props = withDefaults(defineProps<HighlightProps>(), {
  color: '#FFFF00',
  opacity: 1,
  border: '1px solid red',
});

// Rename rect to boundingRect for clarity in template
const boundingRect = props.rect;
</script>
