// packages/plugin-redaction/src/shared/components/pending-redactions.tsx
import { Fragment, useEffect, useState, useCallback, MouseEvent, TouchEvent } from '@framework';
import { CounterRotate } from '@embedpdf/utils/@framework';
import { useRedactionCapability } from '../hooks';
import { RedactionItem } from '@embedpdf/plugin-redaction';
import { Highlight } from './highlight';
import { SelectionMenuProps } from './types';
import { Rotation } from '@embedpdf/models';

interface PendingRedactionsProps {
  pageIndex: number;
  scale: number;
  rotation: Rotation;
  bboxStroke?: string;
  selectionMenu?: (props: SelectionMenuProps) => JSX.Element;
}

export function PendingRedactions({
  pageIndex,
  scale,
  bboxStroke = 'rgba(0,0,0,0.8)',
  rotation = Rotation.Degree0,
  selectionMenu,
}: PendingRedactionsProps) {
  const { provides: redaction } = useRedactionCapability();
  const [items, setItems] = useState<RedactionItem[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  useEffect(() => {
    if (!redaction) return;
    const off1 = redaction.onPendingChange((map) => setItems(map[pageIndex] ?? []));
    const off2 = redaction.onSelectionChange((sel) => {
      setSelectedId(sel && sel.page === pageIndex ? sel.id : null);
    });
    return () => {
      off1?.();
      off2?.();
    };
  }, [redaction, pageIndex]);

  const select = useCallback(
    (e: MouseEvent | TouchEvent, id: string) => {
      e.stopPropagation();
      if (!redaction) return;
      redaction.selectPending(pageIndex, id);
    },
    [redaction, pageIndex],
  );

  if (!items.length) return null;

  return (
    <div style={{ position: 'absolute', inset: 0, pointerEvents: 'none' }}>
      {items.map((it) => {
        if (it.kind === 'area') {
          const r = it.rect;
          return (
            <Fragment key={it.id}>
              <div
                style={{
                  position: 'absolute',
                  left: r.origin.x * scale,
                  top: r.origin.y * scale,
                  width: r.size.width * scale,
                  height: r.size.height * scale,
                  background: 'transparent',
                  outline: selectedId === it.id ? `1px solid ${bboxStroke}` : 'none',
                  outlineOffset: '2px',
                  border: `1px solid red`,
                  pointerEvents: 'auto',
                  cursor: 'pointer',
                }}
                onPointerDown={(e) => select(e, it.id)}
                onTouchStart={(e) => select(e, it.id)}
              />
              <CounterRotate
                rect={{
                  origin: { x: r.origin.x * scale, y: r.origin.y * scale },
                  size: { width: r.size.width * scale, height: r.size.height * scale },
                }}
                rotation={rotation}
              >
                {({ rect, menuWrapperProps }) =>
                  selectionMenu &&
                  selectionMenu({
                    item: it,
                    selected: selectedId === it.id,
                    pageIndex,
                    menuWrapperProps,
                    rect,
                  })
                }
              </CounterRotate>
            </Fragment>
          );
        }
        // kind === 'text' → draw bounding box; inner rects are not drawn here to avoid clutter.
        const b = it.boundingRect;
        return (
          <Fragment key={it.id}>
            <div
              style={{
                position: 'absolute',
                left: b.origin.x * scale,
                top: b.origin.y * scale,
                width: b.size.width * scale,
                height: b.size.height * scale,
                background: 'transparent',
                outline: selectedId === it.id ? `1px solid ${bboxStroke}` : 'none',
                outlineOffset: '2px',
                pointerEvents: 'auto',
                cursor: selectedId === it.id ? 'pointer' : 'default',
              }}
            >
              <Highlight
                rect={b}
                rects={it.rects}
                color="transparent"
                border="1px solid red"
                scale={scale}
                onClick={(e) => select(e, it.id)}
              />
            </div>
            <CounterRotate
              rect={{
                origin: { x: b.origin.x * scale, y: b.origin.y * scale },
                size: { width: b.size.width * scale, height: b.size.height * scale },
              }}
              rotation={rotation}
            >
              {({ rect, menuWrapperProps }) =>
                selectionMenu &&
                selectionMenu({
                  item: it,
                  selected: selectedId === it.id,
                  pageIndex,
                  menuWrapperProps,
                  rect,
                })
              }
            </CounterRotate>
          </Fragment>
        );
      })}
    </div>
  );
}

// packages/plugin-redaction/src/vue/components/pending-redactions.vue
<template>
  <div v-if="items.length" :style="{ position: 'absolute', inset: 0, pointerEvents: 'none' }">
    <template v-for="item in items" :key="item.id">
      <!-- Area redaction -->
      <template v-if="item.kind === 'area'">
        <div
          :style="{
            position: 'absolute',
            left: `${item.rect.origin.x * scale}px`,
            top: `${item.rect.origin.y * scale}px`,
            width: `${item.rect.size.width * scale}px`,
            height: `${item.rect.size.height * scale}px`,
            background: 'transparent',
            outline: selectedId === item.id ? `1px solid ${bboxStroke}` : 'none',
            outlineOffset: '2px',
            border: `1px solid red`,
            pointerEvents: 'auto',
            cursor: 'pointer',
          }"
          @pointerdown="(e: PointerEvent) => select(e, item.id)"
          @touchstart="(e: TouchEvent) => select(e, item.id)"
        />
        <CounterRotate
          :rect="{
            origin: { x: item.rect.origin.x * scale, y: item.rect.origin.y * scale },
            size: { width: item.rect.size.width * scale, height: item.rect.size.height * scale },
          }"
          :rotation="rotation"
        >
          <template #default="{ rect, menuWrapperProps }">
            <slot
              name="selection-menu"
              :item="item"
              :selected="selectedId === item.id"
              :page-index="pageIndex"
              :menu-wrapper-props="menuWrapperProps"
              :rect="rect"
            />
          </template>
        </CounterRotate>
      </template>

      <!-- Text redaction -->
      <template v-else>
        <div
          :style="{
            position: 'absolute',
            left: `${item.boundingRect.origin.x * scale}px`,
            top: `${item.boundingRect.origin.y * scale}px`,
            width: `${item.boundingRect.size.width * scale}px`,
            height: `${item.boundingRect.size.height * scale}px`,
            background: 'transparent',
            outline: selectedId === item.id ? `1px solid ${bboxStroke}` : 'none',
            outlineOffset: '2px',
            pointerEvents: 'auto',
            cursor: selectedId === item.id ? 'pointer' : 'default',
          }"
        >
          <Highlight
            :rect="item.boundingRect"
            :rects="item.rects"
            color="transparent"
            border="1px solid red"
            :scale="scale"
            :on-click="(e: PointerEvent | TouchEvent) => select(e, item.id)"
          />
        </div>
        <CounterRotate
          :rect="{
            origin: {
              x: item.boundingRect.origin.x * scale,
              y: item.boundingRect.origin.y * scale,
            },
            size: {
              width: item.boundingRect.size.width * scale,
              height: item.boundingRect.size.height * scale,
            },
          }"
          :rotation="rotation"
        >
          <template #default="{ rect, menuWrapperProps }">
            <slot
              name="selection-menu"
              :item="item"
              :selected="selectedId === item.id"
              :page-index="pageIndex"
              :menu-wrapper-props="menuWrapperProps"
              :rect="rect"
            />
          </template>
        </CounterRotate>
      </template>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { CounterRotate } from '@embedpdf/utils/vue';
import type { Rotation } from '@embedpdf/models';
import type { RedactionItem } from '@embedpdf/plugin-redaction';
import { useRedactionCapability } from '../hooks/use-redaction';
import Highlight from './highlight.vue';

interface PendingRedactionsProps {
  pageIndex: number;
  scale: number;
  rotation?: Rotation;
  bboxStroke?: string;
}

const props = withDefaults(defineProps<PendingRedactionsProps>(), {
  rotation: 0,
  bboxStroke: 'rgba(0,0,0,0.8)',
});

const { provides: redaction } = useRedactionCapability();
const items = ref<RedactionItem[]>([]);
const selectedId = ref<string | null>(null);

const select = (e: PointerEvent | TouchEvent, id: string) => {
  e.stopPropagation();
  if (!redaction.value) return;
  redaction.value.selectPending(props.pageIndex, id);
};

let unsubscribePending: (() => void) | undefined;
let unsubscribeSelection: (() => void) | undefined;

onMounted(() => {
  if (!redaction.value) return;

  unsubscribePending = redaction.value.onPendingChange((map) => {
    items.value = map[props.pageIndex] ?? [];
  });

  unsubscribeSelection = redaction.value.onSelectionChange((sel) => {
    selectedId.value = sel && sel.page === props.pageIndex ? sel.id : null;
  });
});

onUnmounted(() => {
  unsubscribePending?.();
  unsubscribeSelection?.();
});
</script>
