// packages/plugin-form/src/vue/components/fill-mode/combobox-fill-mode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { PdfWidgetAnnoObject } from '@embedpdf/models';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import RenderWidget from '../render-widget.vue';
import ComboboxField from '../fields/combobox-field.vue';
import type { ComboboxFieldProps } from '../../../shared/components/types';

const props = defineProps<AnnotationRendererProps<PdfWidgetAnnoObject>>();
const ws = useFormWidgetState(props);
const { state: formState } = useFormDocumentState(() => props.documentId);

const wrapperEl = ref<HTMLDivElement | null>(null);
const selectEl = ref<HTMLElement | null>(null);

const isFocused = computed(() => formState.value.selectedFieldId === ws.annotation.value.id);

watch(isFocused, (focused) => {
  if (focused && wrapperEl.value && !wrapperEl.value.contains(document.activeElement)) {
    (selectEl.value ?? wrapperEl.value).focus();
  }
});

function handleFocus() {
  ws.scope.value?.selectField(ws.annotation.value.id);
}

function handleBlur() {
  requestAnimationFrame(() => {
    if (wrapperEl.value?.contains(document.activeElement)) return;
    if (ws.scope.value?.getSelectedFieldId() === ws.annotation.value.id) {
      ws.scope.value?.deselectField();
    }
  });
}

function selectInputRef(el: HTMLElement | null) {
  selectEl.value = el;
}
</script>

<template>
  <div
    ref="wrapperEl"
    @focus="handleFocus"
    @blur="handleBlur"
    :style="{
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      cursor: ws.isReadOnly.value ? 'default' : 'pointer',
      pointerEvents: 'auto',
      outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
      outlineOffset: '-2px',
    }"
  >
    <RenderWidget
      :pageIndex="ws.pageIndex.value"
      :annotation="ws.annotation.value"
      :scaleFactor="ws.scale.value"
      :renderKey="ws.renderKey.value"
      :style="{ pointerEvents: 'none' }"
    />
    <ComboboxField
      :annotation="ws.annotation.value as ComboboxFieldProps['annotation']"
      :scale="ws.scale.value"
      :pageIndex="ws.pageIndex.value"
      :isEditable="true"
      :onChangeField="ws.handleChangeField"
      :inputRef="selectInputRef"
    />
  </div>
</template>

// packages/plugin-form/src/shared/components/fill-mode/combobox-fill-mode.tsx
import { useCallback, useEffect, useRef } from '@framework';
import { PdfWidgetAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '@embedpdf/plugin-annotation/@framework';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import { RenderWidget } from '../render-widget';
import { ComboboxField } from '../fields/combobox';
import { ComboboxFieldProps } from '../types';

export function ComboboxFillMode(props: AnnotationRendererProps<PdfWidgetAnnoObject>) {
  const { annotation, scale, pageIndex, scope, handleChangeField, renderKey, isReadOnly } =
    useFormWidgetState(props);
  const formState = useFormDocumentState(props.documentId);
  const wrapperRef = useRef<HTMLDivElement>(null);
  const selectElRef = useRef<HTMLElement | null>(null);

  const isFocused = formState.selectedFieldId === annotation.id;

  useEffect(() => {
    if (isFocused && wrapperRef.current && !wrapperRef.current.contains(document.activeElement)) {
      (selectElRef.current ?? wrapperRef.current).focus();
    }
  }, [isFocused]);

  const handleFocus = useCallback(() => {
    scope?.selectField(annotation.id);
  }, [scope, annotation.id]);

  const handleBlur = useCallback(() => {
    requestAnimationFrame(() => {
      if (wrapperRef.current?.contains(document.activeElement)) return;
      if (scope?.getSelectedFieldId() === annotation.id) {
        scope?.deselectField();
      }
    });
  }, [scope, annotation.id]);

  const selectInputRef = useCallback((el: HTMLElement | null) => {
    selectElRef.current = el;
  }, []);

  return (
    <div
      ref={wrapperRef}
      onFocus={handleFocus}
      onBlur={handleBlur}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        cursor: isReadOnly ? 'default' : 'pointer',
        pointerEvents: 'auto',
        outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
        outlineOffset: -2,
      }}
    >
      <RenderWidget
        pageIndex={pageIndex}
        annotation={annotation}
        scaleFactor={scale}
        renderKey={renderKey}
        style={{ pointerEvents: 'none' }}
      />
      <ComboboxField
        annotation={annotation as ComboboxFieldProps['annotation']}
        scale={scale}
        pageIndex={pageIndex}
        isEditable={true}
        onChangeField={handleChangeField}
        inputRef={selectInputRef}
      />
    </div>
  );
}
