// packages/plugin-form/src/vue/components/fill-mode/listbox-fill-mode.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { PdfWidgetAnnoObject } from '@embedpdf/models';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import RenderWidget from '../render-widget.vue';
import ListboxField from '../fields/listbox-field.vue';
import type { ListboxFieldProps } from '../../../shared/components/types';

const props = defineProps<AnnotationRendererProps<PdfWidgetAnnoObject>>();
const ws = useFormWidgetState(props);
const { state: formState } = useFormDocumentState(() => props.documentId);

const editing = ref(false);
const wrapperEl = ref<HTMLDivElement | null>(null);

const isFocused = computed(() => formState.value.selectedFieldId === ws.annotation.value.id);

watch(isFocused, (focused) => {
  if (focused && wrapperEl.value && !wrapperEl.value.contains(document.activeElement)) {
    wrapperEl.value.focus();
  }
});

function handleFocus() {
  if (ws.isReadOnly.value) return;
  ws.scope.value?.selectField(ws.annotation.value.id);
  editing.value = true;
}

function handleBlur() {
  requestAnimationFrame(() => {
    if (wrapperEl.value?.contains(document.activeElement)) return;
    editing.value = false;
    if (ws.scope.value?.getSelectedFieldId() === ws.annotation.value.id) {
      ws.scope.value?.deselectField();
    }
  });
}
</script>

<template>
  <div
    ref="wrapperEl"
    :tabindex="ws.isReadOnly.value ? -1 : 0"
    @focus="handleFocus"
    @blur="handleBlur"
    :style="{
      width: '100%',
      height: '100%',
      overflow: 'hidden',
      cursor: ws.isReadOnly.value ? 'default' : 'pointer',
      pointerEvents: 'auto',
      outline: isFocused && !editing ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
      outlineOffset: '-2px',
    }"
  >
    <ListboxField
      :annotation="ws.annotation.value as ListboxFieldProps['annotation']"
      :scale="ws.scale.value"
      :pageIndex="ws.pageIndex.value"
      :isEditable="true"
      :onChangeField="ws.handleChangeField"
    />
    <RenderWidget
      v-if="!editing"
      :pageIndex="ws.pageIndex.value"
      :annotation="ws.annotation.value"
      :scaleFactor="ws.scale.value"
      :renderKey="ws.renderKey.value"
      :style="{ pointerEvents: 'none' }"
    />
  </div>
</template>

// packages/plugin-form/src/shared/components/fill-mode/listbox-fill-mode.tsx
import { useCallback, useEffect, useRef, useState } from '@framework';
import { PdfWidgetAnnoObject } from '@embedpdf/models';
import { AnnotationRendererProps } from '@embedpdf/plugin-annotation/@framework';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import { RenderWidget } from '../render-widget';
import { ListboxField } from '../fields/listbox';
import { ListboxFieldProps } from '../types';

export function ListboxFillMode(props: AnnotationRendererProps<PdfWidgetAnnoObject>) {
  const { annotation, scale, pageIndex, scope, handleChangeField, renderKey, isReadOnly } =
    useFormWidgetState(props);
  const formState = useFormDocumentState(props.documentId);
  const [editing, setEditing] = useState(false);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const isFocused = formState.selectedFieldId === annotation.id;

  useEffect(() => {
    if (isFocused && wrapperRef.current && !wrapperRef.current.contains(document.activeElement)) {
      wrapperRef.current.focus();
    }
  }, [isFocused]);

  const handleFocus = useCallback(() => {
    if (isReadOnly) return;
    scope?.selectField(annotation.id);
    setEditing(true);
  }, [isReadOnly, scope, annotation.id]);

  const handleBlur = useCallback(() => {
    requestAnimationFrame(() => {
      if (wrapperRef.current?.contains(document.activeElement)) return;
      setEditing(false);
      if (scope?.getSelectedFieldId() === annotation.id) {
        scope?.deselectField();
      }
    });
  }, [scope, annotation.id]);

  return (
    <div
      ref={wrapperRef}
      tabIndex={isReadOnly ? -1 : 0}
      onFocus={handleFocus}
      onBlur={handleBlur}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        cursor: isReadOnly ? 'default' : 'pointer',
        pointerEvents: 'auto',
        outline: isFocused && !editing ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
        outlineOffset: -2,
      }}
    >
      <ListboxField
        annotation={annotation as ListboxFieldProps['annotation']}
        scale={scale}
        pageIndex={pageIndex}
        isEditable={true}
        onChangeField={handleChangeField}
      />
      {!editing && (
        <RenderWidget
          pageIndex={pageIndex}
          annotation={annotation}
          scaleFactor={scale}
          renderKey={renderKey}
          style={{ pointerEvents: 'none' }}
        />
      )}
    </div>
  );
}
