// packages/plugin-form/src/svelte/components/fill-mode/RadioButtonFillMode.svelte
<script lang="ts">
  import type { PdfWidgetAnnoObject } from '@embedpdf/models';
  import { isWidgetChecked } from '@embedpdf/models';
  import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/svelte';
  import { useFormWidgetState } from '../../hooks/use-form-widget-state.svelte';
  import { useFormDocumentState } from '../../hooks/use-form.svelte';
  import RenderWidget from '../RenderWidget.svelte';

  let props: AnnotationRendererProps<PdfWidgetAnnoObject> = $props();
  const widgetState = useFormWidgetState(props);
  const formDocState = useFormDocumentState(() => props.documentId);

  let wrapperEl: HTMLDivElement;

  const isFocused = $derived(formDocState.state.selectedFieldId === widgetState.annotation.id);

  $effect(() => {
    if (isFocused && wrapperEl && document.activeElement !== wrapperEl) {
      wrapperEl.focus();
    }
  });

  function selectRadio() {
    if (widgetState.isReadOnly) return;
    if (!isWidgetChecked(widgetState.annotation) && widgetState.annotation.exportValue) {
      widgetState.handleChangeField({
        ...widgetState.field,
        value: widgetState.annotation.exportValue,
      });
    }
  }

  function handleClick() {
    if (widgetState.isReadOnly) return;
    widgetState.scope?.selectField(widgetState.annotation.id);
    selectRadio();
  }

  function handleFocus() {
    if (widgetState.isReadOnly) return;
    widgetState.scope?.selectField(widgetState.annotation.id);
  }

  function handleBlur() {
    if (widgetState.scope?.getSelectedFieldId() === widgetState.annotation.id) {
      widgetState.scope?.deselectField();
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === ' ' || e.key === 'Enter') {
      e.preventDefault();
      selectRadio();
    }
  }
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  bind:this={wrapperEl}
  tabindex={widgetState.isReadOnly ? -1 : 0}
  onclick={handleClick}
  onfocus={handleFocus}
  onblur={handleBlur}
  onkeydown={handleKeyDown}
  style="width: 100%; height: 100%; overflow: hidden; cursor: {widgetState.isReadOnly
    ? 'default'
    : 'pointer'}; pointer-events: auto; outline: {isFocused
    ? '2px solid rgba(66, 133, 244, 0.8)'
    : 'none'}; outline-offset: -2px;"
>
  <RenderWidget
    pageIndex={widgetState.pageIndex}
    annotation={widgetState.annotation}
    scaleFactor={widgetState.scale}
    renderKey={widgetState.renderKey}
    style="pointer-events: none;"
  />
</div>

// packages/plugin-form/src/shared/components/fill-mode/radio-button-fill-mode.tsx
import { useCallback, useEffect, useRef } from '@framework';
import { PdfWidgetAnnoObject, isWidgetChecked } from '@embedpdf/models';
import { AnnotationRendererProps } from '@embedpdf/plugin-annotation/@framework';
import { useFormWidgetState } from '../../hooks/use-form-widget-state';
import { useFormDocumentState } from '../../hooks/use-form';
import { RenderWidget } from '../render-widget';

export function RadioButtonFillMode(props: AnnotationRendererProps<PdfWidgetAnnoObject>) {
  const { annotation, field, scale, pageIndex, scope, handleChangeField, renderKey, isReadOnly } =
    useFormWidgetState(props);
  const formState = useFormDocumentState(props.documentId);
  const wrapperRef = useRef<HTMLDivElement>(null);

  const isFocused = formState.selectedFieldId === annotation.id;

  useEffect(() => {
    if (isFocused && wrapperRef.current && document.activeElement !== wrapperRef.current) {
      wrapperRef.current.focus();
    }
  }, [isFocused]);

  const selectRadio = useCallback(() => {
    if (isReadOnly) return;
    if (!isWidgetChecked(annotation) && annotation.exportValue) {
      handleChangeField({ ...field, value: annotation.exportValue });
    }
  }, [isReadOnly, annotation, field, handleChangeField]);

  const handleClick = useCallback(() => {
    if (isReadOnly) return;
    scope?.selectField(annotation.id);
    selectRadio();
  }, [isReadOnly, scope, annotation.id, selectRadio]);

  const handleFocus = useCallback(() => {
    if (isReadOnly) return;
    scope?.selectField(annotation.id);
  }, [isReadOnly, scope, annotation.id]);

  const handleBlur = useCallback(() => {
    if (scope?.getSelectedFieldId() === annotation.id) {
      scope?.deselectField();
    }
  }, [scope, annotation.id]);

  const handleKeyDown = useCallback(
    (e: { key: string; preventDefault: () => void }) => {
      if (e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        selectRadio();
      }
    },
    [selectRadio],
  );

  return (
    <div
      ref={wrapperRef}
      tabIndex={isReadOnly ? -1 : 0}
      onClick={handleClick}
      onFocus={handleFocus}
      onBlur={handleBlur}
      onKeyDown={handleKeyDown}
      style={{
        width: '100%',
        height: '100%',
        overflow: 'hidden',
        cursor: isReadOnly ? 'default' : 'pointer',
        pointerEvents: 'auto',
        outline: isFocused ? '2px solid rgba(66, 133, 244, 0.8)' : 'none',
        outlineOffset: -2,
      }}
    >
      <RenderWidget
        pageIndex={pageIndex}
        annotation={annotation}
        scaleFactor={scale}
        renderKey={renderKey}
        style={{ pointerEvents: 'none' }}
      />
    </div>
  );
}
