// packages/core/src/svelte/components/EmbedPDF.svelte
<script lang="ts">
    import type {Logger, PdfEngine} from '@embedpdf/models';
    import {type IPlugin, type PluginBatchRegistration, PluginRegistry} from '@embedpdf/core';
    import {type Snippet} from 'svelte';
    import AutoMount from "./AutoMount.svelte";
    import {pdfContext, type PDFContextState} from "../hooks";



    interface EmbedPDFProps {
    /**
     * The PDF engine to use for the PDF viewer.
     */
    engine: PdfEngine;
    /**
     * The logger to use for the PDF viewer.
     */
    logger?: Logger;
    /**
     * The callback to call when the PDF viewer is initialized.
     */
    onInitialized?: (registry: PluginRegistry) => Promise<void>;
    /**
     * The plugins to use for the PDF viewer.
     */
    plugins: PluginBatchRegistration<IPlugin<any>, any>[];
    /**
     * The children to render for the PDF viewer.
     */
    children: Snippet<[PDFContextState]>;
    /**
     * Whether to auto-mount specific non-visual DOM elements from plugins.
     * @default true
     */
    autoMountDomElements?: boolean;
  }

  let {
    engine,
    logger,
    onInitialized,
    plugins,
    children,
    autoMountDomElements = true
  }: EmbedPDFProps = $props();



  let latestInit = onInitialized;


  $effect(() => {
    if (onInitialized) {
      latestInit = onInitialized;
    }
  });

  $effect(() => {
    if (engine || (engine && plugins)) {
      const reg = new PluginRegistry(engine, { logger });
      reg.registerPluginBatch(plugins);

      const initialize = async () => {
        await reg.initialize();

        // if the registry is destroyed, don't do anything
        if (reg.isDestroyed()) {
          return;
        }

        /* always call the *latest* callback */
        await latestInit?.(reg);

        // if the registry is destroyed, don't do anything
        if (reg.isDestroyed()) {
          return;
        }

        reg.pluginsReady().then(() => {
          if (!reg.isDestroyed()) {
            pdfContext.pluginsReady = true;
          }
        });

        // Provide the registry to children via context
        pdfContext.registry = reg;
        pdfContext.isInitializing = false;
      };
      initialize().catch(console.error);

      return () => {
        reg.destroy();
        pdfContext.registry = null;
        pdfContext.isInitializing = false;
        pdfContext.pluginsReady = false;
      };
    }
  });
</script>

{#if pdfContext.pluginsReady && autoMountDomElements}
  <AutoMount {plugins}>{@render children(pdfContext)}</AutoMount>
{:else}
  {@render children(pdfContext)}
{/if}

// packages/core/src/react/components/embed-pdf.tsx
import React, { useState, useEffect, useRef } from 'react';
import { PdfEngine } from '@embedpdf/models';
import { PluginRegistry } from '@embedpdf/core';
import type { IPlugin, PluginBatchRegistration } from '@embedpdf/core';

import { PDFContext, PDFContextState } from '../context';

interface EmbedPDFProps {
  engine: PdfEngine;
  onInitialized?: (registry: PluginRegistry) => Promise<void>;
  plugins: PluginBatchRegistration<IPlugin<any>, any>[];
  children: React.ReactNode | ((state: PDFContextState) => React.ReactNode);
}

export function EmbedPDF({ engine, onInitialized, plugins, children }: EmbedPDFProps) {
  const [registry, setRegistry] = useState<PluginRegistry | null>(null);
  const [isInitializing, setIsInitializing] = useState<boolean>(true);
  const [pluginsReady, setPluginsReady] = useState<boolean>(false);
  const initRef = useRef<EmbedPDFProps['onInitialized']>(onInitialized);

  useEffect(() => {
    initRef.current = onInitialized; // update without triggering re-runs
  }, [onInitialized]);

  useEffect(() => {
    const pdfViewer = new PluginRegistry(engine);
    pdfViewer.registerPluginBatch(plugins);

    const initialize = async () => {
      await pdfViewer.initialize();
      // if the registry is destroyed, don't do anything
      if (pdfViewer.isDestroyed()) {
        return;
      }

      /* always call the *latest* callback */
      await initRef.current?.(pdfViewer);

      // if the registry is destroyed, don't do anything
      if (pdfViewer.isDestroyed()) {
        return;
      }

      pdfViewer.pluginsReady().then(() => {
        if (!pdfViewer.isDestroyed()) {
          setPluginsReady(true);
        }
      });

      // Provide the registry to children via context
      setRegistry(pdfViewer);
      setIsInitializing(false);
    };

    initialize().catch(console.error);

    return () => {
      pdfViewer.destroy();
      setRegistry(null);
      setIsInitializing(true);
      setPluginsReady(false);
    };
  }, [engine, plugins]);

  return (
    <PDFContext.Provider value={{ registry, isInitializing, pluginsReady }}>
      {typeof children === 'function'
        ? children({ registry, isInitializing, pluginsReady })
        : children}
    </PDFContext.Provider>
  );
}
