// packages/plugin-annotation/src/svelte/components/annotations/FreeTextPreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { FreeTextPreviewData } from '@embedpdf/plugin-annotation';

  interface FreeTextPreviewProps {
    data: FreeTextPreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data }: FreeTextPreviewProps = $props();
</script>

<div
  style:width="100%"
  style:height="100%"
  style:border="1px dashed {data.fontColor || '#000000'}"
  style:background-color="transparent"
></div>

// packages/plugin-annotation/src/vue/components/annotations/free-text-preview.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Rect } from '@embedpdf/models';
import { FreeTextPreviewData } from '@embedpdf/plugin-annotation';

const props = defineProps<{
  data: FreeTextPreviewData;
  bounds: Rect;
  scale: number;
}>();

const style = computed(() => ({
  width: '100%',
  height: '100%',
  border: `1px dashed ${props.data.fontColor || '#000000'}`,
  backgroundColor: 'transparent',
}));
</script>

<template>
  <div :style="style" />
</template>
