// packages/plugin-annotation/src/svelte/components/annotations/Line.svelte
<script lang="ts">
  import type { Rect, LinePoints, LineEndings } from '@embedpdf/models';
  import { PdfAnnotationBorderStyle } from '@embedpdf/models';
  import { patching } from '@embedpdf/plugin-annotation';

  const MIN_HIT_AREA_SCREEN_PX = 20;

  interface LineProps {
    color?: string;
    opacity?: number;
    strokeWidth: number;
    strokeColor?: string;
    strokeStyle?: PdfAnnotationBorderStyle;
    strokeDashArray?: number[];
    rect: Rect;
    linePoints: LinePoints;
    lineEndings?: LineEndings;
    scale: number;
    onClick?: (e: MouseEvent) => void;
    isSelected: boolean;
    appearanceActive?: boolean;
  }

  let {
    color = 'transparent',
    opacity = 1,
    strokeWidth,
    strokeColor = '#000000',
    strokeStyle = PdfAnnotationBorderStyle.SOLID,
    strokeDashArray,
    rect,
    linePoints,
    lineEndings,
    scale,
    onClick,
    isSelected,
    appearanceActive = false,
  }: LineProps = $props();

  const x1 = $derived(linePoints.start.x - rect.origin.x);
  const y1 = $derived(linePoints.start.y - rect.origin.y);
  const x2 = $derived(linePoints.end.x - rect.origin.x);
  const y2 = $derived(linePoints.end.y - rect.origin.y);

  const endings = $derived.by(() => {
    const angle = Math.atan2(y2 - y1, x2 - x1);
    return {
      start: patching.createEnding(lineEndings?.start, strokeWidth, angle + Math.PI, x1, y1),
      end: patching.createEnding(lineEndings?.end, strokeWidth, angle, x2, y2),
    };
  });

  const width = $derived(rect.size.width * scale);
  const height = $derived(rect.size.height * scale);
  const hitStrokeWidth = $derived(Math.max(strokeWidth, MIN_HIT_AREA_SCREEN_PX / scale));

  const dash = $derived(
    strokeStyle === PdfAnnotationBorderStyle.DASHED ? strokeDashArray?.join(',') : undefined,
  );
</script>

<svg
  style="position: absolute; z-index: 2; overflow: visible; pointer-events: none;"
  style:width={`${width}px`}
  style:height={`${height}px`}
  {width}
  {height}
  viewBox={`0 0 ${rect.size.width} ${rect.size.height}`}
>
  <!-- Hit area -- always rendered, transparent, wider stroke for mobile -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <line
    {x1}
    {y1}
    {x2}
    {y2}
    stroke="transparent"
    stroke-width={hitStrokeWidth}
    onpointerdown={onClick}
    style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
    style:pointer-events={!onClick ? 'none' : isSelected ? 'none' : 'visibleStroke'}
    style:stroke-linecap="butt"
  />
  {#if endings.start}
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <path
      d={endings.start.d}
      transform={endings.start.transform}
      fill="transparent"
      stroke="transparent"
      stroke-width={hitStrokeWidth}
      onpointerdown={onClick}
      style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
      style:pointer-events={!onClick
        ? 'none'
        : isSelected
          ? 'none'
          : endings.start.filled
            ? 'visible'
            : 'visibleStroke'}
      style:stroke-linecap="butt"
    />
  {/if}
  {#if endings.end}
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <path
      d={endings.end.d}
      transform={endings.end.transform}
      fill="transparent"
      stroke="transparent"
      stroke-width={hitStrokeWidth}
      onpointerdown={onClick}
      style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
      style:pointer-events={!onClick
        ? 'none'
        : isSelected
          ? 'none'
          : endings.end.filled
            ? 'visible'
            : 'visibleStroke'}
      style:stroke-linecap="butt"
    />
  {/if}

  <!-- Visual -- hidden when AP active, never interactive -->
  {#if !appearanceActive}
    <line
      {x1}
      {y1}
      {x2}
      {y2}
      {opacity}
      style:pointer-events="none"
      style:stroke={strokeColor}
      style:stroke-width={strokeWidth}
      style:stroke-linecap="butt"
      style:stroke-dasharray={dash}
    />
    {#if endings.start}
      <path
        d={endings.start.d}
        transform={endings.start.transform}
        stroke={strokeColor}
        fill={endings.start.filled ? color : 'none'}
        style:pointer-events="none"
        style:stroke-width={strokeWidth}
        style:stroke-linecap="butt"
        style:stroke-dasharray={dash}
      />
    {/if}
    {#if endings.end}
      <path
        d={endings.end.d}
        transform={endings.end.transform}
        stroke={strokeColor}
        fill={endings.end.filled ? color : 'none'}
        style:pointer-events="none"
        style:stroke-width={strokeWidth}
        style:stroke-linecap="butt"
        style:stroke-dasharray={dash}
      />
    {/if}
  {/if}
</svg>

// packages/plugin-annotation/src/vue/components/annotations/line.vue
<template>
  <svg
    :style="{
      position: 'absolute',
      width: `${width}px`,
      height: `${height}px`,
      pointerEvents: 'none',
      zIndex: 2,
      overflow: 'visible',
    }"
    :width="width"
    :height="height"
    :viewBox="`0 0 ${rect.size.width} ${rect.size.height}`"
  >
    <!-- Hit area -- always rendered, transparent, wider stroke for mobile -->
    <line
      :x1="localLine.x1"
      :y1="localLine.y1"
      :x2="localLine.x2"
      :y2="localLine.y2"
      stroke="transparent"
      :stroke-width="hitStrokeWidth"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick ? 'none' : isSelected ? 'none' : 'visibleStroke',
        strokeLinecap: 'butt',
      }"
    />
    <path
      v-if="endings.start"
      :d="endings.start.d"
      :transform="endings.start.transform"
      fill="transparent"
      stroke="transparent"
      :stroke-width="hitStrokeWidth"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick
          ? 'none'
          : isSelected
            ? 'none'
            : endings.start.filled
              ? 'visible'
              : 'visibleStroke',
        strokeLinecap: 'butt',
      }"
    />
    <path
      v-if="endings.end"
      :d="endings.end.d"
      :transform="endings.end.transform"
      fill="transparent"
      stroke="transparent"
      :stroke-width="hitStrokeWidth"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick
          ? 'none'
          : isSelected
            ? 'none'
            : endings.end.filled
              ? 'visible'
              : 'visibleStroke',
        strokeLinecap: 'butt',
      }"
    />

    <!-- Visual -- hidden when AP active, never interactive -->
    <template v-if="!appearanceActive">
      <line
        :x1="localLine.x1"
        :y1="localLine.y1"
        :x2="localLine.x2"
        :y2="localLine.y2"
        :opacity="opacity"
        :style="{
          pointerEvents: 'none',
          stroke: strokeColor,
          strokeWidth: strokeWidth,
          strokeLinecap: 'butt',
          ...(strokeStyle === PdfAnnotationBorderStyle.DASHED && {
            strokeDasharray: strokeDashArray?.join(','),
          }),
        }"
      />
      <path
        v-if="endings.start"
        :d="endings.start.d"
        :transform="endings.start.transform"
        :stroke="strokeColor"
        :fill="endings.start.filled ? color : 'none'"
        :style="{
          pointerEvents: 'none',
          strokeWidth: strokeWidth,
          strokeLinecap: 'butt',
          ...(strokeStyle === PdfAnnotationBorderStyle.DASHED && {
            strokeDasharray: strokeDashArray?.join(','),
          }),
        }"
      />
      <path
        v-if="endings.end"
        :d="endings.end.d"
        :transform="endings.end.transform"
        :stroke="strokeColor"
        :fill="endings.end.filled ? color : 'none'"
        :style="{
          pointerEvents: 'none',
          strokeWidth: strokeWidth,
          strokeLinecap: 'butt',
          ...(strokeStyle === PdfAnnotationBorderStyle.DASHED && {
            strokeDasharray: strokeDashArray?.join(','),
          }),
        }"
      />
    </template>
  </svg>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Rect, LinePoints, LineEndings, PdfAnnotationBorderStyle } from '@embedpdf/models';
import { patching } from '@embedpdf/plugin-annotation';

const MIN_HIT_AREA_SCREEN_PX = 20;

const props = withDefaults(
  defineProps<{
    color?: string;
    opacity?: number;
    strokeWidth: number;
    strokeColor?: string;
    strokeStyle?: PdfAnnotationBorderStyle;
    strokeDashArray?: number[];
    rect: Rect;
    linePoints: LinePoints;
    lineEndings?: LineEndings;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    isSelected: boolean;
    appearanceActive?: boolean;
  }>(),
  {
    color: 'transparent',
    opacity: 1,
    strokeColor: '#000000',
    strokeStyle: PdfAnnotationBorderStyle.SOLID,
    appearanceActive: false,
  },
);

const localLine = computed(() => ({
  x1: props.linePoints.start.x - props.rect.origin.x,
  y1: props.linePoints.start.y - props.rect.origin.y,
  x2: props.linePoints.end.x - props.rect.origin.x,
  y2: props.linePoints.end.y - props.rect.origin.y,
}));

const endings = computed(() => {
  const { x1, y1, x2, y2 } = localLine.value;
  const angle = Math.atan2(y2 - y1, x2 - x1);
  return {
    start: patching.createEnding(
      props.lineEndings?.start,
      props.strokeWidth,
      angle + Math.PI,
      x1,
      y1,
    ),
    end: patching.createEnding(props.lineEndings?.end, props.strokeWidth, angle, x2, y2),
  };
});

const width = computed(() => props.rect.size.width * props.scale);
const height = computed(() => props.rect.size.height * props.scale);
const hitStrokeWidth = computed(() =>
  Math.max(props.strokeWidth, MIN_HIT_AREA_SCREEN_PX / props.scale),
);
</script>
