// packages/plugin-annotation/src/vue/components/annotations/caret.vue
<template>
  <svg
    :style="{
      position: 'absolute',
      width: svgWidth,
      height: svgHeight,
      pointerEvents: 'none',
      zIndex: 2,
    }"
    :width="svgWidth"
    :height="svgHeight"
    :viewBox="`0 0 ${width} ${height}`"
    overflow="visible"
  >
    <!-- Hit area -->
    <path
      :d="path"
      fill="transparent"
      stroke="transparent"
      :stroke-width="4"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick ? 'none' : isSelected ? 'none' : 'visible',
      }"
    />
    <!-- Visual -->
    <path
      v-if="!appearanceActive"
      :d="path"
      :fill="strokeColor"
      :stroke="strokeColor"
      :stroke-width="0.5"
      :opacity="opacity"
      fill-rule="evenodd"
      :style="{ pointerEvents: 'none' }"
    />
  </svg>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { Rect } from '@embedpdf/models';

const props = withDefaults(
  defineProps<{
    isSelected: boolean;
    strokeColor?: string;
    opacity?: number;
    rect: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }>(),
  {
    strokeColor: '#000000',
    opacity: 1,
    appearanceActive: false,
  },
);

const width = computed(() => props.rect.size.width);
const height = computed(() => props.rect.size.height);

const path = computed(() => {
  const w = width.value;
  const h = height.value;
  const midX = w / 2;

  return [
    `M 0 ${h}`,
    `C ${w * 0.27} ${h} ${midX} ${h - h * 0.44} ${midX} 0`,
    `C ${midX} ${h - h * 0.44} ${w - w * 0.27} ${h} ${w} ${h}`,
    'Z',
  ].join(' ');
});

const svgWidth = computed(() => width.value * props.scale);
const svgHeight = computed(() => height.value * props.scale);
</script>

// packages/plugin-annotation/src/svelte/components/annotations/Caret.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface CaretProps {
    isSelected: boolean;
    strokeColor?: string;
    opacity?: number;
    rect: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
  }

  let {
    isSelected,
    strokeColor = '#000000',
    opacity = 1,
    rect,
    scale,
    onClick,
    appearanceActive = false,
  }: CaretProps = $props();

  const { width, height, path } = $derived.by(() => {
    const w = rect.size.width;
    const h = rect.size.height;
    const midX = w / 2;

    const d = [
      `M 0 ${h}`,
      `C ${w * 0.27} ${h} ${midX} ${h - h * 0.44} ${midX} 0`,
      `C ${midX} ${h - h * 0.44} ${w - w * 0.27} ${h} ${w} ${h}`,
      'Z',
    ].join(' ');

    return { width: w, height: h, path: d };
  });

  let svgWidth = $derived(width * scale);
  let svgHeight = $derived(height * scale);
</script>

<svg
  style:position="absolute"
  style:width={`${svgWidth}px`}
  style:height={`${svgHeight}px`}
  style:pointer-events="none"
  style:z-index="2"
  width={svgWidth}
  height={svgHeight}
  viewBox={`0 0 ${width} ${height}`}
  overflow="visible"
>
  <!-- Hit area -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <path
    d={path}
    fill="transparent"
    stroke="transparent"
    stroke-width={4}
    onpointerdown={(e) => onClick?.(e)}
    style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
    pointer-events={!onClick ? 'none' : isSelected ? 'none' : 'visible'}
  />
  <!-- Visual -->
  {#if !appearanceActive}
    <path
      d={path}
      fill={strokeColor}
      stroke={strokeColor}
      stroke-width={0.5}
      {opacity}
      fill-rule="evenodd"
      style:pointer-events="none"
    />
  {/if}
</svg>
