// packages/plugin-annotation/src/vue/components/annotations/circle-preview.vue
<script setup lang="ts">
import { Rect } from '@embedpdf/models';
import { CirclePreviewData } from '@embedpdf/plugin-annotation';
import Circle from './circle.vue';

defineProps<{
  data: CirclePreviewData;
  bounds: Rect;
  scale: number;
}>();
</script>

<template>
  <Circle :isSelected="false" :scale="scale" v-bind="data" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/CirclePreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { CirclePreviewData } from '@embedpdf/plugin-annotation';
  import Circle from './Circle.svelte';

  interface CirclePreviewProps {
    data: CirclePreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, scale }: CirclePreviewProps = $props();
</script>

<Circle isSelected={false} {scale} {...data} />
