// packages/plugin-annotation/src/vue/components/annotations/line-preview.vue
<script setup lang="ts">
import { Rect } from '@embedpdf/models';
import { LinePreviewData } from '@embedpdf/plugin-annotation';
import Line from './line.vue';

defineProps<{
  data: LinePreviewData;
  bounds: Rect;
  scale: number;
}>();
</script>

<template>
  <Line :isSelected="false" :scale="scale" v-bind="data" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/LinePreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { LinePreviewData } from '@embedpdf/plugin-annotation';
  import Line from './Line.svelte';

  interface LinePreviewProps {
    data: LinePreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, scale }: LinePreviewProps = $props();
</script>

<Line isSelected={false} {scale} {...data} />
