// packages/plugin-annotation/src/vue/components/annotations/link-preview.vue
<script setup lang="ts">
import { computed } from 'vue';
import { Rect } from '@embedpdf/models';
import { LinkPreviewData } from '@embedpdf/plugin-annotation';

const props = defineProps<{
  data: LinkPreviewData;
  bounds: Rect;
  scale: number;
}>();

const style = computed(() => ({
  position: 'absolute' as const,
  left: 0,
  top: 0,
  width: `${props.bounds.size.width * props.scale}px`,
  height: `${props.bounds.size.height * props.scale}px`,
  borderBottom: `${props.data.strokeWidth * props.scale}px solid ${props.data.strokeColor}`,
  backgroundColor: 'rgba(0, 0, 255, 0.05)',
  boxSizing: 'border-box' as const,
}));
</script>

<template>
  <div :style="style" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/LinkPreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { LinkPreviewData } from '@embedpdf/plugin-annotation';

  interface LinkPreviewProps {
    data: LinkPreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, bounds, scale }: LinkPreviewProps = $props();
</script>

<div
  style:position="absolute"
  style:left="0"
  style:top="0"
  style:width="{bounds.size.width * scale}px"
  style:height="{bounds.size.height * scale}px"
  style:border-bottom="{data.strokeWidth * scale}px solid {data.strokeColor}"
  style:background-color="rgba(0, 0, 255, 0.05)"
  style:box-sizing="border-box"
></div>
