// packages/plugin-annotation/src/vue/components/annotations/polyline-preview.vue
<script setup lang="ts">
import { Rect } from '@embedpdf/models';
import { PolylinePreviewData } from '@embedpdf/plugin-annotation';
import Polyline from './polyline.vue';

defineProps<{
  data: PolylinePreviewData;
  bounds: Rect;
  scale: number;
}>();
</script>

<template>
  <Polyline :isSelected="false" :scale="scale" v-bind="data" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/PolylinePreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { PolylinePreviewData } from '@embedpdf/plugin-annotation';
  import Polyline from './Polyline.svelte';

  interface PolylinePreviewProps {
    data: PolylinePreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, scale }: PolylinePreviewProps = $props();
</script>

<Polyline isSelected={false} {scale} {...data} />
