// packages/plugin-annotation/src/vue/components/annotations/polygon-preview.vue
<script setup lang="ts">
import { Rect } from '@embedpdf/models';
import { PolygonPreviewData } from '@embedpdf/plugin-annotation';
import Polygon from './polygon.vue';

defineProps<{
  data: PolygonPreviewData;
  bounds: Rect;
  scale: number;
}>();
</script>

<template>
  <Polygon :isSelected="false" :scale="scale" v-bind="data" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/PolygonPreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { PolygonPreviewData } from '@embedpdf/plugin-annotation';
  import Polygon from './Polygon.svelte';

  interface PolygonPreviewProps {
    data: PolygonPreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, scale }: PolygonPreviewProps = $props();
</script>

<Polygon isSelected={false} {scale} {...data} />
