// packages/plugin-annotation/src/vue/components/annotations/square.vue
<template>
  <svg
    :style="{
      position: 'absolute',
      width: svgWidth,
      height: svgHeight,
      pointerEvents: 'none',
      zIndex: 2,
    }"
    :width="svgWidth"
    :height="svgHeight"
    :viewBox="`0 0 ${rect.size.width} ${rect.size.height}`"
    overflow="visible"
  >
    <!-- Hit area -- always rendered, transparent, wider stroke for mobile -->
    <path
      v-if="isCloudy && cloudyPath"
      :d="cloudyPath.path"
      fill="transparent"
      stroke="transparent"
      :stroke-width="hitStrokeWidth"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick
          ? 'none'
          : isSelected
            ? 'none'
            : color === 'transparent'
              ? 'visibleStroke'
              : 'visible',
      }"
    />
    <rect
      v-else
      :x="geometry.x"
      :y="geometry.y"
      :width="geometry.width"
      :height="geometry.height"
      fill="transparent"
      stroke="transparent"
      :stroke-width="hitStrokeWidth"
      @pointerdown="onClick"
      :style="{
        cursor: isSelected ? 'move' : onClick ? 'pointer' : 'default',
        pointerEvents: !onClick
          ? 'none'
          : isSelected
            ? 'none'
            : color === 'transparent'
              ? 'visibleStroke'
              : 'visible',
      }"
    />
    <!-- Visual -- hidden when AP active, never interactive -->
    <template v-if="!appearanceActive">
      <path
        v-if="isCloudy && cloudyPath"
        :d="cloudyPath.path"
        :fill="color"
        :opacity="opacity"
        :style="{
          pointerEvents: 'none',
          stroke: strokeColor ?? color,
          strokeWidth: strokeWidth,
          strokeLinejoin: 'round',
        }"
      />
      <rect
        v-else
        :x="geometry.x"
        :y="geometry.y"
        :width="geometry.width"
        :height="geometry.height"
        :fill="color"
        :opacity="opacity"
        :style="{
          pointerEvents: 'none',
          stroke: strokeColor ?? color,
          strokeWidth: strokeWidth,
          ...(strokeStyle === PdfAnnotationBorderStyle.DASHED && {
            strokeDasharray: strokeDashArray?.join(','),
          }),
        }"
      />
    </template>
  </svg>
</template>

<script lang="ts">
export default { inheritAttrs: false };
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { PdfAnnotationBorderStyle, PdfRectDifferences, Rect } from '@embedpdf/models';
import { generateCloudyRectanglePath } from '@embedpdf/plugin-annotation';

const MIN_HIT_AREA_SCREEN_PX = 20;

const props = withDefaults(
  defineProps<{
    isSelected: boolean;
    color?: string;
    strokeColor?: string;
    opacity?: number;
    strokeWidth: number;
    strokeStyle?: PdfAnnotationBorderStyle;
    strokeDashArray?: number[];
    rect: Rect;
    scale: number;
    onClick?: (e: PointerEvent) => void;
    appearanceActive?: boolean;
    cloudyBorderIntensity?: number;
    rectangleDifferences?: PdfRectDifferences;
  }>(),
  {
    color: '#000000',
    opacity: 1,
    strokeStyle: PdfAnnotationBorderStyle.SOLID,
    appearanceActive: false,
  },
);

const isCloudy = computed(() => (props.cloudyBorderIntensity ?? 0) > 0);

const geometry = computed(() => {
  const outerW = props.rect.size.width;
  const outerH = props.rect.size.height;
  const innerW = Math.max(outerW - props.strokeWidth, 0);
  const innerH = Math.max(outerH - props.strokeWidth, 0);

  return {
    width: innerW,
    height: innerH,
    x: props.strokeWidth / 2,
    y: props.strokeWidth / 2,
  };
});

const cloudyPath = computed(() => {
  if (!isCloudy.value) return null;
  return generateCloudyRectanglePath(
    { x: 0, y: 0, width: props.rect.size.width, height: props.rect.size.height },
    props.rectangleDifferences,
    props.cloudyBorderIntensity!,
    props.strokeWidth,
  );
});

const svgWidth = computed(() => props.rect.size.width * props.scale);
const svgHeight = computed(() => props.rect.size.height * props.scale);
const hitStrokeWidth = computed(() =>
  Math.max(props.strokeWidth, MIN_HIT_AREA_SCREEN_PX / props.scale),
);
</script>

// packages/plugin-annotation/src/svelte/components/annotations/Square.svelte
<script lang="ts">
  import type { Rect, PdfRectDifferences } from '@embedpdf/models';
  import { PdfAnnotationBorderStyle } from '@embedpdf/models';
  import { generateCloudyRectanglePath } from '@embedpdf/plugin-annotation';

  const MIN_HIT_AREA_SCREEN_PX = 20;

  interface SquareProps {
    isSelected: boolean;
    color?: string;
    strokeColor?: string;
    opacity?: number;
    strokeWidth: number;
    strokeStyle?: PdfAnnotationBorderStyle;
    strokeDashArray?: number[];
    rect: Rect;
    scale: number;
    onClick?: (e: MouseEvent) => void;
    appearanceActive?: boolean;
    cloudyBorderIntensity?: number;
    rectangleDifferences?: PdfRectDifferences;
  }

  let {
    isSelected,
    color = '#000000',
    strokeColor,
    opacity = 1,
    strokeWidth,
    strokeStyle = PdfAnnotationBorderStyle.SOLID,
    strokeDashArray,
    rect,
    scale,
    onClick,
    appearanceActive = false,
    cloudyBorderIntensity,
    rectangleDifferences,
  }: SquareProps = $props();

  const isCloudy = $derived((cloudyBorderIntensity ?? 0) > 0);

  const { width, height, x, y } = $derived.by(() => {
    const outerW = rect.size.width;
    const outerH = rect.size.height;
    const innerW = Math.max(outerW - strokeWidth, 0);
    const innerH = Math.max(outerH - strokeWidth, 0);
    return {
      width: innerW,
      height: innerH,
      x: strokeWidth / 2,
      y: strokeWidth / 2,
    };
  });

  const cloudyPath = $derived.by(() => {
    if (!isCloudy) return null;
    return generateCloudyRectanglePath(
      { x: 0, y: 0, width: rect.size.width, height: rect.size.height },
      rectangleDifferences,
      cloudyBorderIntensity!,
      strokeWidth,
    );
  });

  const svgWidth = $derived((width + strokeWidth) * scale);
  const svgHeight = $derived((height + strokeWidth) * scale);
  const hitStrokeWidth = $derived(Math.max(strokeWidth, MIN_HIT_AREA_SCREEN_PX / scale));

  const dash = $derived(
    strokeStyle === PdfAnnotationBorderStyle.DASHED ? strokeDashArray?.join(',') : undefined,
  );
</script>

<svg
  style="position: absolute; pointer-events: none; z-index: 2;"
  style:width={`${svgWidth}px`}
  style:height={`${svgHeight}px`}
  width={svgWidth}
  height={svgHeight}
  viewBox={`0 0 ${width + strokeWidth} ${height + strokeWidth}`}
  overflow="visible"
>
  <!-- Hit area -- always rendered, transparent, wider stroke for mobile -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  {#if isCloudy && cloudyPath}
    <path
      d={cloudyPath.path}
      fill="transparent"
      stroke="transparent"
      stroke-width={hitStrokeWidth}
      onpointerdown={onClick}
      style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
      style:pointer-events={!onClick
        ? 'none'
        : isSelected
          ? 'none'
          : color === 'transparent'
            ? 'visibleStroke'
            : 'visible'}
    />
  {:else}
    <rect
      {x}
      {y}
      {width}
      {height}
      fill="transparent"
      stroke="transparent"
      stroke-width={hitStrokeWidth}
      onpointerdown={onClick}
      style:cursor={isSelected ? 'move' : onClick ? 'pointer' : 'default'}
      style:pointer-events={!onClick
        ? 'none'
        : isSelected
          ? 'none'
          : color === 'transparent'
            ? 'visibleStroke'
            : 'visible'}
    />
  {/if}
  <!-- Visual -- hidden when AP active, never interactive -->
  {#if !appearanceActive}
    {#if isCloudy && cloudyPath}
      <path
        d={cloudyPath.path}
        fill={color}
        {opacity}
        style:pointer-events="none"
        style:stroke={strokeColor ?? color}
        style:stroke-width={strokeWidth}
        stroke-linejoin="round"
      />
    {:else}
      <rect
        {x}
        {y}
        {width}
        {height}
        fill={color}
        {opacity}
        style:pointer-events="none"
        style:stroke={strokeColor ?? color}
        style:stroke-width={strokeWidth}
        style:stroke-dasharray={dash}
      />
    {/if}
  {/if}
</svg>
