// packages/plugin-annotation/src/vue/components/annotations/square-preview.vue
<script setup lang="ts">
import { Rect } from '@embedpdf/models';
import { SquarePreviewData } from '@embedpdf/plugin-annotation';
import Square from './square.vue';

defineProps<{
  data: SquarePreviewData;
  bounds: Rect;
  scale: number;
}>();
</script>

<template>
  <Square :isSelected="false" :scale="scale" v-bind="data" />
</template>

// packages/plugin-annotation/src/svelte/components/annotations/SquarePreview.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';
  import type { SquarePreviewData } from '@embedpdf/plugin-annotation';
  import Square from './Square.svelte';

  interface SquarePreviewProps {
    data: SquarePreviewData;
    bounds: Rect;
    scale: number;
  }

  let { data, scale }: SquarePreviewProps = $props();
</script>

<Square isSelected={false} {scale} {...data} />
