// packages/plugin-annotation/src/shared/components/counter-rotate-container.tsx
import { Rect, Rotation, Size } from '@embedpdf/models';
import { ReactNode, CSSProperties, PointerEvent, Fragment, TouchEvent } from '@framework';

interface CounterRotateProps {
  rect: Rect;
  rotation: Rotation;
}

interface CounterTransformResult {
  matrix: string; // CSS matrix(a,b,c,d,e,f)
  width: number; // new width
  height: number; // new height
}

/**
 * Given an already-placed rect (left/top/width/height in px) and the page rotation,
 * return the counter-rotation matrix + adjusted width/height.
 *
 * transform-origin is expected to be "0 0".
 * left/top DO NOT change, apply them as-is.
 */
export function getCounterRotation(rect: Rect, rotation: Rotation): CounterTransformResult {
  const { width: w, height: h } = rect.size;

  switch (rotation % 4) {
    case 1: // 90° cw → need matrix(0,-1,1,0,0,h) and swap w/h
      return {
        matrix: `matrix(0, -1, 1, 0, 0, ${h})`,
        width: h,
        height: w,
      };

    case 2: // 180° → matrix(-1,0,0,-1,w,h), width/height unchanged
      return {
        matrix: `matrix(-1, 0, 0, -1, ${w}, ${h})`,
        width: w,
        height: h,
      };

    case 3: // 270° cw → matrix(0,1,-1,0,w,0), swap w/h
      return {
        matrix: `matrix(0, 1, -1, 0, ${w}, 0)`,
        width: h,
        height: w,
      };

    default:
      return {
        matrix: `matrix(1, 0, 0, 1, 0, 0)`,
        width: w,
        height: h,
      };
  }
}

export interface MenuWrapperProps {
  style: CSSProperties;
  onPointerDown: (e: PointerEvent<HTMLDivElement>) => void;
  onTouchStart: (e: TouchEvent<HTMLDivElement>) => void;
}

interface CounterRotateComponentProps extends CounterRotateProps {
  children: (props: {
    matrix: string;
    rect: Rect;
    menuWrapperProps: MenuWrapperProps;
  }) => ReactNode;
}

export function CounterRotate({ children, ...props }: CounterRotateComponentProps) {
  const { rect, rotation } = props;
  const { matrix, width, height } = getCounterRotation(rect, rotation);

  const menuWrapperStyle: CSSProperties = {
    position: 'absolute',
    left: rect.origin.x,
    top: rect.origin.y,
    transform: matrix,
    transformOrigin: '0 0',
    width: width,
    height: height,
    pointerEvents: 'none',
    zIndex: 3,
  };

  const menuWrapperProps = {
    style: menuWrapperStyle,
    onPointerDown: (e: PointerEvent<HTMLDivElement>) => e.stopPropagation(),
    onTouchStart: (e: TouchEvent<HTMLDivElement>) => e.stopPropagation(),
  };

  return (
    <Fragment>
      {children({
        menuWrapperProps,
        matrix,
        rect: {
          origin: { x: rect.origin.x, y: rect.origin.y },
          size: { width: width, height: height },
        },
      })}
    </Fragment>
  );
}

// packages/utils/src/vue/components/counter-rotate-container.vue
<template>
  <slot :menu-wrapper-props="menuWrapperProps" :matrix="matrix" :rect="adjustedRect" />
</template>

<script setup lang="ts">
import { computed, type CSSProperties } from 'vue';
import type { Rect, Rotation } from '@embedpdf/models';
import { getCounterRotation } from '@embedpdf/utils';

interface CounterRotateProps {
  rect: Rect;
  rotation: Rotation;
}

const props = defineProps<CounterRotateProps>();

const { matrix, width, height } = getCounterRotation(props.rect, props.rotation);

const menuWrapperProps = computed(() => ({
  style: {
    position: 'absolute',
    left: `${props.rect.origin.x}px`,
    top: `${props.rect.origin.y}px`,
    transform: matrix,
    transformOrigin: '0 0',
    width: `${width}px`,
    height: `${height}px`,
    pointerEvents: 'none',
    zIndex: 3,
  } as CSSProperties,
  onPointerDown: (e: PointerEvent) => e.stopPropagation(),
  onTouchStart: (e: TouchEvent) => e.stopPropagation(),
}));

const adjustedRect = computed(() => ({
  origin: { x: props.rect.origin.x, y: props.rect.origin.y },
  size: { width, height },
}));
</script>
