// packages/plugin-annotation/src/svelte/components/text-markup/Squiggly.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface SquigglyProps {
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent | TouchEvent) => void;
    style?: Record<string, string | number | undefined>;
    /** When true, AP image provides the visual; only render hit area */
    appearanceActive?: boolean;
  }

  let {
    strokeColor,
    opacity = 0.5,
    segmentRects,
    rect,
    scale,
    onClick,
    style,
    appearanceActive = false,
  }: SquigglyProps = $props();

  const resolvedColor = $derived(strokeColor ?? '#FFFF00');
  const amplitude = $derived(2 * scale); // wave height
  const period = $derived(6 * scale); // wave length

  const svg =
    $derived(`<svg xmlns="http://www.w3.org/2000/svg" width="${period}" height="${amplitude * 2}" viewBox="0 0 ${period} ${amplitude * 2}">
      <path d="M0 ${amplitude} Q ${period / 4} 0 ${period / 2} ${amplitude} T ${period} ${amplitude}"
            fill="none" stroke="${resolvedColor}" stroke-width="${amplitude}" stroke-linecap="round"/>
    </svg>`);

  // Completely escape the SVG markup
  const svgDataUri = $derived(`url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`);
</script>

{#each segmentRects as r, i (i)}
  <div
    role="button"
    tabindex={onClick ? 0 : -1}
    onpointerdown={onClick}
    ontouchstart={onClick}
    style:position="absolute"
    style:left="{(rect ? r.origin.x - rect.origin.x : r.origin.x) * scale}px"
    style:top="{(rect ? r.origin.y - rect.origin.y : r.origin.y) * scale}px"
    style:width="{r.size.width * scale}px"
    style:height="{r.size.height * scale}px"
    style:background="transparent"
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? 1 : 0}
    {...style ? Object.fromEntries(Object.entries(style).map(([k, v]) => [`style:${k}`, v])) : {}}
  >
    <!-- Visual -- hidden when AP active, never interactive -->
    {#if !appearanceActive}
      <div
        style:position="absolute"
        style:left="0"
        style:bottom="0"
        style:width="100%"
        style:height="{amplitude * 2}px"
        style:background-image={svgDataUri}
        style:background-repeat="repeat-x"
        style:background-size="{period}px {amplitude * 2}px"
        style:opacity
        style:pointer-events="none"
      ></div>
    {/if}
  </div>
{/each}

// packages/plugin-annotation/src/shared/components/text-markup/squiggly.tsx
import { CSSProperties, MouseEvent, TouchEvent } from '@framework';
import { Rect } from '@embedpdf/models';

type SquigglyProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement> | TouchEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Squiggly({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: SquigglyProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';
  const amplitude = 2 * scale; // wave height
  const period = 6 * scale; // wave length

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${period}" height="${amplitude * 2}" viewBox="0 0 ${period} ${amplitude * 2}">
      <path d="M0 ${amplitude} Q ${period / 4} 0 ${period / 2} ${amplitude} T ${period} ${amplitude}"
            fill="none" stroke="${resolvedColor}" stroke-width="${amplitude}" stroke-linecap="round"/>
    </svg>`;

  // Completely escape the SVG markup
  const svgDataUri = `url("data:image/svg+xml;utf8,${encodeURIComponent(svg)}")`;

  return (
    <>
      {segmentRects.map((r, i) => (
        <div
          key={i}
          onPointerDown={onClick}
          onTouchStart={onClick}
          style={{
            position: 'absolute',
            left: (rect ? r.origin.x - rect.origin.x : r.origin.x) * scale,
            top: (rect ? r.origin.y - rect.origin.y : r.origin.y) * scale,
            width: r.size.width * scale,
            height: r.size.height * scale,
            background: 'transparent',
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : 0,
            ...style,
          }}
        >
          {/* Visual -- hidden when AP active, never interactive */}
          {!appearanceActive && (
            <div
              style={{
                position: 'absolute',
                left: 0,
                bottom: 0,
                width: '100%',
                height: amplitude * 2,
                backgroundImage: svgDataUri,
                backgroundRepeat: 'repeat-x',
                backgroundSize: `${period}px ${amplitude * 2}px`,
                opacity: opacity,
                pointerEvents: 'none',
              }}
            />
          )}
        </div>
      ))}
    </>
  );
}
