// packages/plugin-annotation/src/svelte/components/RenderAnnotation.svelte
<script lang="ts">
  import { ignore, type PdfAnnotationObject, PdfErrorCode } from '@embedpdf/models';
  import type { HTMLImgAttributes } from 'svelte/elements';
  import { useAnnotationCapability } from '../hooks';
  import { deepToRaw } from '@embedpdf/utils/svelte';

  interface RenderAnnotationProps extends Omit<HTMLImgAttributes, 'style'> {
    documentId: string;
    pageIndex: number;
    annotation: PdfAnnotationObject;
    scaleFactor?: number;
    dpr?: number;
    unrotated?: boolean;
    style?: Record<string, string | number | undefined>;
  }

  let {
    documentId,
    pageIndex,
    annotation,
    scaleFactor = 1,
    unrotated = false,
    style,
    ...restProps
  }: RenderAnnotationProps = $props();

  const annotationCapability = useAnnotationCapability();

  let imageUrl = $state<string | null>(null);
  let urlRef: string | null = null;

  const { width, height } = $derived(annotation.rect.size);

  // Get scoped API for this document
  const annotationProvides = $derived(
    annotationCapability.provides ? annotationCapability.provides.forDocument(documentId) : null,
  );

  // Effect to render annotation
  $effect(() => {
    if (annotationProvides) {
      const task = annotationProvides.renderAnnotation({
        pageIndex,
        annotation: deepToRaw(annotation),
        options: {
          scaleFactor,
          dpr: window.devicePixelRatio,
          unrotated,
        },
      });

      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        imageUrl = url;
        urlRef = url;
      }, ignore);

      return () => {
        if (urlRef) {
          URL.revokeObjectURL(urlRef);
          urlRef = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      };
    }
  });

  function handleImageLoad() {
    if (urlRef) {
      URL.revokeObjectURL(urlRef);
      urlRef = null;
    }
  }
</script>

{#if imageUrl}
  <img
    alt=""
    src={imageUrl}
    onload={handleImageLoad}
    {...restProps}
    style:width="100%"
    style:height="100%"
    style:display="block"
    {style}
  />
{/if}

// packages/plugin-annotation/src/shared/components/render-annotation.tsx
import { Fragment, HTMLAttributes, CSSProperties, useEffect, useRef, useState } from '@framework';
import { AppearanceMode, ignore, PdfAnnotationObject, PdfErrorCode } from '@embedpdf/models';

import { useAnnotationCapability } from '../hooks/use-annotation';

type RenderAnnotationProps = Omit<HTMLAttributes<HTMLImageElement>, 'style'> & {
  documentId: string;
  pageIndex: number;
  annotation: PdfAnnotationObject;
  scaleFactor?: number;
  dpr?: number;
  style?: CSSProperties;
  unrotated?: boolean;
};

export function RenderAnnotation({
  documentId,
  pageIndex,
  annotation,
  scaleFactor = 1,
  unrotated,
  style,
  ...props
}: RenderAnnotationProps) {
  const { provides: annotationProvides } = useAnnotationCapability();
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const urlRef = useRef<string | null>(null);

  const { width, height } = annotation.rect.size;

  useEffect(() => {
    if (annotationProvides) {
      const task = annotationProvides.forDocument(documentId).renderAnnotation({
        pageIndex,
        annotation,
        options: {
          scaleFactor,
          dpr: window.devicePixelRatio,
          unrotated,
        },
      });
      task.wait((blob) => {
        const url = URL.createObjectURL(blob);
        setImageUrl(url);
        urlRef.current = url;
      }, ignore);

      return () => {
        if (urlRef.current) {
          URL.revokeObjectURL(urlRef.current);
          urlRef.current = null;
        } else {
          task.abort({
            code: PdfErrorCode.Cancelled,
            message: 'canceled render task',
          });
        }
      };
    }
  }, [
    pageIndex,
    scaleFactor,
    unrotated,
    annotationProvides,
    documentId,
    annotation.id,
    width,
    height,
  ]);

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  return (
    <Fragment>
      {imageUrl && (
        <img
          src={imageUrl}
          onLoad={handleImageLoad}
          {...props}
          style={{
            width: '100%',
            height: '100%',
            display: 'block',
            ...(style || {}),
          }}
        />
      )}
    </Fragment>
  );
}
