// packages/plugin-annotation/src/svelte/components/TextMarkup.svelte
<script lang="ts">
  import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode, type Rect } from '@embedpdf/models';
  import type { AnnotationTool } from '@embedpdf/plugin-annotation';
  import { useSelectionCapability } from '@embedpdf/plugin-selection/svelte';

  import { useAnnotationCapability } from '../hooks';
  import Highlight from './text-markup/Highlight.svelte';
  import Squiggly from './text-markup/Squiggly.svelte';
  import Underline from './text-markup/Underline.svelte';
  import Strikeout from './text-markup/Strikeout.svelte';

  interface TextMarkupProps {
    documentId: string;
    pageIndex: number;
    scale: number;
  }

  let { documentId, pageIndex, scale }: TextMarkupProps = $props();

  const selectionCapability = useSelectionCapability();
  const annotationCapability = useAnnotationCapability();

  let rects = $state<Rect[]>([]);
  let boundingRect = $state<Rect | null>(null);
  let activeTool = $state<AnnotationTool | null>(null);

  // Get scoped APIs for this document
  const selectionProvides = $derived(
    selectionCapability.provides ? selectionCapability.provides.forDocument(documentId) : null,
  );
  const annotationProvides = $derived(
    annotationCapability.provides ? annotationCapability.provides.forDocument(documentId) : null,
  );

  // Subscribe to selection changes
  $effect(() => {
    if (!selectionProvides) return;

    const off = selectionProvides.onSelectionChange(() => {
      rects = selectionProvides.getHighlightRectsForPage(pageIndex);
      boundingRect = selectionProvides.getBoundingRectForPage(pageIndex);
    });
    return off;
  });

  // Subscribe to active tool changes
  $effect(() => {
    if (!annotationProvides) return;

    // Initialize with current active tool
    activeTool = annotationProvides.getActiveTool();

    const off = annotationProvides.onActiveToolChange((tool) => {
      activeTool = tool;
    });
    return off;
  });

  const mixBlendMode = $derived(
    activeTool?.defaults?.blendMode
      ? blendModeToCss(activeTool.defaults.blendMode)
      : activeTool?.defaults?.type === PdfAnnotationSubtype.HIGHLIGHT
        ? blendModeToCss(PdfBlendMode.Multiply)
        : blendModeToCss(PdfBlendMode.Normal),
  );
</script>

{#if boundingRect && activeTool && activeTool.defaults}
  {#if activeTool.defaults.type === PdfAnnotationSubtype.UNDERLINE}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Underline
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.HIGHLIGHT}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Highlight
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.STRIKEOUT}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Strikeout
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        {scale}
      />
    </div>
  {:else if activeTool.defaults.type === PdfAnnotationSubtype.SQUIGGLY}
    <div
      style:mix-blend-mode={mixBlendMode}
      style:pointer-events="none"
      style:position="absolute"
      style:inset="0"
    >
      <Squiggly
        strokeColor={activeTool.defaults?.strokeColor}
        opacity={activeTool.defaults?.opacity}
        segmentRects={rects}
        {scale}
      />
    </div>
  {/if}
{/if}

// packages/plugin-annotation/src/shared/components/text-markup.tsx
import { blendModeToCss, PdfAnnotationSubtype, PdfBlendMode, Rect } from '@embedpdf/models';
import { AnnotationTool } from '@embedpdf/plugin-annotation';
import { useSelectionCapability } from '@embedpdf/plugin-selection/@framework';

import { useEffect, useState } from '@framework';
import { useAnnotationCapability } from '../hooks';
import { Highlight } from './text-markup/highlight';
import { Squiggly } from './text-markup/squiggly';
import { Underline } from './text-markup/underline';
import { Strikeout } from './text-markup/strikeout';

interface TextMarkupProps {
  documentId: string;
  pageIndex: number;
  scale: number;
}

export function TextMarkup({ documentId, pageIndex, scale }: TextMarkupProps) {
  const { provides: selectionProvides } = useSelectionCapability();
  const { provides: annotationProvides } = useAnnotationCapability();
  const [rects, setRects] = useState<Array<Rect>>([]);
  const [boundingRect, setBoundingRect] = useState<Rect | null>(null);
  const [activeTool, setActiveTool] = useState<AnnotationTool | null>(null);

  useEffect(() => {
    if (!selectionProvides) return;

    return selectionProvides.forDocument(documentId).onSelectionChange(() => {
      setRects(selectionProvides.forDocument(documentId).getHighlightRectsForPage(pageIndex));
      setBoundingRect(selectionProvides.forDocument(documentId).getBoundingRectForPage(pageIndex));
    });
  }, [selectionProvides, documentId, pageIndex]);

  useEffect(() => {
    if (!annotationProvides) return;

    // Initialize with current active tool
    setActiveTool(annotationProvides.forDocument(documentId).getActiveTool());

    return annotationProvides
      .forDocument(documentId)
      .onActiveToolChange((event) => setActiveTool(event));
  }, [annotationProvides, documentId]);

  if (!boundingRect) return null;
  if (!activeTool || !activeTool.defaults) return null;

  switch (activeTool.defaults.type) {
    case PdfAnnotationSubtype.UNDERLINE:
      return (
        <div
          style={{
            mixBlendMode: blendModeToCss(activeTool.defaults?.blendMode ?? PdfBlendMode.Normal),
            pointerEvents: 'none',
            position: 'absolute',
            inset: 0,
          }}
        >
          <Underline
            strokeColor={activeTool.defaults?.strokeColor}
            opacity={activeTool.defaults?.opacity}
            segmentRects={rects}
            scale={scale}
          />
        </div>
      );
    case PdfAnnotationSubtype.HIGHLIGHT:
      return (
        <div
          style={{
            mixBlendMode: blendModeToCss(activeTool.defaults?.blendMode ?? PdfBlendMode.Multiply),
            pointerEvents: 'none',
            position: 'absolute',
            inset: 0,
          }}
        >
          <Highlight
            strokeColor={activeTool.defaults?.strokeColor}
            opacity={activeTool.defaults?.opacity}
            segmentRects={rects}
            scale={scale}
          />
        </div>
      );
    case PdfAnnotationSubtype.STRIKEOUT:
      return (
        <div
          style={{
            mixBlendMode: blendModeToCss(activeTool.defaults?.blendMode ?? PdfBlendMode.Normal),
            pointerEvents: 'none',
            position: 'absolute',
            inset: 0,
          }}
        >
          <Strikeout
            strokeColor={activeTool.defaults?.strokeColor}
            opacity={activeTool.defaults?.opacity}
            segmentRects={rects}
            scale={scale}
          />
        </div>
      );
    case PdfAnnotationSubtype.SQUIGGLY:
      return (
        <div
          style={{
            mixBlendMode: blendModeToCss(activeTool.defaults?.blendMode ?? PdfBlendMode.Normal),
            pointerEvents: 'none',
            position: 'absolute',
            inset: 0,
          }}
        >
          <Squiggly
            strokeColor={activeTool.defaults?.strokeColor}
            opacity={activeTool.defaults?.opacity}
            segmentRects={rects}
            scale={scale}
          />
        </div>
      );
    default:
      return null;
  }
}
