// packages/core/src/shared/components/auto-mount.tsx
import { Fragment, useMemo, ComponentType, ReactNode } from '@framework';
import { hasAutoMountElements } from '@embedpdf/core';
import type { PluginBatchRegistration, IPlugin } from '@embedpdf/core';

interface AutoMountProps {
  plugins: PluginBatchRegistration<IPlugin<any>, any>[];
  children: ReactNode;
}

export function AutoMount({ plugins, children }: AutoMountProps) {
  const { utilities, wrappers } = useMemo(() => {
    // React-specific types for internal use
    const utilities: ComponentType[] = [];
    const wrappers: ComponentType<{ children: ReactNode }>[] = [];

    for (const reg of plugins) {
      const pkg = reg.package;
      if (hasAutoMountElements(pkg)) {
        const elements = pkg.autoMountElements() || [];

        for (const element of elements) {
          if (element.type === 'utility') {
            utilities.push(element.component);
          } else if (element.type === 'wrapper') {
            // In React context, we know wrappers need children
            wrappers.push(element.component);
          }
        }
      }
    }
    return { utilities, wrappers };
  }, [plugins]);

  // Combine children and utilities as siblings inside the wrapper chain
  const contentWithUtilities = (
    <Fragment>
      {children}
      {utilities.map((Utility, i) => (
        <Utility key={`utility-${i}`} />
      ))}
    </Fragment>
  );

  // Wrap everything together - utilities now inside wrapper context
  const wrappedContent = wrappers.reduce(
    (content, Wrapper) => <Wrapper>{content}</Wrapper>,
    contentWithUtilities,
  );

  return <Fragment>{wrappedContent}</Fragment>;
}

// packages/core/src/vue/components/auto-mount.vue
<script setup lang="ts">
import { computed } from 'vue';
import { hasAutoMountElements, type PluginBatchRegistration, type IPlugin } from '@embedpdf/core';
import NestedWrapper from './nested-wrapper.vue';

const props = defineProps<{
  plugins: PluginBatchRegistration<IPlugin<any>, any>[];
}>();

const elements = computed(() => {
  const utilities: any[] = [];
  const wrappers: any[] = [];

  for (const reg of props.plugins) {
    const pkg = reg.package;
    if (hasAutoMountElements(pkg)) {
      const elements = pkg.autoMountElements() || [];

      for (const element of elements) {
        if (element.type === 'utility') {
          utilities.push(element.component);
        } else if (element.type === 'wrapper') {
          wrappers.push(element.component);
        }
      }
    }
  }

  return { utilities, wrappers };
});
</script>

<template>
  <NestedWrapper
    v-if="elements.wrappers.length > 0"
    :wrappers="elements.wrappers"
    :utilities="elements.utilities"
  >
    <slot />
  </NestedWrapper>
  <template v-else>
    <!-- No wrappers - render children and utilities directly -->
    <slot />
    <component
      v-for="(utility, index) in elements.utilities"
      :key="`utility-${index}`"
      :is="utility"
    />
  </template>
</template>
