// packages/plugin-annotation/src/shared/components/text-markup/highlight.tsx
import { CSSProperties, MouseEvent, TouchEvent } from '@framework';
import { Rect } from '@embedpdf/models';

type HighlightProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement> | TouchEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Highlight({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: HighlightProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';

  return (
    <>
      {segmentRects.map((b, i) => (
        <div
          key={i}
          onPointerDown={onClick}
          onTouchStart={onClick}
          style={{
            position: 'absolute',
            left: (rect ? b.origin.x - rect.origin.x : b.origin.x) * scale,
            top: (rect ? b.origin.y - rect.origin.y : b.origin.y) * scale,
            width: b.size.width * scale,
            height: b.size.height * scale,
            background: appearanceActive ? 'transparent' : resolvedColor,
            opacity: appearanceActive ? undefined : opacity,
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : undefined,
            ...style,
          }}
        />
      ))}
    </>
  );
}

// packages/plugin-annotation/src/svelte/components/text-markup/Highlight.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface HighlightProps {
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent | TouchEvent) => void;
    style?: Record<string, string | number | undefined>;
    /** When true, AP image provides the visual; only render hit area */
    appearanceActive?: boolean;
  }

  let {
    strokeColor,
    opacity = 0.5,
    segmentRects,
    rect,
    scale,
    onClick,
    style,
    appearanceActive = false,
  }: HighlightProps = $props();

  const resolvedColor = $derived(strokeColor ?? '#FFFF00');
</script>

{#each segmentRects as b, i (i)}
  <div
    role="button"
    tabindex={onClick ? 0 : -1}
    onpointerdown={onClick}
    ontouchstart={onClick}
    style:position="absolute"
    style:left="{(rect ? b.origin.x - rect.origin.x : b.origin.x) * scale}px"
    style:top="{(rect ? b.origin.y - rect.origin.y : b.origin.y) * scale}px"
    style:width="{b.size.width * scale}px"
    style:height="{b.size.height * scale}px"
    style:background={appearanceActive ? 'transparent' : resolvedColor}
    style:opacity={appearanceActive ? undefined : opacity}
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? 1 : undefined}
    {...style ? Object.fromEntries(Object.entries(style).map(([k, v]) => [`style:${k}`, v])) : {}}
  ></div>
{/each}
