// packages/plugin-annotation/src/shared/components/text-markup/underline.tsx
import { CSSProperties, MouseEvent, TouchEvent } from '@framework';
import { Rect } from '@embedpdf/models';

type UnderlineProps = {
  /** Stroke/markup color */
  strokeColor?: string;
  opacity?: number;
  segmentRects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent<HTMLDivElement> | TouchEvent<HTMLDivElement>) => void;
  style?: CSSProperties;
  /** When true, AP image provides the visual; only render hit area */
  appearanceActive?: boolean;
};

export function Underline({
  strokeColor,
  opacity = 0.5,
  segmentRects,
  rect,
  scale,
  onClick,
  style,
  appearanceActive = false,
}: UnderlineProps) {
  const resolvedColor = strokeColor ?? '#FFFF00';
  const thickness = 2 * scale; // 2 CSS px at 100 % zoom

  return (
    <>
      {segmentRects.map((r, i) => (
        <div
          key={i}
          onPointerDown={onClick}
          onTouchStart={onClick}
          style={{
            position: 'absolute',
            left: (rect ? r.origin.x - rect.origin.x : r.origin.x) * scale,
            top: (rect ? r.origin.y - rect.origin.y : r.origin.y) * scale,
            width: r.size.width * scale,
            height: r.size.height * scale,
            background: 'transparent',
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : 0,
            ...style,
          }}
        >
          {/* Visual -- hidden when AP active, never interactive */}
          {!appearanceActive && (
            <div
              style={{
                position: 'absolute',
                left: 0,
                bottom: 0,
                width: '100%',
                height: thickness,
                background: resolvedColor,
                opacity: opacity,
                pointerEvents: 'none',
              }}
            />
          )}
        </div>
      ))}
    </>
  );
}

// packages/plugin-annotation/src/svelte/components/text-markup/Underline.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface UnderlineProps {
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent | TouchEvent) => void;
    style?: Record<string, string | number | undefined>;
    /** When true, AP image provides the visual; only render hit area */
    appearanceActive?: boolean;
  }

  let {
    strokeColor,
    opacity = 0.5,
    segmentRects,
    rect,
    scale,
    onClick,
    style,
    appearanceActive = false,
  }: UnderlineProps = $props();

  const resolvedColor = $derived(strokeColor ?? '#FFFF00');
  const thickness = $derived(2 * scale); // 2 CSS px at 100% zoom
</script>

{#each segmentRects as r, i (i)}
  <div
    role="button"
    tabindex={onClick ? 0 : -1}
    onpointerdown={onClick}
    ontouchstart={onClick}
    style:position="absolute"
    style:left="{(rect ? r.origin.x - rect.origin.x : r.origin.x) * scale}px"
    style:top="{(rect ? r.origin.y - rect.origin.y : r.origin.y) * scale}px"
    style:width="{r.size.width * scale}px"
    style:height="{r.size.height * scale}px"
    style:background="transparent"
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? 1 : 0}
    {...style ? Object.fromEntries(Object.entries(style).map(([k, v]) => [`style:${k}`, v])) : {}}
  >
    <!-- Visual -- hidden when AP active, never interactive -->
    {#if !appearanceActive}
      <div
        style:position="absolute"
        style:left="0"
        style:bottom="0"
        style:width="100%"
        style:height="{thickness}px"
        style:background={resolvedColor}
        style:opacity
        style:pointer-events="none"
      ></div>
    {/if}
  </div>
{/each}
