// packages/plugin-redaction/src/svelte/components/annotations/RedactHighlight.svelte
<script lang="ts">
  import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/svelte';
  import type { PdfRedactAnnoObject } from '@embedpdf/models';
  import {
    PdfStandardFont,
    PdfTextAlignment,
    standardFontCss,
    textAlignmentToCss,
  } from '@embedpdf/models';

  let { annotation, isSelected, scale, onClick }: AnnotationRendererProps<PdfRedactAnnoObject> =
    $props();
  let isHovered = $state(false);

  const object = $derived(annotation.object);

  const segmentRects = $derived(object.segmentRects ?? []);
  const rect = $derived(object.rect);

  // C - Border/stroke color
  const strokeColor = $derived(object.strokeColor ?? '#FF0000');
  // IC - Interior color (background fill when redaction is applied)
  const color = $derived(object.color ?? '#000000');
  // CA - Opacity (0-1)
  const opacity = $derived(object.opacity ?? 1);
  // OC - Overlay text color (Adobe extension), fallback to fontColor
  const textColor = $derived(object.fontColor ?? object.overlayColor ?? '#FFFFFF');
  // Overlay text properties
  const overlayText = $derived(object.overlayText);
  const overlayTextRepeat = $derived(object.overlayTextRepeat ?? false);
  const fontSize = $derived(object.fontSize ?? 12);
  const fontFamily = $derived(object.fontFamily ?? PdfStandardFont.Helvetica);
  const textAlign = $derived(object.textAlign ?? PdfTextAlignment.Center);

  // Calculate how many times to repeat text (approximate)
  function renderOverlayText(): string | null {
    if (!overlayText) return null;
    if (!overlayTextRepeat) return overlayText;
    // Repeat text multiple times to fill the space
    const reps = 10;
    return Array(reps).fill(overlayText).join(' ');
  }

  const justifyContent = $derived(
    textAlign === PdfTextAlignment.Left
      ? 'flex-start'
      : textAlign === PdfTextAlignment.Right
        ? 'flex-end'
        : 'center',
  );
</script>

<div
  role="group"
  onmouseenter={() => (isHovered = true)}
  onmouseleave={() => (isHovered = false)}
  style:position="absolute"
  style:inset="0"
>
  {#each segmentRects as b, i (i)}
    {@const left = (rect ? b.origin.x - rect.origin.x : b.origin.x) * scale}
    {@const top = (rect ? b.origin.y - rect.origin.y : b.origin.y) * scale}
    {@const width = b.size.width * scale}
    {@const height = b.size.height * scale}
    {@const scaledFontSize = Math.min(fontSize * scale, height * 0.8)}
    <div
      role="button"
      tabindex="0"
      onpointerdown={onClick}
      ontouchstart={onClick}
      style:position="absolute"
      style:left="{left}px"
      style:top="{top}px"
      style:width="{width}px"
      style:height="{height}px"
      style:background={isHovered ? color : 'transparent'}
      style:border={!isHovered ? `2px solid ${strokeColor}` : 'none'}
      style:opacity={isHovered ? opacity : 1}
      style:box-sizing="border-box"
      style:pointer-events="auto"
      style:cursor="pointer"
      style:display="flex"
      style:align-items="center"
      style:justify-content={justifyContent}
      style:overflow="hidden"
    >
      {#if isHovered && overlayText}
        <span
          style:color={textColor}
          style:font-size="{scaledFontSize}px"
          style:font-family={standardFontCss(fontFamily)}
          style:text-align={textAlignmentToCss(textAlign)}
          style:white-space={overlayTextRepeat ? 'normal' : 'nowrap'}
          style:overflow="hidden"
          style:text-overflow="ellipsis"
          style:line-height="1"
        >
          {renderOverlayText()}
        </span>
      {/if}
    </div>
  {/each}
</div>

// packages/plugin-redaction/src/vue/components/annotations/redact-highlight.vue
<template>
  <div
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
    :style="{ position: 'absolute', inset: 0 }"
  >
    <div
      v-for="(b, i) in segmentRects"
      :key="i"
      @pointerdown="onClick"
      @touchstart="onClick"
      :style="getSegmentStyle(b)"
    >
      <span v-if="isHovered && overlayText" :style="getTextStyle(b)">
        {{ renderedOverlayText }}
      </span>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, type CSSProperties } from 'vue';
import type { AnnotationRendererProps } from '@embedpdf/plugin-annotation/vue';
import type { PdfRedactAnnoObject, Rect } from '@embedpdf/models';
import {
  PdfStandardFont,
  PdfTextAlignment,
  standardFontCss,
  textAlignmentToCss,
} from '@embedpdf/models';

const props = defineProps<AnnotationRendererProps<PdfRedactAnnoObject>>();
const isHovered = ref(false);

// Access props.annotation.object directly in computed to maintain reactivity
const segmentRects = computed(() => props.annotation.object.segmentRects ?? []);
const rect = computed(() => props.annotation.object.rect);

// C - Border/stroke color
const strokeColor = computed(() => props.annotation.object.strokeColor ?? '#FF0000');
// IC - Interior color (background fill when redaction is applied)
const color = computed(() => props.annotation.object.color ?? '#000000');
// CA - Opacity (0-1)
const opacity = computed(() => props.annotation.object.opacity ?? 1);
// OC - Overlay text color (Adobe extension), fallback to fontColor
const textColor = computed(
  () => props.annotation.object.fontColor ?? props.annotation.object.overlayColor ?? '#FFFFFF',
);
// Overlay text properties
const overlayText = computed(() => props.annotation.object.overlayText);
const overlayTextRepeat = computed(() => props.annotation.object.overlayTextRepeat ?? false);
const fontSize = computed(() => props.annotation.object.fontSize ?? 12);
const fontFamily = computed(() => props.annotation.object.fontFamily ?? PdfStandardFont.Helvetica);
const textAlign = computed(() => props.annotation.object.textAlign ?? PdfTextAlignment.Center);

// Calculate how many times to repeat text (approximate)
const renderedOverlayText = computed(() => {
  if (!overlayText.value) return '';
  if (!overlayTextRepeat.value) return overlayText.value;
  // Repeat text multiple times to fill the space
  const reps = 10;
  return Array(reps).fill(overlayText.value).join(' ');
});

const getSegmentStyle = (b: Rect): CSSProperties => ({
  position: 'absolute',
  left: `${(rect.value ? b.origin.x - rect.value.origin.x : b.origin.x) * props.scale}px`,
  top: `${(rect.value ? b.origin.y - rect.value.origin.y : b.origin.y) * props.scale}px`,
  width: `${b.size.width * props.scale}px`,
  height: `${b.size.height * props.scale}px`,
  // Default: transparent background with strokeColor (C) border
  // Hovered: color (IC) background fill, no border
  background: isHovered.value ? color.value : 'transparent',
  border: !isHovered.value ? `2px solid ${strokeColor.value}` : 'none',
  opacity: isHovered.value ? opacity.value : 1,
  boxSizing: 'border-box',
  pointerEvents: 'auto',
  cursor: 'pointer',
  display: 'flex',
  alignItems: 'center',
  justifyContent:
    textAlign.value === PdfTextAlignment.Left
      ? 'flex-start'
      : textAlign.value === PdfTextAlignment.Right
        ? 'flex-end'
        : 'center',
  overflow: 'hidden',
});

const getTextStyle = (b: Rect): CSSProperties => ({
  color: textColor.value,
  fontSize: `${Math.min(fontSize.value * props.scale, b.size.height * props.scale * 0.8)}px`,
  fontFamily: standardFontCss(fontFamily.value),
  textAlign: textAlignmentToCss(textAlign.value),
  whiteSpace: overlayTextRepeat.value ? 'normal' : 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
  lineHeight: 1,
});
</script>
