// packages/plugin-tiling/src/shared/components/tile-img.tsx
import { ignore, PdfErrorCode } from '@embedpdf/models';
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useRef, useState } from '@framework';

import { useTilingCapability } from '../hooks/use-tiling';

interface TileImgProps {
  pageIndex: number;
  tile: Tile;
  dpr: number;
  scale: number;
}

export function TileImg({ pageIndex, tile, dpr, scale }: TileImgProps) {
  const { provides: tilingCapability } = useTilingCapability();
  const [url, setUrl] = useState<string>();
  const urlRef = useRef<string | null>(null);

  const relativeScale = scale / tile.srcScale;

  /* kick off render exactly once per tile */
  useEffect(() => {
    if (tile.status === 'ready' && urlRef.current) return; // already done
    if (!tilingCapability) return;
    const task = tilingCapability.renderTile({ pageIndex, tile, dpr });
    task.wait((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      urlRef.current = objectUrl;
      setUrl(objectUrl);
    }, ignore);

    return () => {
      if (urlRef.current) {
        URL.revokeObjectURL(urlRef.current);
        urlRef.current = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled render task',
        });
      }
    };
  }, [pageIndex, tile.id]); // id includes scale, so unique

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  if (!url) return null; // could render a placeholder
  return (
    <img
      src={url}
      onLoad={handleImageLoad}
      style={{
        position: 'absolute',
        left: tile.screenRect.origin.x * relativeScale,
        top: tile.screenRect.origin.y * relativeScale,
        width: tile.screenRect.size.width * relativeScale,
        height: tile.screenRect.size.height * relativeScale,
        display: 'block',
      }}
    />
  );
}

// packages/plugin-tiling/src/svelte/components/TileImg.svelte
<script lang="ts">
  import type { Tile } from '@embedpdf/plugin-tiling';
  import { useTilingCapability } from '../hooks';
  import { ignore, PdfErrorCode } from '@embedpdf/models';

  interface TileImgProps {
    pageIndex: number;
    tile: Tile;
    dpr: number;
    scale: number;
  }

  let { pageIndex, tile, dpr, scale }: TileImgProps = $props();
  const { provides: tilingCapability } = $derived(useTilingCapability());
  let url = $state<string>('');
  let urlRef = $state<string | null>(null);

  const relativeScale = scale / tile.srcScale;

  /* kick off render exactly once per tile */
  $effect(() => {
    // use tile.id as effect dependency
    const _tileId = tile.id;

    if (tile.status === 'ready' && urlRef) return; // already done
    if (!tilingCapability) return;
    const task = tilingCapability.renderTile({ pageIndex, tile, dpr });
    task.wait((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      urlRef = objectUrl;
      url = objectUrl;
    }, ignore);

    return () => {
      if (urlRef) {
        URL.revokeObjectURL(urlRef);
        urlRef = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled render task',
        });
      }
    };
  });

  const handleImageLoad = () => {
    if (urlRef) {
      URL.revokeObjectURL(urlRef);
      urlRef = null;
    }
  };
</script>

{#if url}
  <img
    src={url}
    alt=""
    onLoad={handleImageLoad}
    style:postion="absolute"
    style:left={`${tile.screenRect.origin.x * relativeScale}px`}
    style:top={`${tile.screenRect.origin.y * relativeScale}px`}
    style:width={`${tile.screenRect.size.width * relativeScale}px`}
    style:height={`${tile.screenRect.size.height * relativeScale}px`}
    style:display="block"
  />
{/if}
