// packages/plugin-tiling/src/preact/components/tiling-layer.tsx
/** @jsxImportSource preact */
import { JSX } from 'preact';
import { useEffect, useState } from 'preact/hooks';
import { Tile } from '@embedpdf/plugin-tiling';
import { useTilingCapability } from '../hooks/use-tiling';
import { TileImg } from './tile-img';

type TilingLayoutProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, 'style'> & {
  pageIndex: number;
  scale: number;
  style?: JSX.CSSProperties;
};

export function TilingLayer({ pageIndex, scale, style, ...props }: TilingLayoutProps) {
  const { provides: tilingProvides } = useTilingCapability();
  const [tiles, setTiles] = useState<Tile[]>([]);

  useEffect(() => {
    if (tilingProvides) {
      return tilingProvides.onTileRendering((tiles) => setTiles(tiles[pageIndex]));
    }
  }, [tilingProvides]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      {tiles?.map((tile) => (
        <TileImg
          key={tile.id}
          pageIndex={pageIndex}
          tile={tile}
          dpr={window.devicePixelRatio}
          scale={scale}
        />
      ))}
    </div>
  );
}

// packages/plugin-tiling/src/svelte/components/TilingLayer.svelte
<script lang="ts">
  import type { Tile } from '@embedpdf/plugin-tiling';
  import type { HTMLAttributes } from 'svelte/elements';
  import TileImg from './TileImg.svelte';
  import { useTilingCapability } from '../hooks';

  type TilingLayoutProps = HTMLAttributes<HTMLDivElement> & {
    pageIndex: number;
    scale: number;
    class?: string;
  };

  let { pageIndex, scale, class: propsClass, ...restProps }: TilingLayoutProps = $props();

  const { provides: tilingProvides } = $derived(useTilingCapability());
  let tiles = $state<Tile[]>([]);

  $effect(() => {
    if (!tilingProvides) return;
    return tilingProvides.onTileRendering((tilesMap) => {
      tiles = tilesMap[pageIndex] ?? [];
    });
  });
</script>

<div class={propsClass} {...restProps}>
  {#each tiles as tile (tile.id)}
    <TileImg {pageIndex} {tile} dpr={window.devicePixelRatio} {scale} />
  {/each}
</div>
