// packages/plugin-annotation/src/svelte/components/text-markup/Underline.svelte
<script lang="ts">
  import type { Rect } from '@embedpdf/models';

  interface UnderlineProps {
    /** Stroke/markup color */
    strokeColor?: string;
    opacity?: number;
    segmentRects: Rect[];
    rect?: Rect;
    scale: number;
    onClick?: (e: MouseEvent | TouchEvent) => void;
    style?: Record<string, string | number | undefined>;
  }

  let {
    strokeColor,
    opacity = 0.5,
    segmentRects,
    rect,
    scale,
    onClick,
    style,
  }: UnderlineProps = $props();

  const resolvedColor = $derived(strokeColor ?? '#FFFF00');
  const thickness = $derived(2 * scale); // 2 CSS px at 100% zoom
</script>

{#each segmentRects as r, i (i)}
  <div
    role="button"
    tabindex={onClick ? 0 : -1}
    onpointerdown={onClick}
    ontouchstart={onClick}
    style:position="absolute"
    style:left="{(rect ? r.origin.x - rect.origin.x : r.origin.x) * scale}px"
    style:top="{(rect ? r.origin.y - rect.origin.y : r.origin.y) * scale}px"
    style:width="{r.size.width * scale}px"
    style:height="{r.size.height * scale}px"
    style:background="transparent"
    style:pointer-events={onClick ? 'auto' : 'none'}
    style:cursor={onClick ? 'pointer' : 'default'}
    style:z-index={onClick ? 1 : 0}
    {...style ? Object.fromEntries(Object.entries(style).map(([k, v]) => [`style:${k}`, v])) : {}}
  >
    <!-- Visual underline -->
    <div
      style:position="absolute"
      style:left="0"
      style:bottom="0"
      style:width="100%"
      style:height="{thickness}px"
      style:background={resolvedColor}
      style:opacity
      style:pointer-events="none"
    ></div>
  </div>
{/each}

// packages/plugin-annotation/src/preact/components/text-markup/underline.tsx
/** @jsxImportSource preact */
import { JSX } from 'preact';
import { Rect } from '@embedpdf/models';

type UnderlineProps = Omit<JSX.HTMLAttributes<HTMLDivElement>, 'style'> & {
  color?: string;
  opacity?: number;
  rects: Rect[];
  rect?: Rect;
  scale: number;
  onClick?: (e: MouseEvent) => void;
  style?: JSX.CSSProperties;
};

export function Underline({
  color = '#FFFF00',
  opacity = 0.5,
  rects,
  rect,
  scale,
  onClick,
  style,
  ...props
}: UnderlineProps) {
  const thickness = 2 * scale; // 2 CSS px at 100 % zoom

  return (
    <>
      {rects.map((r, i) => (
        <div
          key={i}
          onMouseDown={onClick}
          style={{
            position: 'absolute',
            left: (rect ? r.origin.x - rect.origin.x : r.origin.x) * scale,
            top: (rect ? r.origin.y - rect.origin.y : r.origin.y) * scale,
            width: r.size.width * scale,
            height: r.size.height * scale,
            background: 'transparent',
            pointerEvents: onClick ? 'auto' : 'none',
            cursor: onClick ? 'pointer' : 'default',
            zIndex: onClick ? 1 : 0,
            ...style,
          }}
          {...props}
        >
          {/* Visual underline */}
          <div
            style={{
              position: 'absolute',
              left: 0,
              bottom: 0,
              width: '100%',
              height: thickness,
              background: color,
              opacity: opacity,
              pointerEvents: 'none',
            }}
          />
        </div>
      ))}
    </>
  );
}
