// packages/plugin-scroll/src/react/components/scroller.tsx
import React, { ReactNode, useEffect, useState } from 'react';
import { ScrollStrategy, ScrollerLayout, PageLayout } from '@embedpdf/plugin-scroll';
import { useRegistry } from '@embedpdf/core/react';
import { PdfDocumentObject, Rotation } from '@embedpdf/models';

import { useScrollCapability, useScrollPlugin } from '../hooks';

interface RenderPageProps extends PageLayout {
  rotation: Rotation;
  scale: number;
  document: PdfDocumentObject | null;
}

type ScrollerProps = React.HTMLAttributes<HTMLDivElement> & {
  renderPage: (props: RenderPageProps) => ReactNode;
  overlayElements?: ReactNode[];
};

export function Scroller({ renderPage, overlayElements, ...props }: ScrollerProps) {
  const { provides: scrollProvides } = useScrollCapability();
  const { plugin: scrollPlugin } = useScrollPlugin();
  const { registry } = useRegistry();
  const [scrollerLayout, setScrollerLayout] = useState<ScrollerLayout | null>(
    () => scrollProvides?.getScrollerLayout() ?? null,
  );

  useEffect(() => {
    if (!scrollProvides) return;

    return scrollProvides.onScrollerData(setScrollerLayout);
  }, [scrollProvides]);

  useEffect(() => {
    if (!scrollPlugin) return;

    scrollPlugin.setLayoutReady();
  }, [scrollPlugin]);

  if (!scrollerLayout) return null;
  if (!registry) return null;

  const coreState = registry.getStore().getState();

  return (
    <div
      {...props}
      style={{
        width: `${scrollerLayout.totalWidth}px`,
        height: `${scrollerLayout.totalHeight}px`,
        position: 'relative',
        boxSizing: 'border-box',
        margin: '0 auto',
        ...(scrollerLayout.strategy === ScrollStrategy.Horizontal && {
          display: 'flex',
          flexDirection: 'row',
        }),
      }}
    >
      <div
        style={{
          ...(scrollerLayout.strategy === ScrollStrategy.Horizontal
            ? {
                width: scrollerLayout.startSpacing,
                height: '100%',
                flexShrink: 0,
              }
            : {
                height: scrollerLayout.startSpacing,
                width: '100%',
              }),
        }}
      />
      <div
        style={{
          gap: scrollerLayout.pageGap,
          display: 'flex',
          alignItems: 'center',
          position: 'relative',
          boxSizing: 'border-box',
          ...(scrollerLayout.strategy === ScrollStrategy.Horizontal
            ? {
                flexDirection: 'row',
                minHeight: '100%',
              }
            : {
                flexDirection: 'column',
                minWidth: 'fit-content',
              }),
        }}
      >
        {scrollerLayout.items.map((item) => (
          <div
            key={item.pageNumbers[0]}
            style={{
              display: 'flex',
              justifyContent: 'center',
              gap: scrollerLayout.pageGap,
            }}
          >
            {item.pageLayouts.map((layout) => (
              <div
                key={layout.pageNumber}
                style={{
                  width: `${layout.rotatedWidth}px`,
                  height: `${layout.rotatedHeight}px`,
                }}
              >
                {renderPage({
                  ...layout,
                  rotation: coreState.core.rotation,
                  scale: coreState.core.scale,
                  document: coreState.core.document,
                })}
              </div>
            ))}
          </div>
        ))}
      </div>
      <div
        style={{
          ...(scrollerLayout.strategy === ScrollStrategy.Horizontal
            ? {
                width: scrollerLayout.endSpacing,
                height: '100%',
                flexShrink: 0,
              }
            : {
                height: scrollerLayout.endSpacing,
                width: '100%',
              }),
        }}
      />
      {overlayElements}
    </div>
  );
}

// packages/plugin-scroll/src/vue/components/scroller.vue
<script setup lang="ts">
import { computed, onMounted, ref, watchEffect, useAttrs } from 'vue';
import type { StyleValue } from 'vue';
import { useRegistry } from '@embedpdf/core/vue';

import { useScrollCapability, useScrollPlugin } from '../hooks';
import { ScrollStrategy, type ScrollerLayout, type PageLayout } from '@embedpdf/plugin-scroll';
import type { PdfDocumentObject, Rotation } from '@embedpdf/models';

/* -------------------------------------------------- */
/* props                                              */
/* -------------------------------------------------- */
interface RenderPageProps extends PageLayout {
  rotation: Rotation;
  scale: number;
  document: PdfDocumentObject | null;
}

const props = withDefaults(
  defineProps<{
    style?: StyleValue;
    renderPage: (p: RenderPageProps) => any;
    overlayElements?: any[];
  }>(),
  { overlayElements: () => [] },
);

const attrs = useAttrs();

/* -------------------------------------------------- */
/* plugin + state                                     */
/* -------------------------------------------------- */
const { provides: scrollProvides } = useScrollCapability();
const { plugin: scrollPlugin } = useScrollPlugin();
const { registry } = useRegistry();

const layout = ref<ScrollerLayout | null>(null);

/* subscribe to scroller‑data */
watchEffect((onCleanup) => {
  if (!scrollProvides.value) return;

  layout.value = scrollProvides.value.getScrollerLayout();
  const off = scrollProvides.value.onScrollerData((l) => (layout.value = l));
  onCleanup(off);
});

/* mark layout ready once plugin instance exists */
onMounted(() => {
  if (scrollPlugin.value) scrollPlugin.value.setLayoutReady();
});

/* -------------------------------------------------- */
/* combined root style                                */
/* -------------------------------------------------- */
const rootStyle = computed<StyleValue>(() => {
  if (!layout.value) return props.style;

  const base =
    typeof props.style === 'object' && !Array.isArray(props.style)
      ? { ...props.style }
      : (props.style ?? {});

  return [
    base,
    {
      width: `${layout.value.totalWidth}px`,
      height: `${layout.value.totalHeight}px`,
      position: 'relative',
      boxSizing: 'border-box',
      margin: '0 auto',
      ...(layout.value.strategy === ScrollStrategy.Horizontal && {
        display: 'flex',
        flexDirection: 'row',
      }),
    },
  ];
});
</script>

<template>
  <div :style="rootStyle" v-bind="attrs" v-if="layout && registry">
    <!-- leading spacer -->
    <div
      v-if="layout.strategy === 'horizontal'"
      :style="{ width: layout.startSpacing + 'px', height: '100%', flexShrink: 0 }"
    />
    <div v-else :style="{ height: layout.startSpacing + 'px', width: '100%' }" />

    <!-- page grid -->
    <div
      :style="{
        gap: layout.pageGap + 'px',
        display: 'flex',
        alignItems: 'center',
        position: 'relative',
        boxSizing: 'border-box',
        flexDirection: layout.strategy === 'horizontal' ? 'row' : 'column',
        minHeight: layout.strategy === 'horizontal' ? '100%' : undefined,
        minWidth: layout.strategy === 'vertical' ? 'fit-content' : undefined,
      }"
    >
      <template v-for="item in layout.items" :key="item.pageNumbers[0]">
        <div
          :style="{
            display: 'flex',
            justifyContent: 'center',
            gap: layout.pageGap + 'px',
          }"
        >
          <div
            v-for="pl in item.pageLayouts"
            :key="pl.pageNumber"
            :style="{ width: pl.rotatedWidth + 'px', height: pl.rotatedHeight + 'px' }"
          >
            <!-- call the renderPage prop -->
            <component
              :is="props.renderPage"
              v-bind="{
                ...pl,
                rotation: registry.getStore().getState().core.rotation,
                scale: registry.getStore().getState().core.scale,
                document: registry.getStore().getState().core.document,
              }"
            />
          </div>
        </div>
      </template>
    </div>

    <!-- trailing spacer -->
    <div
      v-if="layout.strategy === 'horizontal'"
      :style="{ width: layout.endSpacing + 'px', height: '100%', flexShrink: 0 }"
    />
    <div v-else :style="{ height: layout.endSpacing + 'px', width: '100%' }" />

    <!-- overlay elements -->
    <component v-for="(el, i) in props.overlayElements" :is="el" :key="i" />
  </div>
</template>
