// packages/plugin-tiling/src/shared/components/tile-img.tsx
import { ignore, PdfErrorCode } from '@embedpdf/models';
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useRef, useState } from '@framework';

import { useTilingCapability, useTilingPlugin } from '../hooks/use-tiling';

interface TileImgProps {
  pageIndex: number;
  tile: Tile;
  dpr: number;
  scale: number;
}

export function TileImg({ pageIndex, tile, dpr, scale }: TileImgProps) {
  const { provides: tilingCapability } = useTilingCapability();
  const { plugin: tilingPlugin } = useTilingPlugin();

  const [url, setUrl] = useState<string>();
  const urlRef = useRef<string | null>(null);
  const [refreshTick, setRefreshTick] = useState(0);

  const relativeScale = scale / tile.srcScale;

  useEffect(() => {
    if (!tilingPlugin) return;
    return tilingPlugin.onRefreshPages((pages) => {
      if (pages.includes(pageIndex)) {
        setRefreshTick((tick) => tick + 1);
      }
    });
  }, [tilingPlugin]);

  /* kick off render exactly once per tile */
  useEffect(() => {
    if (tile.status === 'ready' && urlRef.current) return; // already done
    if (!tilingCapability) return;
    const task = tilingCapability.renderTile({ pageIndex, tile, dpr });
    task.wait((blob) => {
      const objectUrl = URL.createObjectURL(blob);
      urlRef.current = objectUrl;
      setUrl(objectUrl);
    }, ignore);

    return () => {
      if (urlRef.current) {
        URL.revokeObjectURL(urlRef.current);
        urlRef.current = null;
      } else {
        task.abort({
          code: PdfErrorCode.Cancelled,
          message: 'canceled render task',
        });
      }
    };
  }, [pageIndex, tile.id, refreshTick]); // id includes scale, so unique

  const handleImageLoad = () => {
    if (urlRef.current) {
      URL.revokeObjectURL(urlRef.current);
      urlRef.current = null;
    }
  };

  if (!url) return null; // could render a placeholder
  return (
    <img
      src={url}
      onLoad={handleImageLoad}
      style={{
        position: 'absolute',
        left: tile.screenRect.origin.x * relativeScale,
        top: tile.screenRect.origin.y * relativeScale,
        width: tile.screenRect.size.width * relativeScale,
        height: tile.screenRect.size.height * relativeScale,
        display: 'block',
      }}
    />
  );
}

// packages/plugin-tiling/src/vue/components/tile-img.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, toRaw, computed, watchEffect, watch } from 'vue';
import { ignore, PdfErrorCode, PdfErrorReason, Task } from '@embedpdf/models';
import type { StyleValue } from 'vue';

import type { Tile } from '@embedpdf/plugin-tiling';
import { useTilingCapability, useTilingPlugin } from '../hooks';

interface Props {
  pageIndex: number;
  tile: Tile;
  scale: number;
  dpr?: number;
  style?: StyleValue;
}

const props = withDefaults(defineProps<Props>(), {
  dpr: () => window.devicePixelRatio,
});

const { provides: tilingCapability } = useTilingCapability();
const { plugin: tilingPlugin } = useTilingPlugin();

const url = ref<string>();
const refreshTick = ref(0);
let blobUrl: string | null = null;
let renderTask: Task<Blob, PdfErrorReason> | null = null;

/* -------------------------------------------------- */
/* Helper functions                                   */
/* -------------------------------------------------- */
function revoke() {
  if (blobUrl) {
    URL.revokeObjectURL(blobUrl);
    blobUrl = null;
  }
}

function abortCurrentTask() {
  if (renderTask && !blobUrl) {
    renderTask.abort({
      code: PdfErrorCode.Cancelled,
      message: 'canceled tile render',
    });
  }
}

/* -------------------------------------------------- */
/* Watch for external refresh events                  */
/* -------------------------------------------------- */
watchEffect((onCleanup) => {
  if (!tilingPlugin.value) return;
  const unsubscribe = tilingPlugin.value.onRefreshPages((pages) => {
    if (pages.includes(props.pageIndex)) {
      refreshTick.value++;
    }
  });
  onCleanup(unsubscribe);
});

/* -------------------------------------------------- */
/* start render task when dependencies change         */
/* -------------------------------------------------- */
function startRender() {
  if (props.tile.status === 'ready' && blobUrl) return; // already done
  if (!tilingCapability.value) return;

  abortCurrentTask();
  revoke();

  const task = tilingCapability.value.renderTile({
    pageIndex: props.pageIndex,
    tile: toRaw(props.tile),
    dpr: props.dpr,
  });

  renderTask = task;
  task.wait((blob) => {
    blobUrl = URL.createObjectURL(blob);
    url.value = blobUrl;
    renderTask = null; // Task completed
  }, ignore);
}

// Watch for changes that require a re-render
watch(
  () => [props.pageIndex, props.tile.id, refreshTick.value, !!tilingCapability.value],
  startRender,
  { immediate: true },
);

/* -------------------------------------------------- */
/* cleanup                                            */
/* -------------------------------------------------- */
onBeforeUnmount(() => {
  abortCurrentTask();
  revoke();
});

/* -------------------------------------------------- */
/* helpers                                            */
/* -------------------------------------------------- */
const relScale = computed(() => props.scale / props.tile.srcScale);
</script>

<template>
  <img
    v-if="url"
    :src="url"
    :style="[
      {
        position: 'absolute',
        left: tile.screenRect.origin.x * relScale + 'px',
        top: tile.screenRect.origin.y * relScale + 'px',
        width: tile.screenRect.size.width * relScale + 'px',
        height: tile.screenRect.size.height * relScale + 'px',
        display: 'block',
      },
      props.style,
    ]"
    @load="revoke"
  />
</template>
