// packages/plugin-tiling/src/react/components/tiling-layer.tsx
import { Tile } from '@embedpdf/plugin-tiling';
import { useEffect, useState } from 'react';

import { TileImg } from './tile-img';
import { useTilingCapability } from '../hooks/use-tiling';

type TilingLayoutProps = Omit<React.HTMLAttributes<HTMLDivElement>, 'style'> & {
  pageIndex: number;
  scale: number;
  style?: React.CSSProperties;
};

export function TilingLayer({ pageIndex, scale, style, ...props }: TilingLayoutProps) {
  const { provides: tilingProvides } = useTilingCapability();
  const [tiles, setTiles] = useState<Tile[]>([]);

  useEffect(() => {
    if (tilingProvides) {
      return tilingProvides.onTileRendering((tiles) => setTiles(tiles[pageIndex]));
    }
  }, [tilingProvides]);

  return (
    <div
      style={{
        ...style,
      }}
      {...props}
    >
      {tiles?.map((tile) => (
        <TileImg
          key={tile.id}
          pageIndex={pageIndex}
          tile={tile}
          dpr={window.devicePixelRatio}
          scale={scale}
        />
      ))}
    </div>
  );
}

// packages/plugin-tiling/src/vue/components/tiling-layer.vue
<script setup lang="ts">
import type { Tile } from '@embedpdf/plugin-tiling';
import { ref, onMounted, onBeforeUnmount } from 'vue';
import type { StyleValue } from 'vue';

import { useTilingCapability } from '../hooks';
import TileImg from './tile-img.vue';

interface Props {
  pageIndex: number;
  scale: number;
  style?: StyleValue;
}

const props = defineProps<Props>();

const tiles = ref<Tile[]>([]);
const { provides: tilingProvides } = useTilingCapability();

let unsubscribe: (() => void) | undefined;

onMounted(() => {
  if (tilingProvides.value) {
    unsubscribe = tilingProvides.value.onTileRendering((tilesMap) => {
      tiles.value = tilesMap[props.pageIndex] ?? [];
    });
  }
});

onBeforeUnmount(() => {
  unsubscribe?.();
});
</script>

<template>
  <div :style="style" v-bind="$attrs">
    <TileImg
      v-for="tile in tiles"
      :key="tile.id"
      :pageIndex="pageIndex"
      :tile="tile"
      :scale="scale"
    />
  </div>
</template>
